compressionLevel: mixed

enableGlobalCache: false

npmMinimalAgeGate: 0 # minimum age in minutes (24 hours)

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.0.cjs

enableTelemetry: false
