compressionLevel: mixed

enableGlobalCache: false

npmMinimalAgeGate: 1440 # minimum age in minutes (24 hours)

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.16.0.cjs

enableTelemetry: false
