compressionLevel: mixed

enableGlobalCache: false

httpProxy: "http://proxy.jpmchase.net:9443"

httpsProxy: "http://proxy.jpmchase.net:9443"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs
