httpProxy: "http://approxy.jpmchase.net:8080"

httpsProxy: "http://approxy.jpmchase.net:8080"

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
