export const validationExampleData = [
  {
    value: 79,
    min: 27,
    max: 73,
    status: "warning",
    color: "Yellow",
    currency: "AUD",
  },
  {
    value: 94,
    min: 24,
    max: 95,
    status: "success",
    color: "Black",
    currency: "GBP",
  },
  {
    value: 60,
    min: 43,
    max: 80,
    status: "warning",
    color: "Blue",
    currency: "USD",
  },
  {
    value: 62,
    min: 36,
    max: 88,
    status: "success",
    color: "Blue",
    currency: "CAD",
  },
  {
    value: 94,
    min: 46,
    max: 92,
    status: "warning",
    color: "Purple",
    currency: "USD",
  },
  {
    value: 56,
    min: 42,
    max: 75,
    status: "default",
    color: "Brown",
    currency: "EUR",
  },
  {
    value: 92,
    min: 41,
    max: 98,
    status: "error",
    color: "Blue",
    currency: "GBP",
  },
  {
    value: 63,
    min: 16,
    max: 74,
    status: "warning",
    color: "Yellow",
    currency: "USD",
  },
  {
    value: 44,
    min: 42,
    max: 89,
    status: "error",
    color: "Baby blue",
    currency: "ZAR",
  },
  {
    value: 92,
    min: 4,
    max: 50,
    status: "success",
    color: "Brown",
    currency: "NZD",
  },
  {
    value: 7,
    min: 35,
    max: 85,
    status: "default",
    color: "Pink",
    currency: "USD",
  },
  {
    value: 37,
    min: 11,
    max: 56,
    status: "error",
    color: "Yellow",
    currency: "JPY",
  },
  {
    value: 51,
    min: 35,
    max: 57,
    status: "warning",
    color: "Green",
    currency: "NZD",
  },
  {
    value: 49,
    min: 41,
    max: 95,
    status: "success",
    color: "Green",
    currency: "USD",
  },
  {
    value: 92,
    min: 24,
    max: 76,
    status: "default",
    color: "Baby blue",
    currency: "GBP",
  },
  {
    value: 47,
    min: 10,
    max: 76,
    status: "warning",
    color: "Blue",
    currency: "JPY",
  },
  {
    value: 62,
    min: 46,
    max: 81,
    status: "success",
    color: "Yellow",
    currency: "USD",
  },
  {
    value: 33,
    min: 37,
    max: 78,
    status: "success",
    color: "Brown",
    currency: "CAD",
  },
  {
    value: 49,
    min: 45,
    max: 76,
    status: "success",
    color: "Orange",
    currency: "ZAR",
  },
  {
    value: 0,
    min: 0,
    max: 63,
    status: "warning",
    color: "White",
    currency: "EUR",
  },
  {
    value: 66,
    min: 14,
    max: 90,
    status: "default",
    color: "Green",
    currency: "NZD",
  },
  {
    value: 98,
    min: 0,
    max: 70,
    status: "warning",
    color: "White",
    currency: "AUD",
  },
  {
    value: 13,
    min: 27,
    max: 71,
    status: "warning",
    color: "Pink",
    currency: "JPY",
  },
  {
    value: 85,
    min: 5,
    max: 57,
    status: "default",
    color: "White",
    currency: "USD",
  },
  {
    value: 10,
    min: 13,
    max: 63,
    status: "default",
    color: "Pink",
    currency: "JPY",
  },
  {
    value: 77,
    min: 48,
    max: 61,
    status: "warning",
    color: "Pink",
    currency: "NZD",
  },
  {
    value: 28,
    min: 19,
    max: 85,
    status: "success",
    color: "Purple",
    currency: "ZAR",
  },
  {
    value: 61,
    min: 8,
    max: 65,
    status: "default",
    color: "Purple",
    currency: "AUD",
  },
  {
    value: 35,
    min: 16,
    max: 58,
    status: "error",
    color: "Orange",
    currency: "EUR",
  },
  {
    value: 45,
    min: 33,
    max: 79,
    status: "default",
    color: "Pink",
    currency: "JPY",
  },
];
