// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type AUProps = CountrySymbolProps;

const AU = forwardRef<SVGSVGElement, AUProps>(function AU(props: AUProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="AU"
      aria-label="Australia"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-AU-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-AU-a)`}>
        <path fill="#004692" d="M0 0h20v20H0z" />
        <path
          fill="#F5F7F8"
          d="m7.5 12.056.615 1.32 1.39-.33-.622 1.316 1.117.91-1.391.32.004 1.463L7.5 16.14l-1.113.915.004-1.462L5 15.27l1.117-.909-.622-1.316 1.39.33.615-1.32Zm6.667.833.41.88.926-.22-.415.878.745.606-.927.214.002.975-.741-.61-.742.61.002-.975-.927-.214.745-.606-.415-.878.926.22.41-.88Zm-1.945-6.667.342.733.772-.183-.346.732.621.505-.773.178.002.813-.618-.508-.618.508.002-.813-.773-.178.621-.505-.346-.732.772.183.342-.733ZM15 4l.342.733.772-.183-.346.731.62.505-.772.18.002.812L15 6.269l-.618.509.002-.813-.773-.179.62-.505-.345-.73.772.182L15 4Zm2.778 2.778.342.733.772-.183-.346.731.62.505-.772.179.002.813-.618-.509-.618.509.002-.813-.773-.179.62-.505-.345-.731.772.183.342-.733Z"
        />
        <circle cx="15.694" cy="10.528" r=".694" fill="#F5F7F8" />
        <mask
          id={`${uid}-AU-b`}
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path fill="#002F6C" d="M0 10C0 4.477 4.477 0 10 0v10H0Z" />
        </mask>
        <g mask={`url(#${uid}-AU-b)`}>
          <path
            fill="#F5F7F8"
            d="m3.478.87-.589.59 8.202 8.201.59-.589L3.477.871ZM1.907 2.442l-.982.982 8.202 8.202.982-.982-8.202-8.202Z"
          />
          <path
            fill="#DD2033"
            d="m1.907 2.442.982-.982 8.202 8.201-.982.982-8.202-8.201Z"
          />
          <path fill="#F5F7F8" d="M10 3.333v1.39H4.722V10H3.333V3.333H10Z" />
          <path fill="#F5F7F8" d="M10-.556v1.39H1.389V10H0V-.556h10Z" />
          <path
            fill="#DD2033"
            fillRule="evenodd"
            d="M.833 10h2.5V3.333H10v-2.5H.833V10Z"
            clipRule="evenodd"
          />
        </g>
      </g>
    </CountrySymbol>
  );
});

export default AU;
