// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type BI_SharpProps = CountrySymbolProps;

const BI_Sharp = forwardRef<SVGSVGElement, BI_SharpProps>(function BI_Sharp(
  props: BI_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="BI_Sharp"
      aria-label="Burundi"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-BI-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-BI-a)`}>
        <path fill="#A00009" d="M0 0h29v20H0z" />
        <path
          fill="#009B77"
          d="m0-4.4 14.5 14L29-4.4v28.8L14.5 9.6 0 24.4V-4.4Z"
        />
        <path
          fill="#F5F7F8"
          d="m24.408-2.8 2.564 2.546-5.804 5.763A7.925 7.925 0 0 1 22.555 10a7.92 7.92 0 0 1-1.037 3.93l6.676 6.63-2.563 2.546-6.561-6.517A8.057 8.057 0 0 1 14.5 18a8.057 8.057 0 0 1-4.522-1.378l-6.152 6.11-2.563-2.546 6.248-6.205A7.921 7.921 0 0 1 6.444 10c0-1.685.525-3.249 1.421-4.538L2.109-.254 4.672-2.8l5.87 5.83A8.062 8.062 0 0 1 14.5 2c1.46 0 2.828.385 4.008 1.06l5.9-5.86Z"
        />
        <path
          fill="#A00009"
          d="m14.661 4-.72 1.618-1.697.215 1.252 1.216-.329 1.751 1.494-1 1.494 1-.328-1.751 1.25-1.216-1.696-.215L14.661 4Zm-4.028 5.2-.72 1.618-1.696.215 1.25 1.216L9.14 14l1.493-1 1.494 1-.328-1.751 1.25-1.216-1.695-.215-.72-1.618Zm7.653 0-.72 1.618-1.697.215 1.252 1.216L16.792 14l1.494-1 1.494 1-.328-1.751 1.25-1.216-1.696-.215-.72-1.618Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default BI_Sharp;
