// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type BR_SharpProps = CountrySymbolProps;

const BR_Sharp = forwardRef<SVGSVGElement, BR_SharpProps>(function BR_Sharp(
  props: BR_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="BR_Sharp"
      aria-label="Brazil"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-BR-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-BR-a)`}>
        <path fill="#008259" d="M0 0h29v20H0z" />
        <path
          fill="#F1B434"
          d="M14.5 1.2 26.583 10 14.5 18.8 2.417 10 14.5 1.2Z"
        />
        <path
          fill="#004692"
          d="M14.701 15.6c3.003 0 5.438-2.507 5.438-5.6 0-3.093-2.435-5.6-5.438-5.6-3.003 0-5.437 2.507-5.437 5.6 0 3.093 2.434 5.6 5.437 5.6Z"
        />
        <path
          fill="#F5F7F8"
          d="M9.345 9.03a9.97 9.97 0 0 1 2.134-.23c3.196 0 6.083 1.52 7.976 3.92a5.68 5.68 0 0 0 .667-2.274C17.902 8.192 14.849 6.8 11.479 6.8c-.434 0-.863.023-1.286.068a5.664 5.664 0 0 0-.848 2.162Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default BR_Sharp;
