// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type BWProps = CountrySymbolProps;

const BW = forwardRef<SVGSVGElement, BWProps>(function BW(props: BWProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="BW"
      aria-label="Botswana"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-BW-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-BW-a)`}>
        <path fill="#86C5FA" d="M0 20V0h20v20z" />
        <path fill="#F5F7F8" d="M0 13.333V6.666h20v6.667z" />
        <path fill="#31373D" d="M0 11.667V8.334h20v3.333z" />
      </g>
    </CountrySymbol>
  );
});

export default BW;
