// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type CC_SharpProps = CountrySymbolProps;

const CC_Sharp = forwardRef<SVGSVGElement, CC_SharpProps>(function CC_Sharp(
  props: CC_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="CC_Sharp"
      aria-label="Cocos (Keeling) Islands (the)"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-CC-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-CC-a)`}>
        <path fill="#008259" d="M0 0h29v20H0z" />
        <ellipse cx="5.8" cy="5.2" fill="#F1B434" rx="3.625" ry="3.6" />
        <path fill="#936846" d="M5.397 4.8h.806V8h-.806z" />
        <path
          fill="#009B77"
          d="m5.8 2.4.396.845.896-.211-.401.842.72.582-.897.206.003.936-.717-.586-.717.586.002-.936-.896-.206.72-.582-.401-.842.895.21L5.8 2.4Z"
        />
        <path
          fill="#F1B434"
          d="M22.71 2.845 22.314 2l-.397.845-.895-.211.4.842-.72.582.897.206-.002.936.717-.586.717.586-.003-.936.897-.206-.72-.582.4-.842-.895.21ZM15.265 5.8c.248 0 .488.03.719.085a3.626 3.626 0 0 0-2.129-.685c-2.002 0-3.625 1.612-3.625 3.6s1.623 3.6 3.625 3.6c.796 0 1.531-.254 2.129-.685a3.09 3.09 0 0 1-.719.085 3.01 3.01 0 0 1-3.02-3c0-1.657 1.352-3 3.02-3Zm3.418 2.645-.397-.845-.396.845-.896-.211.401.842-.72.582.897.206-.003.936.717-.586.717.586-.002-.936.896-.206-.72-.582.401-.842-.895.21Zm2.422 6.755.397.845.896-.211-.401.842.72.582-.897.206.003.936-.718-.586-.716.586.002-.936-.897-.206.72-.582-.4-.842.895.21.396-.844Zm4.431-8 .397.845.895-.211-.401.842.72.582-.896.206.002.936-.717-.586-.717.586.003-.936-.897-.206.72-.582-.4-.842.895.21.396-.844Zm-1.611 5.6a.803.803 0 0 0 .805-.8c0-.442-.36-.8-.805-.8a.803.803 0 0 0-.806.8c0 .442.361.8.806.8Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default CC_Sharp;
