// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";
import { useId } from "@salt-ds/core";
import { clsx } from "clsx";

import { CountrySymbol, CountrySymbolProps } from "../country-symbol";

export type CG_SharpProps = CountrySymbolProps;

const CG_Sharp = forwardRef<SVGSVGElement, CG_SharpProps>(function CG_Sharp(
  props: CG_SharpProps,
  ref
) {
  const uid = useId(props.id);

  const { className, ...rest } = props;

  return (
    <CountrySymbol
      data-testid="CG_Sharp"
      aria-label="Congo (the)"
      viewBox="0 0 72 50"
      ref={ref}
      className={clsx(className, { saltSharpCountrySymbol: true })}
      {...rest}
    >
      <mask
        id={`${uid}-CG-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h72v50H0z" />
      </mask>
      <g mask={`url(#${uid}-CG-a)`}>
        <path
          fill="#DD2033"
          d="M49.32 74.665 26.311 51.658 74.487 3.483 97.495 26.49z"
        />
        <path
          fill="#FBD381"
          d="m13.797 64.174-16.97-16.97 62.575-62.577 16.971 16.97z"
        />
        <path
          fill="#009B77"
          d="M-2.316 46.345-24.4 24.261l55.286-55.287L52.971-8.94z"
        />
      </g>
    </CountrySymbol>
  );
});

export default CG_Sharp;
