// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type CV_SharpProps = CountrySymbolProps;

const CV_Sharp = forwardRef<SVGSVGElement, CV_SharpProps>(function CV_Sharp(
  props: CV_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="CV_Sharp"
      aria-label="Cabo Verde"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-CV-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-CV-a)`}>
        <path fill="#004692" d="M0 0h29v20H0z" />
        <path fill="#F5F7F8" d="M0 16V8.8h29V16z" />
        <path fill="#DD2033" d="M0 13.6v-2.4h29v2.4z" />
        <path
          fill="#F1B434"
          d="m6.197 10.846-.406.913-.958.121.706.686-.185.988.843-.564.843.564-.185-.988.706-.686-.957-.121-.407-.913ZM7.22 8.332l.406-.913.407.913.957.122-.706.686.185.988-.843-.564-.843.564.185-.988-.706-.686.958-.122Zm3.45-1.419L11.076 6l.407.913.957.122-.706.686.185.988-.843-.565-.842.565.185-.988-.706-.686.957-.122Zm-3.45 8.272.406-.913.407.913.957.122-.706.685.185.989-.843-.565-.843.565.185-.989-.706-.685.958-.122Zm3.856.506-.406.913-.957.122.706.686-.185.988.842-.564.843.564-.185-.988.706-.686-.957-.122-.407-.913Zm3.044-.506.407-.913.406.913.957.122-.706.685.185.989-.842-.565-.843.565.185-.989-.706-.685.957-.122Zm1.836-4.339-.407.913-.957.121.706.686-.185.988.843-.564.843.564-.186-.988.707-.686-.958-.121-.406-.913ZM14.12 8.332l.407-.913.406.913.957.122-.706.686.185.988-.842-.564-.843.564.185-.988-.706-.686.957-.122Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default CV_Sharp;
