// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type DEProps = CountrySymbolProps;

const DE = forwardRef<SVGSVGElement, DEProps>(function DE(props: DEProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="DE"
      aria-label="Germany"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-DE-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-DE-a)`}>
        <path fill="#F1B434" d="M0 20v-6.667h20V20z" />
        <path fill="#DD2033" d="M0 13.333V6.666h20v6.667z" />
        <path fill="#31373D" stroke="#31373D" d="M.5 6.167V.5h19v5.667z" />
      </g>
    </CountrySymbol>
  );
});

export default DE;
