// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type EC_SharpProps = CountrySymbolProps;

const EC_Sharp = forwardRef<SVGSVGElement, EC_SharpProps>(function EC_Sharp(
  props: EC_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="EC_Sharp"
      aria-label="Ecuador"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-EC-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-EC-a)`}>
        <path fill="#dd2033" d="M0 20v-2.8h29V20z" />
        <path fill="#f1b434" d="M0 10V0h29v10z" />
        <path fill="#004692" d="M0 17.2V10h29v7.2z" />
        <path
          fill="#936846"
          fillRule="evenodd"
          d="M15.792 5.374c-.459.27-.712.681-.8.945a.605.605 0 0 1-1.127.053c-.316-.717-.904-1.035-1.591-1.139-.71-.106-1.47.032-1.941.196l-.399-1.133c.606-.21 1.568-.392 2.52-.25.687.104 1.393.384 1.935.956.207-.241.467-.471.787-.66.76-.447 1.795-.624 3.106-.24l-.342 1.15c-1.028-.3-1.71-.135-2.148.122"
          clipRule="evenodd"
        />
        <path
          fill="#fbd381"
          d="M12.164 10 6.928 8.8v4.535c0 .98.88 1.73 1.856 1.581l3.38-.516zm4.833 0 5.236-1.2v4.535c0 .98-.88 1.73-1.856 1.581l-3.38-.516z"
        />
        <path
          fill="#004692"
          d="M13.372 9.2 8.136 8v4.535c0 .98.88 1.73 1.856 1.581l3.38-.516zm2.417 0L21.025 8v4.535c0 .98-.88 1.73-1.856 1.581l-3.38-.516z"
        />
        <path
          fill="#dd2033"
          d="m9.345 7.2 5.236 1.2 5.236-1.2v4.535c0 .98-.88 1.73-1.856 1.581l-3.38-.516-3.38.516c-.976.15-1.856-.6-1.856-1.581z"
        />
        <path
          fill="#0091da"
          d="M17.234 14.487C16.62 15.36 15.694 16 14.581 16c-1.114 0-2.04-.641-2.654-1.513-.616-.874-.971-2.038-.971-3.287s.355-2.413.971-3.287c.614-.872 1.54-1.513 2.654-1.513s2.039.641 2.653 1.513c.616.874.972 2.038.972 3.287s-.356 2.413-.972 3.287"
        />
        <path
          fill="#c1c3c3"
          fillRule="evenodd"
          d="M17.234 14.487C16.62 15.36 15.694 16 14.581 16c-1.114 0-2.04-.641-2.654-1.513-.616-.874-.971-2.038-.971-3.287s.355-2.413.971-3.287c.614-.872 1.54-1.513 2.654-1.513s2.039.641 2.653 1.513c.616.874.972 2.038.972 3.287s-.356 2.413-.972 3.287m-2.653.713c1.557 0 2.82-1.79 2.82-4s-1.263-4-2.82-4-2.82 1.79-2.82 4 1.263 4 2.82 4"
          clipRule="evenodd"
        />
        <mask
          id={`${uid}-EC-b`}
          x="11"
          y="7"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <ellipse cx="14.581" cy="11.2" fill="#d9d9d9" rx="2.819" ry="4" />
        </mask>
        <g mask={`url(#${uid}-EC-b)`}>
          <path
            fill="#008259"
            d="m13.533 11.6-1.61 2.4-.403-2.4zm0 0 3.545 2.4.886-2.4z"
          />
          <path
            fill="#f5f7f8"
            d="m14.339 10 2.014 1.6h-5.236l.604-2 1.812.8z"
          />
        </g>
      </g>
    </CountrySymbol>
  );
});

export default EC_Sharp;
