// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";
import { useId } from "@salt-ds/core";

import { CountrySymbol, CountrySymbolProps } from "../country-symbol";

export type FKProps = CountrySymbolProps;

const FK = forwardRef<SVGSVGElement, FKProps>(function FK(props: FKProps, ref) {
  const uid = useId(props.id);

  const viewBoxValue = props.variant === "sharp" ? "0 0 72 50" : "0 0 72 72";

  return (
    <CountrySymbol
      data-testid="FK"
      aria-label="Falkland Islands (the) [Malvinas]"
      viewBox={viewBoxValue}
      ref={ref}
      {...props}
    >
      {props.variant !== "sharp" && (
        <>
          <mask
            id={`${uid}-FK-a`}
            x="0"
            y="0"
            maskUnits="userSpaceOnUse"
            style={{ maskType: "alpha" }}
          >
            <circle cx="36" cy="36" r="36" fill="#D9D9D9" />
          </mask>
          <g mask={`url(#${uid}-FK-a)`}>
            <path fill="#004692" d="M0 0h72v72H0z" />
            <path fill="#FBD381" d="M61.6 53h-21v5h3v3h15v-3h3v-5Z" />
            <path
              fill="#0091DA"
              d="M40.6 35h21v8.743a14.857 14.857 0 0 1-9.36 13.803L51.1 58l-1.14-.454a14.857 14.857 0 0 1-9.36-13.803V35Z"
            />
            <mask
              id={`${uid}-FK-b`}
              x="40"
              y="35"
              maskUnits="userSpaceOnUse"
              style={{ maskType: "alpha" }}
            >
              <path
                fill="#0091DA"
                d="M40.6 35h21v8.743a14.857 14.857 0 0 1-9.36 13.803L51.1 58l-1.14-.454a14.857 14.857 0 0 1-9.36-13.803V35Z"
              />
            </mask>
            <g fill="#F5F7F8" mask={`url(#${uid}-FK-b)`}>
              <path d="M51.1 48c-2.625 0-2.625 2.182-5.25 2.182S43.225 48 40.6 48v3.818c2.625 0 2.625 2.182 5.25 2.182s2.625-2.182 5.25-2.182c2.624 0 2.624 2.182 5.25 2.182 2.625 0 2.625-2.182 5.25-2.182V48c-2.625 0-2.625 2.182-5.25 2.182-2.626 0-2.626-2.182-5.25-2.182Zm0-7c-2.625 0-2.625 2.182-5.25 2.182S43.225 41 40.6 41v3.818c2.625 0 2.625 2.182 5.25 2.182s2.625-2.182 5.25-2.182c2.624 0 2.624 2.182 5.25 2.182 2.625 0 2.625-2.182 5.25-2.182V41c-2.625 0-2.625 2.182-5.25 2.182-2.626 0-2.626-2.182-5.25-2.182Z" />
            </g>
            <mask
              id={`${uid}-FK-c`}
              x="0"
              y="0"
              maskUnits="userSpaceOnUse"
              style={{ maskType: "alpha" }}
            >
              <path fill="#002F6C" d="M0 36C0 16.118 16.118 0 36 0v36H0Z" />
            </mask>
            <g mask={`url(#${uid}-FK-c)`}>
              <path fill="#004692" d="M0 0h36v36H0z" />
              <path
                fill="#F5F7F8"
                d="m12.522 3.134-2.121 2.121 29.526 29.526 2.121-2.121L12.522 3.134ZM6.865 8.79 3.33 12.327l29.526 29.526 3.535-3.535L6.866 8.79Z"
              />
              <path
                fill="#DD2033"
                d="m6.865 8.79 3.536-3.535 29.526 29.526-3.535 3.536L6.864 8.79Z"
              />
              <path fill="#F5F7F8" d="M36 12v5H17v19h-5V12h24Z" />
              <path fill="#F5F7F8" d="M36-2v5H5v33H0V-2h36Z" />
              <path
                fill="#DD2033"
                fillRule="evenodd"
                d="M3 36h9V12h24V3H3v33Z"
                clipRule="evenodd"
              />
            </g>
          </g>
        </>
      )}
      {props.variant === "sharp" && (
        <>
          <mask
            id={`${uid}-FK-a`}
            x="0"
            y="0"
            maskUnits="userSpaceOnUse"
            style={{ maskType: "alpha" }}
          >
            <path fill="#D9D9D9" d="M0 0h72v50H0z" />
          </mask>
          <g mask={`url(#${uid}-FK-a)`}>
            <path fill="#004692" d="M0 0h72v50H0z" />
            <mask
              id={`${uid}-FK-b`}
              x="0"
              y="0"
              maskUnits="userSpaceOnUse"
              style={{ maskType: "alpha" }}
            >
              <path fill="#002F6C" d="M0 30V0h36v30H0Z" />
            </mask>
            <g mask={`url(#${uid}-FK-b)`}>
              <path
                fill="#F5F7F8"
                d="m12.79 1.005-2.12 2.12 26.197 26.198 2.12-2.121L12.792 1.005ZM7.134 6.661l-3.536 3.536 26.197 26.197 3.536-3.535L7.134 6.66Z"
              />
              <path
                fill="#DD2033"
                d="m7.134 6.661 3.535-3.535 26.198 26.197-3.536 3.535L7.134 6.662Z"
              />
              <path fill="#F5F7F8" d="M6 35h4.002V9H36V5H6v30Z" />
              <path fill="#DD2033" d="M0 35h6.002V5h30V0H0v35Z" />
            </g>
            <path fill="#FBD381" d="M64.6 37h-21v5h3v3h15v-3h3v-5Z" />
            <path
              fill="#0091DA"
              d="M43.6 19h21v8.743a14.857 14.857 0 0 1-9.36 13.803L54.1 42l-1.14-.454a14.857 14.857 0 0 1-9.36-13.803V19Z"
            />
            <mask
              id={`${uid}-FK-c`}
              x="43"
              y="19"
              maskUnits="userSpaceOnUse"
              style={{ maskType: "alpha" }}
            >
              <path
                fill="#0091DA"
                d="M43.6 19h21v8.743a14.857 14.857 0 0 1-9.36 13.803L54.1 42l-1.14-.454a14.857 14.857 0 0 1-9.36-13.803V19Z"
              />
            </mask>
            <g fill="#F5F7F8" mask={`url(#${uid}-FK-c)`}>
              <path d="M54.1 32c-2.625 0-2.625 2.182-5.25 2.182S46.225 32 43.6 32v3.818c2.625 0 2.625 2.182 5.25 2.182s2.625-2.182 5.25-2.182c2.624 0 2.624 2.182 5.25 2.182 2.625 0 2.625-2.182 5.25-2.182V32c-2.625 0-2.625 2.182-5.25 2.182-2.626 0-2.626-2.182-5.25-2.182Zm0-7c-2.625 0-2.625 2.182-5.25 2.182S46.225 25 43.6 25v3.818c2.625 0 2.625 2.182 5.25 2.182s2.625-2.182 5.25-2.182c2.624 0 2.624 2.182 5.25 2.182 2.625 0 2.625-2.182 5.25-2.182V25c-2.625 0-2.625 2.182-5.25 2.182-2.626 0-2.626-2.182-5.25-2.182Z" />
            </g>
          </g>
        </>
      )}
    </CountrySymbol>
  );
});

export default FK;
