// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type FKProps = CountrySymbolProps;

const FK = forwardRef<SVGSVGElement, FKProps>(function FK(props: FKProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="FK"
      aria-label="Falkland Islands (the) [Malvinas]"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-FK-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#d9d9d9" />
      </mask>
      <g mask={`url(#${uid}-FK-a)`}>
        <path fill="#004692" d="M0 0h20v20H0z" />
        <path
          fill="#fbd381"
          d="M17.111 14.722h-5.833v1.39h.833v.833h4.167v-.834h.833z"
        />
        <path
          fill="#0091da"
          d="M11.278 9.722h5.833v2.088a4.63 4.63 0 0 1-2.917 4.301 4.63 4.63 0 0 1-2.916-4.301z"
        />
        <mask
          id={`${uid}-FK-b`}
          x="11"
          y="9"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path
            fill="#0091da"
            d="M11.278 9.722h5.833v2.088a4.63 4.63 0 0 1-2.917 4.301 4.63 4.63 0 0 1-2.916-4.301z"
          />
        </mask>
        <g fill="#f5f7f8" mask={`url(#${uid}-FK-b)`}>
          <path d="M14.194 13.333c-.729 0-.729.606-1.458.606-.73 0-.73-.606-1.458-.606v1.061c.729 0 .729.606 1.458.606.73 0 .73-.606 1.458-.606.73 0 .73.606 1.459.606s.729-.606 1.458-.606v-1.06c-.73 0-.73.605-1.458.605-.73 0-.73-.606-1.459-.606m0-1.944c-.729 0-.729.606-1.458.606-.73 0-.73-.606-1.458-.606v1.06c.729 0 .729.607 1.458.607.73 0 .73-.606 1.458-.606.73 0 .73.606 1.459.606s.729-.606 1.458-.606v-1.061c-.73 0-.73.606-1.458.606-.73 0-.73-.606-1.459-.606" />
        </g>
        <mask
          id={`${uid}-FK-c`}
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path fill="#002f6c" d="M0 10C0 4.477 4.477 0 10 0v10z" />
        </mask>
        <g mask={`url(#${uid}-FK-c)`}>
          <path fill="#004692" d="M0 0h10v10H0z" />
          <path
            fill="#f5f7f8"
            d="m3.478.87-.589.59 8.202 8.201.59-.589zM1.907 2.442l-.982.982 8.202 8.202.982-.982z"
          />
          <path
            fill="#dd2033"
            d="m1.907 2.442.982-.982 8.202 8.201-.982.982z"
          />
          <path fill="#f5f7f8" d="M10 3.333v1.39H4.722V10H3.333V3.333z" />
          <path fill="#f5f7f8" d="M10-.556v1.39H1.389V10H0V-.556z" />
          <path
            fill="#dd2033"
            fillRule="evenodd"
            d="M.833 10h2.5V3.333H10v-2.5H.833z"
            clipRule="evenodd"
          />
        </g>
      </g>
    </CountrySymbol>
  );
});

export default FK;
