// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";
import { useId } from "@salt-ds/core";
import { clsx } from "clsx";

import { CountrySymbol, CountrySymbolProps } from "../country-symbol";

export type GA_SharpProps = CountrySymbolProps;

const GA_Sharp = forwardRef<SVGSVGElement, GA_SharpProps>(function GA_Sharp(
  props: GA_SharpProps,
  ref
) {
  const uid = useId(props.id);

  const { className, ...rest } = props;

  return (
    <CountrySymbol
      data-testid="GA_Sharp"
      aria-label="Gabon"
      viewBox="0 0 72 50"
      ref={ref}
      className={clsx(className, { saltSharpCountrySymbol: true })}
      {...rest}
    >
      <mask
        id={`${uid}-GA-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h72v50H0z" />
      </mask>
      <g mask={`url(#${uid}-GA-a)`}>
        <path fill="#005EB8" d="M0 50V34h72v16z" />
        <path fill="#FBD381" d="M0 34V16h72v18z" />
        <path fill="#009B77" d="M0 16V0h72v16z" />
      </g>
    </CountrySymbol>
  );
});

export default GA_Sharp;
