// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type GB_ENG_SharpProps = CountrySymbolProps;

const GB_ENG_Sharp = forwardRef<SVGSVGElement, GB_ENG_SharpProps>(
  function GB_ENG_Sharp(props: GB_ENG_SharpProps, ref) {
    const uid = useId(props.id);

    return (
      <CountrySymbol
        data-testid="GB_ENG_Sharp"
        aria-label="England"
        viewBox="0 0 72 50"
        ref={ref}
        sharp
        {...props}
      >
        <mask
          id={`${uid}-GB-ENG-a`}
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path fill="#D9D9D9" d="M0 0h72v50H0z" />
        </mask>
        <g mask={`url(#${uid}-GB-ENG-a)`}>
          <path fill="#F5F7F8" d="M0 0h72v50H0z" />
          <path
            fill="#DD2033"
            d="M30.4 50h12V31H72V19H42.4V0h-12v19H0v12h30.4v19Z"
          />
        </g>
      </CountrySymbol>
    );
  },
);

export default GB_ENG_Sharp;
