// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type GB_NIR_SharpProps = CountrySymbolProps;

const GB_NIR_Sharp = forwardRef<SVGSVGElement, GB_NIR_SharpProps>(
  function GB_NIR_Sharp(props: GB_NIR_SharpProps, ref) {
    const uid = useId(props.id);

    return (
      <CountrySymbol
        data-testid="GB_NIR_Sharp"
        aria-label="Northern Ireland"
        viewBox="0 0 29 20"
        ref={ref}
        sharp
        {...props}
      >
        <mask
          id={`${uid}-GB-NIR-a`}
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path fill="#D9D9D9" d="M0 0h29v20H0z" />
        </mask>
        <g mask={`url(#${uid}-GB-NIR-a)`}>
          <path fill="#F5F7F8" d="M0 0h29v20H0z" />
          <path
            fill="#DD2033"
            d="M12.244 20h4.834v-7.6H29V7.6H17.078V0h-4.834v7.6H0v4.8h12.244V20Z"
          />
          <path
            fill="#F5F7F8"
            fillRule="evenodd"
            d="M13.44 7.897 14.702 5.2l1.261 2.697 2.969.359-2.19 2.025.574 2.919-2.614-1.667-2.613 1.667.574-2.919-2.19-2.025 2.969-.36Zm1.966.303H14.35v.667h-.705V11.2h1.762v-.667h.705v-1h-.705V8.2Z"
            clipRule="evenodd"
          />
          <path
            fill="#F1B434"
            fillRule="evenodd"
            d="M14.27.4h.863V1h.863v.9h-.863v.84c.254-.152.549-.24.863-.24.953 0 1.726.806 1.726 1.8a1.83 1.83 0 0 1-.575 1.342V6.4h-4.891v-.758A1.83 1.83 0 0 1 11.68 4.3c0-.994.772-1.8 1.726-1.8.314 0 .609.088.863.24V1.9h-.863V1h.863V.4Zm.431 2.71-.008-.01h.016l-.008.01Zm-.008 2.39.008-.01.008.01h-.016Z"
            clipRule="evenodd"
          />
        </g>
      </CountrySymbol>
    );
  },
);

export default GB_NIR_Sharp;
