// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type GM_SharpProps = CountrySymbolProps;

const GM_Sharp = forwardRef<SVGSVGElement, GM_SharpProps>(function GM_Sharp(
  props: GM_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="GM_Sharp"
      aria-label="Gambia (the)"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-GM-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-GM-a)`}>
        <path fill="#f5f7f8" d="M0 0h29v20H0z" />
        <path fill="#005eb8" d="M0 13.6V6.4h29v7.2z" />
        <path fill="#dd2033" d="M0 4.4V0h29v4.4z" />
        <path fill="#009b77" d="M0 20v-4.4h29V20z" />
      </g>
    </CountrySymbol>
  );
});

export default GM_Sharp;
