// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type GR_SharpProps = CountrySymbolProps;

const GR_Sharp = forwardRef<SVGSVGElement, GR_SharpProps>(function GR_Sharp(
  props: GR_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="GR_Sharp"
      aria-label="Greece"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-GR-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-GR-a)`}>
        <path fill="#F5F7F8" d="M0 16.8V14h29v2.8H0Z" />
        <path fill="#005EB8" d="M0 14v-2.8h29V14H0Z" />
        <path fill="#F5F7F8" d="M0 11.2V8.4h29v2.8H0Z" />
        <path fill="#005EB8" d="M0 8.4V5.6h29v2.8H0Z" />
        <path fill="#F5F7F8" d="M0 5.6V2.8h29v2.8H0Z" />
        <path fill="#005EB8" d="M0 2.8V0h29v2.8H0ZM0 20v-3.2h29V20H0Z" />
        <path fill="#005EB8" d="M0 0h14.5v14H0z" />
        <path fill="#F5F7F8" d="M0 8.4V5.6h14.5v2.8H0Z" />
        <path fill="#F5F7F8" d="M5.639 0H8.86v14H5.64V0Z" />
      </g>
    </CountrySymbol>
  );
});

export default GR_Sharp;
