// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type GSProps = CountrySymbolProps;

const GS = forwardRef<SVGSVGElement, GSProps>(function GS(props: GSProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="GS"
      aria-label="South Georgia and the South Sandwich Islands"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-GS-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle
          cx="10"
          cy="10"
          r="10"
          fill="#d9d9d9"
          transform="rotate(-90 10 10)"
        />
      </mask>
      <g mask={`url(#${uid}-GS-a)`}>
        <path fill="#004692" d="M0 0h20v20H0z" />
        <path fill="#c1c3c3" d="M12.889 7.444h2.5v2.222h-2.5z" />
        <path fill="#936846" d="M13.167 5.5h.694v.833h.972v1.111h-1.666z" />
        <path
          fill="#fbd381"
          d="M17.056 14.667h-5.834v1.388h.834v.834h4.166v-.834h.834z"
        />
        <path
          fill="#f5f7f8"
          d="M11.222 9.667h5.834v2.428c0 1.69-1.03 3.21-2.6 3.834l-.317.126-.317-.126a4.13 4.13 0 0 1-2.6-3.834z"
        />
        <mask
          id={`${uid}-GS-b`}
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path fill="#002f6c" d="M0 10C0 4.477 4.477 0 10 0v10z" />
        </mask>
        <g mask={`url(#${uid}-GS-b)`}>
          <path fill="#004692" d="M0 0h10v10H0z" />
          <path
            fill="#f5f7f8"
            d="m3.478.87-.589.59 8.202 8.201.59-.589zM1.907 2.442l-.982.982 8.202 8.202.982-.982z"
          />
          <path
            fill="#dd2033"
            d="m1.907 2.442.982-.982 8.202 8.201-.982.982z"
          />
          <path fill="#f5f7f8" d="M10 3.333v1.39H4.722V10H3.333V3.333z" />
          <path fill="#f5f7f8" d="M10-.556v1.39H1.389V10H0V-.556z" />
          <path
            fill="#dd2033"
            fillRule="evenodd"
            d="M.833 10h2.5V3.333H10v-2.5H.833z"
            clipRule="evenodd"
          />
        </g>
      </g>
      <mask
        id={`${uid}-GS-c`}
        x="11"
        y="9"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path
          fill="#f5f7f8"
          d="M11.222 9.667h5.834v2.428c0 1.69-1.03 3.21-2.6 3.834l-.317.126-.317-.126a4.13 4.13 0 0 1-2.6-3.834z"
        />
      </mask>
      <g fill="#005eb8" mask={`url(#${uid}-GS-c)`}>
        <path d="m14.07 9.528 1.319 1.32-1.32 1.319-1.319-1.32zm-2.64 2.639 1.32 1.32-1.32 1.319-1.319-1.32zm6.598-1.32-1.32-1.32-1.319 1.32 1.32 1.32z" />
        <path d="m14.07 12.167 1.319 1.32-1.32 1.319 1.32 1.32-1.32 1.319-1.319-1.32 1.32-1.32-1.32-1.319zm-1.32-1.32-1.32-1.32-1.319 1.32 1.32 1.32zm3.959 1.32 1.319 1.32-1.32 1.319-1.319-1.32z" />
      </g>
    </CountrySymbol>
  );
});

export default GS;
