// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type HN_SharpProps = CountrySymbolProps;

const HN_Sharp = forwardRef<SVGSVGElement, HN_SharpProps>(function HN_Sharp(
  props: HN_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="HN_Sharp"
      aria-label="Honduras"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-HN-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-HN-a)`}>
        <path fill="#0091DA" d="M0 0h29v20H0z" />
        <path fill="#F5F7F8" d="M0 16.4V3.6h29v12.8z" />
        <path
          fill="#0091DA"
          d="m7.572 5.6-.72 1.618-1.696.215 1.25 1.216L6.08 10.4l1.493-1 1.494 1-.328-1.751 1.25-1.216-1.695-.215-.72-1.618Zm6.848 4-.72 1.618-1.697.215 1.251 1.216-.328 1.751 1.493-1 1.494 1-.328-1.751 1.251-1.216-1.696-.215-.72-1.618Zm6.126-2.382.72-1.618.721 1.618 1.696.215-1.25 1.216.327 1.751-1.493-1-1.494 1 .328-1.751-1.251-1.216 1.696-.215Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default HN_Sharp;
