// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type JMProps = CountrySymbolProps;

const JM = forwardRef<SVGSVGElement, JMProps>(function JM(props: JMProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="JM"
      aria-label="Jamaica"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-JM-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-JM-a)`}>
        <path fill="#31373D" d="M0 0h20v20H0z" />
        <path fill="#009B77" d="m0 20 9.722-10L0 0h20L9.722 10 20 20H0Z" />
        <path
          fill="#F1B434"
          d="m16.089 18.053 1.964-1.964L11.964 10l6.09-6.089-1.965-1.964L10 8.036l-6.089-6.09-1.964 1.965L8.036 10l-6.09 6.089 1.965 1.964L10 11.964l6.089 6.09Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default JM;
