// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";
import { useId } from "@salt-ds/core";

import { CountrySymbol, CountrySymbolProps } from "../country-symbol";

export type JM_SharpProps = CountrySymbolProps;

const JM_Sharp = forwardRef<SVGSVGElement, JM_SharpProps>(function JM_Sharp(
  props: JM_SharpProps,
  ref
) {
  const uid = useId(props.id);

  const { style: styleProp, ...rest } = props;

  const style = {
    ...styleProp,
    borderRadius: "0",
  };

  return (
    <CountrySymbol
      data-testid="JM_Sharp"
      style={style}
      aria-label="Jamaica"
      viewBox="0 0 72 50"
      ref={ref}
      {...rest}
    >
      <mask
        id={`${uid}-JM-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h72v50H0z" />
      </mask>
      <g mask={`url(#${uid}-JM-a)`}>
        <path fill="#31373D" d="M0 0h72v50H0z" />
        <path fill="#009B77" d="m0 61 35-36L0-11h72L35 25l37 36H0Z" />
        <path
          fill="#F1B434"
          d="M65.471 56 72 50.378 42.529 25 72-.378 65.472-6 36 19.378 6.529-6 0-.378 29.471 25 .002 50.378 6.528 56 36 30.622 65.471 56Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default JM_Sharp;
