// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";
import { useId } from "@salt-ds/core";

import { CountrySymbol, CountrySymbolProps } from "../country-symbol";

export type JO_SharpProps = CountrySymbolProps;

const JO_Sharp = forwardRef<SVGSVGElement, JO_SharpProps>(function JO_Sharp(
  props: JO_SharpProps,
  ref
) {
  const uid = useId(props.id);

  const { style: styleProp, ...rest } = props;

  const style = {
    ...styleProp,
    borderRadius: "0",
  };

  return (
    <CountrySymbol
      data-testid="JO_Sharp"
      style={style}
      aria-label="Jordan"
      viewBox="0 0 72 50"
      ref={ref}
      {...rest}
    >
      <mask
        id={`${uid}-JO-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h72v50H0z" />
      </mask>
      <g mask={`url(#${uid}-JO-a)`}>
        <path fill="#008259" d="M0 50V34h72v16z" />
        <path fill="#F5F7F8" d="M0 34V16h72v18z" />
        <path fill="#31373D" d="M0 16V0h72v16z" />
        <path fill="#DD2033" d="M40 25-8-11v72l48-36Z" />
        <path
          fill="#F5F7F8"
          d="m15 14 2.707 5.807 6.114-1.45-2.738 5.792 4.917 4-6.122 1.415.017 6.436L15 31.973 10.104 36l.018-6.436L4 28.148l4.917-3.999-2.738-5.791 6.114 1.449L15 14Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default JO_Sharp;
