// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type JPProps = CountrySymbolProps;

const JP = forwardRef<SVGSVGElement, JPProps>(function JP(props: JPProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="JP"
      aria-label="Japan"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-JP-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-JP-a)`}>
        <path fill="#F5F7F8" d="M0 0h20v20H0z" />
        <circle cx="10" cy="10" r="4.444" fill="#DD2033" />
      </g>
    </CountrySymbol>
  );
});

export default JP;
