// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type KGProps = CountrySymbolProps;

const KG = forwardRef<SVGSVGElement, KGProps>(function KG(props: KGProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="KG"
      aria-label="Kyrgyzstan"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-KG-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle
          cx="10"
          cy="10"
          r="10"
          fill="#d9d9d9"
          transform="rotate(-90 10 10)"
        />
      </mask>
      <g mask={`url(#${uid}-KG-a)`}>
        <path fill="#dd2033" d="M20 20H0V0h20z" />
        <path
          fill="#f1b434"
          d="M10 6.667a3.333 3.333 0 1 0 0 6.666 3.333 3.333 0 0 0 0-6.666"
        />
        <path
          fill="#f1b434"
          fillRule="evenodd"
          d="M17.778 10 14.6 11.572l1.692 3.235-3.451-.694-.437 3.665L10 15.082l-2.404 2.696-.437-3.665-3.451.694L5.4 11.57 2.222 10 5.4 8.428 3.708 5.193l3.45.694.438-3.665L10 4.918l2.404-2.696.437 3.665 3.451-.694L14.6 8.43zM5.556 10a4.444 4.444 0 1 1 8.888 0 4.444 4.444 0 0 1-8.888 0"
          clipRule="evenodd"
        />
        <path
          fill="#dd2033"
          d="M7.077 8.396c.74.113 1.43.376 2.039.757a6.5 6.5 0 0 0-1.689 2.967c.269.325.597.598.97.803A5.4 5.4 0 0 1 10 9.84a5.4 5.4 0 0 1 1.604 3.082c.372-.205.7-.478.969-.803a6.5 6.5 0 0 0-1.689-2.967c.61-.38 1.3-.644 2.039-.757a3.4 3.4 0 0 0-.803-.969 6.5 6.5 0 0 0-2.12.98 6.5 6.5 0 0 0-2.12-.98 3.4 3.4 0 0 0-.803.969"
        />
      </g>
    </CountrySymbol>
  );
});

export default KG;
