// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type KM_SharpProps = CountrySymbolProps;

const KM_Sharp = forwardRef<SVGSVGElement, KM_SharpProps>(function KM_Sharp(
  props: KM_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="KM_Sharp"
      aria-label="Comoros (the)"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-KM-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-KM-a)`}>
        <path fill="#004692" d="M0 20v-5.2h29V20z" />
        <path fill="#DD2033" d="M0 14.8V10h29v4.8z" />
        <path fill="#F5F7F8" d="M0 10V5.2h29V10z" />
        <path fill="#FBD381" d="M0 5.2V0h29v5.2z" />
        <path fill="#009B77" d="M19.333 10 0-4.4v28.8L19.333 10Z" />
        <path
          fill="#F5F7F8"
          d="M4.189 10c0-2.652 1.857-4.874 4.35-5.453A5.693 5.693 0 0 0 7.25 4.4c-3.114 0-5.639 2.507-5.639 5.6 0 3.093 2.525 5.6 5.639 5.6.443 0 .875-.05 1.289-.147-2.493-.579-4.35-2.8-4.35-5.453Zm6.041-2c.668 0 1.209-.537 1.209-1.2 0-.663-.541-1.2-1.209-1.2-.667 0-1.208.537-1.208 1.2 0 .663.541 1.2 1.208 1.2Zm0 3.2c.668 0 1.209-.537 1.209-1.2 0-.663-.541-1.2-1.209-1.2-.667 0-1.208.537-1.208 1.2 0 .663.541 1.2 1.208 1.2Zm1.209 2c0 .663-.541 1.2-1.209 1.2a1.204 1.204 0 0 1-1.208-1.2c0-.663.541-1.2 1.208-1.2.668 0 1.209.537 1.209 1.2Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default KM_Sharp;
