// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type KWProps = CountrySymbolProps;

const KW = forwardRef<SVGSVGElement, KWProps>(function KW(props: KWProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="KW"
      aria-label="Kuwait"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-KW-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#d9d9d9" />
      </mask>
      <g mask={`url(#${uid}-KW-a)`}>
        <path fill="#dd2033" d="M0 20v-7h20v7z" />
        <path fill="#f5f7f8" d="M0 13V7h20v6z" />
        <path fill="#009b77" d="M0 7V0h20v7z" />
        <path fill="#31373d" d="M0 0v20l9-7V7z" />
      </g>
    </CountrySymbol>
  );
});

export default KW;
