// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type KY_SharpProps = CountrySymbolProps;

const KY_Sharp = forwardRef<SVGSVGElement, KY_SharpProps>(function KY_Sharp(
  props: KY_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="KY_Sharp"
      aria-label="Cayman Islands (the)"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-KY-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-KY-a)`}>
        <path fill="#004692" d="M0 0h29v20H0z" />
        <mask
          id={`${uid}-KY-b`}
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path fill="#002F6C" d="M0 12V0h14.5v12H0Z" />
        </mask>
        <g mask={`url(#${uid}-KY-b)`}>
          <path fill="#004692" d="M0 0h14.5v14.4H0z" />
          <path
            fill="#F5F7F8"
            d="m5.152.402-.855.848L14.85 11.73l.854-.85L5.152.403ZM2.873 2.665 1.45 4.079l10.552 10.479 1.424-1.415L2.873 2.665Z"
          />
          <path
            fill="#DD2033"
            d="M2.873 2.665 4.297 1.25 14.85 11.73l-1.424 1.413L2.873 2.665Z"
          />
          <path fill="#F5F7F8" d="M2.417 14h1.611V3.6H14.5V2H2.417v12Z" />
          <path fill="#DD2033" d="M0 14h2.417V2h12.084V0H0v14Z" />
        </g>
        <path
          fill="#FBD381"
          d="M26.18 14h-8.458v2h1.209v1.2h6.041V16h1.209v-2Z"
        />
        <ellipse cx="21.951" cy="3.8" fill="#FBD381" rx="1.007" ry="1" />
        <ellipse cx="21.951" cy="7" fill="#008259" rx="3.021" ry="3" />
        <path
          fill="#DD2033"
          d="M17.722 6.8h8.459v2.98A6.69 6.69 0 0 1 21.95 16a6.69 6.69 0 0 1-4.229-6.22V6.8Z"
        />
        <mask
          id={`${uid}-KY-c`}
          x="17"
          y="6"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path
            fill="#DD2033"
            d="M17.722 6.8h8.459v2.98A6.69 6.69 0 0 1 21.95 16a6.69 6.69 0 0 1-4.229-6.22V6.8Z"
          />
        </mask>
        <g mask={`url(#${uid}-KY-c)`}>
          <path fill="#005EB8" d="M17.722 10.8h8.458V16h-8.458z" />
          <path
            fill="#F5F7F8"
            d="M21.951 12.4c-1.057 0-1.057.873-2.114.873-1.058 0-1.058-.873-2.115-.873v1.527c1.057 0 1.057.873 2.115.873 1.057 0 1.057-.873 2.114-.873 1.058 0 1.058.873 2.115.873 1.057 0 1.057-.873 2.115-.873V12.4c-1.058 0-1.058.873-2.115.873-1.057 0-1.057-.873-2.115-.873Zm0-2.8c-1.057 0-1.057.873-2.114.873-1.058 0-1.058-.873-2.115-.873v1.527c1.057 0 1.057.873 2.115.873 1.057 0 1.057-.873 2.114-.873 1.058 0 1.058.873 2.115.873 1.057 0 1.057-.873 2.115-.873V9.6c-1.058 0-1.058.873-2.115.873-1.057 0-1.057-.873-2.115-.873Z"
          />
          <path fill="#F1B434" d="M18.931 7.6h6.042v1.6h-6.042z" />
        </g>
      </g>
    </CountrySymbol>
  );
});

export default KY_Sharp;
