// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type KZProps = CountrySymbolProps;

const KZ = forwardRef<SVGSVGElement, KZProps>(function KZ(props: KZProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="KZ"
      aria-label="Kazakhstan"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-KZ-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#d9d9d9" />
      </mask>
      <g mask={`url(#${uid}-KZ-a)`}>
        <path fill="#3ccbda" d="M0 0h20v20H0z" />
        <path
          fill="#fbd381"
          d="M4.5 4.714 1.722 7.492V0H4.5zM1.722 9.063v1.874L4.5 13.714V6.286zm0 3.445L4.5 15.286V20H1.722zm13.889-4.73-1.362.673.725 1.387-1.479-.298-.187 1.571-1.03-1.155-1.03 1.155-.188-1.57-1.479.297.726-1.387-1.363-.673 1.363-.674-.726-1.386 1.48.297.187-1.57 1.03 1.155 1.03-1.156.187 1.571 1.48-.297-.726 1.386zm1.232 1.389a5.2 5.2 0 0 1-.743 1.522 4.95 4.95 0 0 1-2.606 1.896 4.7 4.7 0 0 1-1.077.192l-3.002 3.056 3.207-.568a4.6 4.6 0 0 0 1.98-.617 4.8 4.8 0 0 0 1.488-1.367 4.98 4.98 0 0 0 .753-4.114m-5.707 3.505a4.5 4.5 0 0 1-1.721-.801 4.76 4.76 0 0 1-1.73-2.596c-.429 1.846.219 3.86 1.793 5.055z"
        />
      </g>
    </CountrySymbol>
  );
});

export default KZ;
