// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type MCProps = CountrySymbolProps;

const MC = forwardRef<SVGSVGElement, MCProps>(function MC(props: MCProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="MC"
      aria-label="Monaco"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-MC-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-MC-a)`}>
        <path fill="#DD2033" d="M0 0v10h20V0z" />
        <path fill="#F5F7F8" d="M0 10v10h20V10z" />
      </g>
    </CountrySymbol>
  );
});

export default MC;
