// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";
import { useId } from "@salt-ds/core";

import { CountrySymbol, CountrySymbolProps } from "../country-symbol";

export type MCProps = CountrySymbolProps;

const MC = forwardRef<SVGSVGElement, MCProps>(function MC(props: MCProps, ref) {
  const uid = useId(props.id);

  const viewBoxValue = props.variant === "sharp" ? "0 0 72 50" : "0 0 72 72";

  return (
    <CountrySymbol
      data-testid="MC"
      aria-label="Monaco"
      viewBox={viewBoxValue}
      ref={ref}
      {...props}
    >
      {props.variant !== "sharp" && (
        <>
          <mask
            id={`${uid}-MC-a`}
            x="0"
            y="0"
            maskUnits="userSpaceOnUse"
            style={{ maskType: "alpha" }}
          >
            <circle cx="36" cy="36" r="36" fill="#D9D9D9" />
          </mask>
          <g mask={`url(#${uid}-MC-a)`}>
            <path fill="#DD2033" d="M0 0v36h72V0z" />
            <path fill="#F5F7F8" d="M0 36v36h72V36z" />
          </g>
        </>
      )}
      {props.variant === "sharp" && (
        <>
          <mask
            id={`${uid}-MC-a`}
            x="0"
            y="0"
            maskUnits="userSpaceOnUse"
            style={{ maskType: "alpha" }}
          >
            <path fill="#D9D9D9" d="M0 0h72v50H0z" />
          </mask>
          <g mask={`url(#${uid}-MC-a)`}>
            <path fill="#DD2033" d="M0 0v25h72V0z" />
            <path fill="#F5F7F8" d="M0 25v25h72V25z" />
          </g>
        </>
      )}
    </CountrySymbol>
  );
});

export default MC;
