// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";
import { useId } from "@salt-ds/core";

import { CountrySymbol, CountrySymbolProps } from "../country-symbol";

export type MDProps = CountrySymbolProps;

const MD = forwardRef<SVGSVGElement, MDProps>(function MD(props: MDProps, ref) {
  const uid = useId(props.id);

  const viewBoxValue = props.variant === "sharp" ? "0 0 72 50" : "0 0 72 72";

  return (
    <CountrySymbol
      data-testid="MD"
      aria-label="Moldova (the Republic of)"
      viewBox={viewBoxValue}
      ref={ref}
      {...props}
    >
      {props.variant !== "sharp" && (
        <>
          <mask
            id={`${uid}-MD-a`}
            x="0"
            y="0"
            maskUnits="userSpaceOnUse"
            style={{ maskType: "alpha" }}
          >
            <circle cx="36" cy="36" r="36" fill="#D9D9D9" />
          </mask>
          <g mask={`url(#${uid}-MD-a)`}>
            <path fill="#DD2033" d="M72 72H56V0h16z" />
            <path fill="#F1B434" d="M56 72H16V0h40z" />
            <path fill="#004692" d="M16 72H0V0h16z" />
            <path
              fill="#936846"
              d="M24.685 23.261c1.69-.115 4.172.134 6.102 1.094 1.739.866 2.951 2.218 2.951 4.753v9.637L22.4 49.987l4.165 4.13 7.355-7.293-3.106 7.698 5.89 5.84 5.89-5.84-3.113-7.718 7.342 7.28 4.165-4.13-11.339-11.242v-9.637h-.02c-.013-5.121-2.862-8.278-6.2-9.94-3.154-1.57-6.772-1.863-9.15-1.7l.406 5.826Z"
            />
            <path
              fill="#936846"
              d="M21.4 26v20l7-5V30a4 4 0 0 0-4-4h-3Zm30 20V26h-3a4 4 0 0 0-4 4v11l7 5Z"
            />
            <path
              fill="#DD2033"
              d="M26.2 27.823h20v7.942a14.857 14.857 0 0 1-9.34 13.794l-.66.264-.66-.264a14.857 14.857 0 0 1-9.34-13.794v-7.942Z"
            />
            <mask
              id={`${uid}-MD-b`}
              x="26"
              y="27"
              maskUnits="userSpaceOnUse"
              style={{ maskType: "alpha" }}
            >
              <path
                fill="#005EB8"
                d="M26.2 27.823h20v7.942a14.857 14.857 0 0 1-9.34 13.794l-.66.264-.66-.264a14.857 14.857 0 0 1-9.34-13.794v-7.942Z"
              />
            </mask>
            <g mask={`url(#${uid}-MD-b)`}>
              <path fill="#0091DA" d="M26.2 38h20v12h-20V38Z" />
              <path
                fill="#F1B434"
                d="M38.4 37.465a3.998 3.998 0 0 0 .828-6.293l-.808.808c.517.517.837 1.231.837 2.02 0 .8-.328 1.522-.857 2.04V35h-4v1.04a2.849 2.849 0 0 1-.857-2.04c0-.789.32-1.503.837-2.02l-.809-.808a3.998 3.998 0 0 0 .828 6.293V43a2 2 0 0 0 4.001 0v-5.535ZM36.4 30h.016-.032.016Z"
              />
            </g>
          </g>
        </>
      )}
      {props.variant === "sharp" && (
        <>
          <mask
            id={`${uid}-MD-a`}
            x="0"
            y="0"
            maskUnits="userSpaceOnUse"
            style={{ maskType: "alpha" }}
          >
            <path fill="#D9D9D9" d="M0 0h72v50H0z" />
          </mask>
          <g mask={`url(#${uid}-MD-a)`}>
            <path fill="#DD2033" d="M72 50H56V0h16z" />
            <path fill="#F1B434" d="M56 50H16V0h40z" />
            <path fill="#004692" d="M16 50H0V0h16z" />
            <path
              fill="#936846"
              d="M25.066 10.461c1.578-.108 3.894.124 5.695 1.018 1.623.806 2.755 2.066 2.755 4.425v8.971L22.934 35.341l3.887 3.845 6.864-6.789-2.898 7.166L36.284 45l5.498-5.437-2.906-7.185 6.852 6.777 3.887-3.844-10.582-10.466v-8.971h-.02c-.011-4.768-2.67-7.707-5.785-9.254-2.944-1.461-6.322-1.734-8.54-1.583l.378 5.424Z"
            />
            <path
              fill="#936846"
              d="M22 13.01v18.62l6.533-4.655v-10.24A3.729 3.729 0 0 0 24.8 13.01H22Zm28 18.62V13.01h-2.8a3.729 3.729 0 0 0-3.733 3.725v10.24L50 31.63Z"
            />
            <path
              fill="#DD2033"
              d="M26.48 14.708h18.666v6.708a14.828 14.828 0 0 1-9.333 13.773 14.828 14.828 0 0 1-9.333-13.773v-6.708Z"
            />
            <mask
              id={`${uid}-MD-b`}
              x="26"
              y="14"
              maskUnits="userSpaceOnUse"
              style={{ maskType: "alpha" }}
            >
              <path
                fill="#005EB8"
                d="M26.48 14.708h18.666v6.709a14.828 14.828 0 0 1-9.333 13.772 14.828 14.828 0 0 1-9.333-13.772v-6.709Z"
              />
            </mask>
            <g mask={`url(#${uid}-MD-b)`}>
              <path
                fill="#0091DA"
                d="M26.48 24.182h18.666v11.171H26.48v-11.17Z"
              />
              <path
                fill="#F1B434"
                d="M37.867 23.684a3.72 3.72 0 0 0 .773-5.859l-.755.753a2.651 2.651 0 0 1-.018 3.78v-.969h-3.734v.969a2.648 2.648 0 0 1-.8-1.9c0-.734.299-1.399.781-1.88l-.754-.753a3.72 3.72 0 0 0 .773 5.859v5.153c0 1.028.836 1.862 1.867 1.862 1.03 0 1.867-.834 1.867-1.862v-5.153ZM36 16.735h.015-.03H36Z"
              />
            </g>
          </g>
        </>
      )}
    </CountrySymbol>
  );
});

export default MD;
