// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type MKProps = CountrySymbolProps;

const MK = forwardRef<SVGSVGElement, MKProps>(function MK(props: MKProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="MK"
      aria-label="North Macedonia"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-MK-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#d9d9d9" />
      </mask>
      <g mask={`url(#${uid}-MK-a)`}>
        <path fill="#dd2033" d="M0 0h20v20H0z" />
        <path
          fill="#fbd381"
          d="M6.919 7.778a3.9 3.9 0 0 1 .97-.97L3.694.833l-2.75 2.75zm2.414-1.589a3.9 3.9 0 0 1 1.34-.037l1.271-7.263H8.057zm3.977 1.599a3.9 3.9 0 0 0-.908-.93l4.31-6.139 2.75 2.75zm.642 1.602a3.9 3.9 0 0 1-.023 1.355l7.252 1.269V8.125zm-1.574 3.77c.344-.247.646-.549.893-.893l6.235 4.378-2.75 2.75zm-1.728.692a3.9 3.9 0 0 1-1.293-.036L8.056 21.25h3.889zm-2.737-.643a3.9 3.9 0 0 1-.955-.932L.9 16.531l2.75 2.75zm-1.627-2.502-7.467 1.307V8.125l7.445 1.303a3.9 3.9 0 0 0 .022 1.28M13.167 10a3.056 3.056 0 1 1-6.112 0 3.056 3.056 0 0 1 6.112 0"
        />
      </g>
    </CountrySymbol>
  );
});

export default MK;
