// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type MPProps = CountrySymbolProps;

const MP = forwardRef<SVGSVGElement, MPProps>(function MP(props: MPProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="MP"
      aria-label="Northern Mariana Islands (the)"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-MP-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-MP-a)`}>
        <path fill="#0091DA" d="M0 0h20v20H0z" />
        <path
          fill="#F5F7F8"
          fillRule="evenodd"
          d="M8.916 16.992c.104.283.37.491.692.507l.039.001a.777.777 0 0 0 .698-.438.78.78 0 0 0 1.416-.216.78.78 0 0 0 .836.196l-.112.041c-.038.015-.038.015.113-.041a.778.778 0 0 0 .506-.694.778.778 0 0 0 1.215-.757.78.78 0 0 0 1.037-.986.778.778 0 0 0 .818-1.174.778.778 0 0 0 .566-1.315.777.777 0 0 0 .287-1.401.778.778 0 0 0 .473-.716v-.017a.776.776 0 0 0-.474-.713.778.778 0 0 0-.291-1.401.778.778 0 0 0-.568-1.314.776.776 0 0 0-.821-1.172.776.776 0 0 0-1.04-.983.776.776 0 0 0-1.216-.755.778.778 0 0 0-1.344-.495.778.778 0 0 0-1.416-.213.778.778 0 0 0-1.43.074.778.778 0 0 0-1.386.36.779.779 0 0 0-1.285.633.777.777 0 0 0-1.13.878.778.778 0 0 0-.931 1.086.779.779 0 0 0-.695 1.251.778.778 0 0 0-.426 1.366.777.777 0 0 0-.143 1.423.776.776 0 0 0 .146 1.423.776.776 0 0 0 .43 1.365.778.778 0 0 0 .697 1.25.775.775 0 0 0 .933 1.084.777.777 0 0 0 1.133.875.777.777 0 0 0 1.286.63.777.777 0 0 0 1.387.358ZM10 15a5 5 0 1 0 0-10 5 5 0 0 0 0 10Z"
          clipRule="evenodd"
        />
        <path
          fill="#C1C3C3"
          d="M8.472 5.833a.556.556 0 0 0-.555.556v1.666c0 .307.248.556.555.556h.209l-.964 7.709a.556.556 0 0 0 .551.624h3.464a.556.556 0 0 0 .551-.624l-.963-7.71h.208a.556.556 0 0 0 .555-.556V6.39a.556.556 0 0 0-.555-.556H8.472Z"
        />
        <path
          fill="#F5F7F8"
          d="m10 6.667-.994 2.247-2.34.3L8.393 10.9l-.452 2.432L10 11.944l2.06 1.39-.452-2.433 1.725-1.688-2.34-.299L10 6.667Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default MP;
