// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type MV_SharpProps = CountrySymbolProps;

const MV_Sharp = forwardRef<SVGSVGElement, MV_SharpProps>(function MV_Sharp(
  props: MV_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="MV_Sharp"
      aria-label="Maldives"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-MV-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-MV-a)`}>
        <path fill="#dd2033" d="M0 0h29v20H0z" />
        <path fill="#005b33" d="M4.028 3.6h20.944v12.8H4.028z" />
        <path
          fill="#f5f7f8"
          d="M18.125 14.482a6 6 0 0 1-1.75-.59c-2.634-1.367-3.574-4.335-2.1-6.63.614-.956 1.55-1.644 2.621-2.023-2.071-.239-4.195.634-5.305 2.361-1.474 2.296-.6 5.23 1.955 6.556a5.87 5.87 0 0 0 4.579.326"
        />
      </g>
    </CountrySymbol>
  );
});

export default MV_Sharp;
