// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type NA_SharpProps = CountrySymbolProps;

const NA_Sharp = forwardRef<SVGSVGElement, NA_SharpProps>(function NA_Sharp(
  props: NA_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="NA_Sharp"
      aria-label="Namibia"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-NA-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-NA-a)`}>
        <path fill="#005eb8" d="M0-4.4h29v28.8H0z" />
        <path fill="#009b77" d="M29 24.4H0L29-4.4z" />
        <path
          fill="#f5f7f8"
          d="m-2.417 17.218 5.66 8.117L33.991 5.361l-5.66-8.117z"
        />
        <path
          fill="#dd2033"
          d="M2.304 23.296-.96 18.613 28.914-.794l3.265 4.683z"
        />
        <path
          fill="#fbd381"
          d="m9.264 5.2-1.317.647.701 1.33-1.43-.285-.18 1.508-.996-1.109L5.046 8.4l-.181-1.508-1.43.286.701-1.331L2.82 5.2l1.317-.647-.701-1.33 1.43.285L5.045 2l.997 1.109L7.038 2l.18 1.508 1.43-.286-.7 1.331z"
        />
      </g>
    </CountrySymbol>
  );
});

export default NA_Sharp;
