// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type NC_SharpProps = CountrySymbolProps;

const NC_Sharp = forwardRef<SVGSVGElement, NC_SharpProps>(function NC_Sharp(
  props: NC_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="NC_Sharp"
      aria-label="New Caledonia"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-NC-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 20h29V0H0z" />
      </mask>
      <g mask={`url(#${uid}-NC-a)`}>
        <path fill="#004692" d="M0 0h29.091v6.666H0z" />
        <path fill="#dd2033" d="M0 6.666h29.091v6.666H0z" />
        <path fill="#008259" d="M0 13.327h29.091v6.666H0z" />
        <ellipse cx="12.174" cy="10" fill="#fbd381" rx="6.444" ry="6.4" />
        <path
          fill="#31373d"
          d="M12.323 6.068c.192-.094.397-.207.583-.38.085-.079.08-.094.08-.094s.055.098-.06.32c-.209.403-.418.656-.603.821v.718c.304.05.537.332.537.671 0 .34-.233.62-.537.671v.582h.695v.21h-.695v.1c.304.031.537.209.537.424 0 .214-.233.392-.537.424v.099h.695v.21h-.695v.657c.242.071.425.402.425.8s-.183.729-.425.8v.237c.284.017.55.089.695.22.315.281.878.935.982 1.057-.56.25-1.162.38-1.77.385h-.009a4.4 4.4 0 0 1-1.857-.42c.128-.149.744-.817.984-1.023.16-.137.465-.212.779-.222v-.234c-.242-.071-.425-.402-.425-.8s.183-.729.425-.8v-.657h-.695v-.21h.695v-.099c-.304-.032-.536-.21-.536-.424 0-.215.232-.393.536-.425v-.098h-.695v-.21h.695v-.583c-.304-.05-.536-.331-.536-.67 0-.34.232-.621.536-.672v-.567c-.209.137-.363.165-.414.21-.116.1-.165.093-.165.093.008-.09.016-.464.022-.5.046-.27.272-.39.557-.526V5h.196z"
        />
        <path
          fill="#31373d"
          d="M11.131 7.887s.124.38.143.764c.03.61.576.628.951.628v-.34c-.28 0-.525-.044-.73-.492-.1-.221-.364-.56-.364-.56m-.016 4.924s.2-.264.433-.883c.122-.322.411-.51.677-.51v-.475c-.603 0-.893.24-.923.59a11 11 0 0 1-.187 1.278"
        />
        <path
          fill="#31373d"
          d="M13.32 7.887s-.125.38-.143.764c-.03.61-.577.628-.952.628v-.34c.281 0 .525-.044.73-.492.1-.221.364-.56.364-.56m.015 4.924s-.2-.264-.433-.883c-.122-.322-.41-.51-.677-.51v-.475c.604 0 .893.24.924.59.062.719.186 1.278.186 1.278"
        />
      </g>
    </CountrySymbol>
  );
});

export default NC_Sharp;
