// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type NP_SharpProps = CountrySymbolProps;

const NP_Sharp = forwardRef<SVGSVGElement, NP_SharpProps>(function NP_Sharp(
  props: NP_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="NP_Sharp"
      aria-label="Nepal"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-NP-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-NP-a)`}>
        <path fill="#F5F7F8" d="M0 0h29v20H0z" />
        <path
          fill="#004692"
          d="M26.23 11.6H12.504L26.613 26H7.45L-7.814 11.6 4.45-7.627l4.356 3.845L26.229 11.6Z"
        />
        <path
          fill="#DD2033"
          d="M21.992 10 6.646-3H-6.042v27.4h28.84L8.688 10h13.303Z"
        />
        <path
          fill="#F5F7F8"
          d="m9.667 14.4-1.482.727.79 1.498-1.61-.321L7.163 18l-1.12-1.247L4.922 18l-.204-1.696-1.609.321.789-1.498-1.481-.727 1.48-.727-.788-1.498 1.608.321.204-1.696 1.12 1.248L7.163 10.8l.204 1.696 1.608-.32-.789 1.497 1.482.727Z"
        />
        <mask
          id={`${uid}-NP-b`}
          x="2"
          y="1"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <ellipse cx="6.042" cy="4.8" fill="#D9D9D9" rx="3.625" ry="3.6" />
        </mask>
        <g mask={`url(#${uid}-NP-b)`}>
          <path
            fill="#F5F7F8"
            d="m8.678 5.42-1.077.529.573 1.089-1.17-.234-.148 1.234-.814-.907-.815.907-.148-1.234-1.17.234.574-1.09-1.078-.528 1.078-.53-.574-1.088 1.17.233.148-1.233.815.907.814-.907.149 1.233 1.17-.233L7.6 4.89l1.077.529Z"
          />
        </g>
        <path
          fill="#F5F7F8"
          d="M9.649 4.438a3.957 3.957 0 0 1-3.607 2.315 3.957 3.957 0 0 1-3.607-2.315c-.012.12-.018.24-.018.362 0 1.988 1.623 3.6 3.625 3.6s3.625-1.612 3.625-3.6a3.61 3.61 0 0 0-.018-.362Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default NP_Sharp;
