// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type PM_SharpProps = CountrySymbolProps;

const PM_Sharp = forwardRef<SVGSVGElement, PM_SharpProps>(function PM_Sharp(
  props: PM_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="PM_Sharp"
      aria-label="Saint Pierre and Miquelon"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-PM-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-PM-a)`}>
        <path fill="#004692" d="M0 20h9.667V0H0z" />
        <path fill="#f5f7f8" d="M9.667 20h9.667V0H9.667z" />
        <path fill="#dd2033" d="M19.333 20H29V0h-9.667z" />
      </g>
    </CountrySymbol>
  );
});

export default PM_Sharp;
