// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type PNProps = CountrySymbolProps;

const PN = forwardRef<SVGSVGElement, PNProps>(function PN(props: PNProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="PN"
      aria-label="Pitcairn"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-PN-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-PN-a)`}>
        <path fill="#004692" d="M0 0h20v20H0z" />
        <path fill="#C1C3C3" d="M12.778 7.549h2.5v2.222h-2.5z" />
        <path
          fill="#008259"
          d="M13.056 5.605h.694v.833h.972V7.55h-1.666V5.605Z"
        />
        <path
          fill="#86C5FA"
          d="M11.111 9.722h5.833v2.088a4.63 4.63 0 0 1-2.916 4.301 4.63 4.63 0 0 1-2.917-4.301V9.722Z"
        />
        <mask
          id={`${uid}-PN-b`}
          x="11"
          y="9"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path
            fill="#86C5FA"
            d="M11.111 9.722h5.833v2.088a4.63 4.63 0 0 1-2.916 4.301 4.63 4.63 0 0 1-2.917-4.301V9.722Z"
          />
        </mask>
        <g mask={`url(#${uid}-PN-b)`}>
          <path
            fill="#FBD381"
            d="m14.028 9.722 2.916 6.39h-5.833l2.917-6.39Z"
          />
          <path
            fill="#008259"
            d="m14.028 11.16 2.916 6.389h-5.833l2.917-6.389Z"
          />
        </g>
        <mask
          id={`${uid}-PN-c`}
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path fill="#002F6C" d="M0 10C0 4.477 4.477 0 10 0v10H0Z" />
        </mask>
        <g mask={`url(#${uid}-PN-c)`}>
          <path fill="#004692" d="M0 0h10v10H0z" />
          <path
            fill="#F5F7F8"
            d="m3.478.87-.589.59 8.202 8.201.59-.589L3.477.87ZM1.907 2.442l-.982.982 8.202 8.201.982-.982-8.202-8.201Z"
          />
          <path
            fill="#DD2033"
            d="m1.907 2.442.982-.982 8.202 8.201-.982.982-8.202-8.201Z"
          />
          <path fill="#F5F7F8" d="M10 3.333v1.39H4.722V10H3.333V3.333H10Z" />
          <path fill="#F5F7F8" d="M10-.556v1.39H1.389V10H0V-.556h10Z" />
          <path
            fill="#DD2033"
            fillRule="evenodd"
            d="M.833 10h2.5V3.333H10v-2.5H.833V10Z"
            clipRule="evenodd"
          />
        </g>
      </g>
    </CountrySymbol>
  );
});

export default PN;
