// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type RS_SharpProps = CountrySymbolProps;

const RS_Sharp = forwardRef<SVGSVGElement, RS_SharpProps>(function RS_Sharp(
  props: RS_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="RS_Sharp"
      aria-label="Serbia"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-RS-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-RS-a)`}>
        <path fill="#f5f7f8" d="M0 20v-6.4h29V20z" />
        <path fill="#004692" d="M0 13.6V6.4h29v7.2z" />
        <path
          fill="#dd2033"
          d="M0 6.4V0h29v6.4zm4.43 0H14.5v5.295a5.74 5.74 0 0 1-3.587 5.32 3.86 3.86 0 0 1-2.896 0 5.74 5.74 0 0 1-3.586-5.32z"
        />
        <path
          fill="#f5f7f8"
          d="M12.315 8.164c-.392-.027-.967.031-1.413.255-.403.201-.684.516-.684 1.105v.203l3.564-.96a.935.935 0 0 1-.664 1.142l-2.9.78v.241l3.64-.979a.935.935 0 0 1-.664 1.142l-2.875.773.19.19 3.2-.861a.935.935 0 0 1-.663 1.141l-1.775.478 1.573 1.566-.965.96-1.7-1.693.72 1.795L9.537 16.8l-1.364-1.358.719-1.79-1.704 1.696-.964-.96 1.55-1.544-1.889-.508a.935.935 0 0 1-.663-1.141l3.313.891.19-.19-2.987-.803a.935.935 0 0 1-.664-1.142l3.776 1.016v-.24l-3.036-.818a.935.935 0 0 1-.664-1.141l3.7.995v-.231c0-.59-.281-.904-.684-1.106-.447-.223-1.022-.28-1.413-.254l-.094-1.355c.55-.038 1.389.03 2.119.396.273.136.532.316.752.544a2.8 2.8 0 0 1 .76-.552c.73-.365 1.569-.434 2.12-.396z"
        />
        <path
          fill="#dd2033"
          d="M7.653 9.6h3.625v2.24a2.09 2.09 0 0 1-1.245 1.91c-.362.16-.774.16-1.135 0a2.09 2.09 0 0 1-1.245-1.91z"
        />
        <path
          fill="#f1b434"
          fillRule="evenodd"
          d="M10.07.229h-.806V.8h-.806v.8h.806v.69a2.07 2.07 0 0 0-1.15-.347A2.064 2.064 0 0 0 6.041 4c0 .61.266 1.157.69 1.533V6.4h5.87v-.867c.423-.376.69-.924.69-1.533a2.064 2.064 0 0 0-2.072-2.057c-.426 0-.821.128-1.15.346V1.6h.805V.8h-.806zM9.666 5.36l-.01.01h.02zm-1.55-.332h-.004c-.572 0-1.036-.46-1.036-1.029 0-.568.464-1.028 1.036-1.028S9.15 3.432 9.15 4v1.03zM12.256 4c0 .568-.464 1.029-1.036 1.029h-1.035V4c0-.568.463-1.028 1.035-1.028s1.036.46 1.036 1.028"
          clipRule="evenodd"
        />
        <path
          fill="#f5f7f8"
          d="M9.989 9.6h-.806v1.6h-1.53v.8h1.53v2h.806v-2h1.289v-.8h-1.29z"
        />
      </g>
    </CountrySymbol>
  );
});

export default RS_Sharp;
