import { useId } from "@salt-ds/core";
import { clsx } from "clsx";
// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type SA_SharpProps = CountrySymbolProps;

const SA_Sharp = forwardRef<SVGSVGElement, SA_SharpProps>(function SA_Sharp(
  props: SA_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="SA_Sharp"
      aria-label="Saudi Arabia"
      viewBox="0 0 72 50"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-SA-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h72v50H0z" />
      </mask>
      <g mask={`url(#${uid}-SA-a)`}>
        <path fill="#005B33" d="M0 0h72v50H0z" />
        <path
          fill="#F5F7F8"
          d="M13.472 19.15A3.476 3.476 0 0 1 10 22.624v5.207c4.786 0 8.68-3.893 8.68-8.68V7h-5.208v12.15ZM50.792 7v12.15a3.476 3.476 0 0 1-3.471 3.473v5.207c4.785 0 8.679-3.893 8.679-8.68V7h-5.208Z"
        />
        <path
          fill="#F5F7F8"
          d="M48.188 7h-5.207v12.15h5.207V7ZM35.17 13.943a.869.869 0 0 1-1.736 0V7h-5.208v6.943a.869.869 0 0 1-1.735 0V7h-5.208v6.943a6.082 6.082 0 0 0 6.076 6.076c1.29 0 2.486-.405 3.471-1.094a6.04 6.04 0 0 0 4.239 1.044 3.475 3.475 0 0 1-3.37 2.654v5.207c4.785 0 8.678-3.893 8.678-8.68V7H35.17v6.943Z"
        />
        <path
          fill="#F5F7F8"
          d="M29.094 22.623h-7.811v5.207h7.811v-5.207ZM48.144 38H53v3h-4.856a4.502 4.502 0 0 1-8.488 0H15v-3h24.656a4.502 4.502 0 0 1 8.488 0Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default SA_Sharp;
