// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type SL_SharpProps = CountrySymbolProps;

const SL_Sharp = forwardRef<SVGSVGElement, SL_SharpProps>(function SL_Sharp(
  props: SL_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="SL_Sharp"
      aria-label="Sierra Leone"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-SL-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-SL-a)`}>
        <path fill="#005EB8" d="M0 20v-6.4h29V20z" />
        <path fill="#F5F7F8" d="M0 13.6V6.4h29v7.2z" />
        <path fill="#009B77" d="M0 6.4V0h29v6.4z" />
      </g>
    </CountrySymbol>
  );
});

export default SL_Sharp;
