// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type SN_SharpProps = CountrySymbolProps;

const SN_Sharp = forwardRef<SVGSVGElement, SN_SharpProps>(function SN_Sharp(
  props: SN_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="SN_Sharp"
      aria-label="Senegal"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-SN-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-SN-a)`}>
        <path fill="#005B33" d="M0 20h9.667V0H0z" />
        <path fill="#FBD381" d="M9.667 20h9.667V0H9.667z" />
        <path fill="#DD2033" d="M19.333 20H29V0h-9.667z" />
        <path
          fill="#005B33"
          d="m14.5 6-1.2 2.697-2.828.359 2.085 2.025L12.011 14l2.489-1.667L16.99 14l-.547-2.919 2.085-2.025-2.827-.36L14.5 6Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default SN_Sharp;
