// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type TJ_SharpProps = CountrySymbolProps;

const TJ_Sharp = forwardRef<SVGSVGElement, TJ_SharpProps>(function TJ_Sharp(
  props: TJ_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="TJ_Sharp"
      aria-label="Tajikistan"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-TJ-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-TJ-a)`}>
        <path fill="#008259" d="M0 20v-6.4h29V20z" />
        <path fill="#f5f7f8" d="M0 13.6V6.4h29v7.2z" />
        <path fill="#dd2033" d="M0 6.4V0h29v6.4z" />
        <path
          fill="#f1b434"
          d="m13.685 5.348.6-1.348.6 1.348 1.414.18-1.042 1.013L15.53 8l-1.245-.833L13.041 8l.273-1.46-1.043-1.012zm.614 5.052 2.071 2.057 1.15-.857 1.612 1.2-.472 2.4H9.937l-.472-2.4 1.611-1.2 1.151.857zM7.303 6.362l.287 1.446-1.054.952 1.439.236.619 1.351.538-1.391 1.5-.027-1.066-1.04.27-1.423-1.262.658zm-2.264 5.386.6-1.348.6 1.348 1.414.18L6.61 12.94l.274 1.459-1.245-.833-1.245.833.274-1.46-1.043-1.012zM23.361 10.4l-.6 1.348-1.414.18 1.043 1.013-.274 1.459 1.245-.833 1.245.833-.274-1.46 1.043-1.012-1.414-.18zm-3.337-3.276 1.27-.762-.287 1.446 1.054.952-1.439.236-.619 1.351-.538-1.391-1.5-.027 1.066-1.04-.27-1.423z"
        />
      </g>
    </CountrySymbol>
  );
});

export default TJ_Sharp;
