// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type TM_SharpProps = CountrySymbolProps;

const TM_Sharp = forwardRef<SVGSVGElement, TM_SharpProps>(function TM_Sharp(
  props: TM_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="TM_Sharp"
      aria-label="Turkmenistan"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-TM-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-TM-a)`}>
        <path fill="#009B77" d="M0 0h29v20H0z" />
        <path
          fill="#F5F7F8"
          d="m16.96 2.81.36-.81.36.81.848.107-.626.607.164.876-.747-.5-.746.5.164-.876-.626-.607.848-.108Zm3.221 2 .36-.81.36.81.849.107-.626.607.165.876-.747-.5-.747.5.164-.876-.626-.607.849-.108Zm-3.221 1.6.36-.81.36.81.848.107-.626.607.164.876-.747-.5-.746.5.164-.876-.626-.607.848-.108Zm-2.863.79-.36.81-.848.107.626.607-.165.876.747-.5.747.5-.164-.876.626-.607-.849-.108-.36-.809Zm3.223 2-.36.81-.849.107.626.607-.164.876.746-.5.747.5-.164-.876.626-.607-.848-.108-.36-.809Z"
        />
        <path
          fill="#F5F7F8"
          d="M24.041 6.634A5.845 5.845 0 0 0 21.3 2.613c2.33.5 4.237 2.357 4.667 4.834.567 3.257-1.633 6.354-4.914 6.916a6.047 6.047 0 0 1-5.44-1.823 5.557 5.557 0 0 0 3.854.748c3.073-.527 5.121-3.506 4.574-6.654Z"
        />
        <path fill="#DD2033" d="M-.08 24.4V-4.4h9.667v28.8z" />
        <path
          fill="#E26E00"
          d="M7.774 1.2 9.586 3V-.6L7.774 1.2Zm0 6.2 1.812 1.8V5.6L7.774 7.4Zm-6.042 0L-.081 9.2V5.6l1.813 1.8Zm6.042 6.2 1.812 1.8v-3.6l-1.812 1.8Zm-6.042 0-1.813 1.8v-3.6l1.813 1.8Zm6.042 6.2 1.812 1.8V18l-1.812 1.8Z"
        />
        <path
          fill="#009B77"
          fillRule="evenodd"
          d="M6.04 9.2H3.869l-.726.577v1.246l.726.577H6.04l.726-.577V9.777L6.04 9.2ZM6.466 8H3.444l-1.51 1.2v2.4l1.51 1.2h3.02l1.511-1.2V9.2L6.465 8Zm-.426 7.2H3.869l-.726.577v1.246l.726.577H6.04l.726-.577v-1.246L6.04 15.2Zm.425-1.2H3.444l-1.51 1.2v2.4l1.51 1.2h3.02l1.511-1.2v-2.4L6.465 14ZM6.04 3.2H3.869l-.726.577v1.246l.726.577H6.04l.726-.577V3.777L6.04 3.2ZM6.466 2H3.444l-1.51 1.2v2.4l1.51 1.2h3.02l1.511-1.2V3.2L6.465 2ZM6.04-2.8H3.869l-.726.577v1.246l.726.577H6.04l.726-.577v-1.246L6.04-2.8ZM6.466-4H3.444l-1.51 1.2v2.4L3.443.8h3.02L7.976-.4v-2.4L6.465-4ZM6.04 21.2H3.869l-.726.577v1.246l.726.577H6.04l.726-.577v-1.246L6.04 21.2Zm.425-1.2H3.444l-1.51 1.2v2.4l1.51 1.2h3.02l1.511-1.2v-2.4L6.465 20Z"
          clipRule="evenodd"
        />
      </g>
    </CountrySymbol>
  );
});

export default TM_Sharp;
