// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type TR_SharpProps = CountrySymbolProps;

const TR_Sharp = forwardRef<SVGSVGElement, TR_SharpProps>(function TR_Sharp(
  props: TR_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="TR_Sharp"
      aria-label="Türkiye"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-TR-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#d9d9d9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-TR-a)`}>
        <path fill="#dd2033" d="M0 20V0h29v20z" />
        <path
          fill="#f5f7f8"
          d="m18.485 6.668-.411 2.623-2.374.966 2.288 1.278.21 2.664 1.772-2.025 2.555.873-1.16-2.41 1.338-2.244-2.542.342z"
        />
        <path
          fill="#f5f7f8"
          d="M16.252 5.835a5 5 0 0 0-2.745-.812c-2.768 0-5.013 2.229-5.013 4.978s2.245 4.978 5.013 4.978a5 5 0 0 0 2.742-.81 6.45 6.45 0 0 1-4.89 2.231c-3.56 0-6.445-2.865-6.445-6.4s2.885-6.4 6.444-6.4a6.45 6.45 0 0 1 4.894 2.235"
        />
      </g>
    </CountrySymbol>
  );
});

export default TR_Sharp;
