// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type UZ_SharpProps = CountrySymbolProps;

const UZ_Sharp = forwardRef<SVGSVGElement, UZ_SharpProps>(function UZ_Sharp(
  props: UZ_SharpProps,
  ref,
) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="UZ_Sharp"
      aria-label="Uzbekistan"
      viewBox="0 0 29 20"
      ref={ref}
      sharp
      {...props}
    >
      <mask
        id={`${uid}-UZ-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path fill="#D9D9D9" d="M0 0h29v20H0z" />
      </mask>
      <g mask={`url(#${uid}-UZ-a)`}>
        <path fill="#0091DA" d="M0 0v8.8h29V0z" />
        <path
          fill="#F5F7F8"
          d="M22.48 1.418 22.757.8l.278.618.655.082-.483.464.127.67-.577-.383-.577.382.126-.669-.483-.464.655-.082Zm2.489 0L25.247.8l.278.618.655.082-.483.464.127.67-.577-.383-.577.382.127-.669-.483-.464.655-.082Zm-4.701 1.521-.278.618-.655.082.483.464-.127.669.577-.382.577.382-.127-.669.484-.464-.656-.082-.278-.618Zm2.212.618.278-.618.278.618.655.082-.483.464.127.669-.577-.382-.577.382.126-.669-.483-.464.655-.082Zm2.767-.618-.278.618-.655.082.483.464-.127.669.577-.382.577.382-.127-.669.483-.464-.655-.082-.278-.618ZM19.99 5.695l.278-.618.278.618.656.083-.484.464.127.669-.577-.382-.577.382.127-.67-.483-.463.655-.083Zm-2.211-.618-.279.618-.655.083.484.464-.127.669.577-.382.577.382-.127-.67.483-.463-.655-.083-.278-.618Zm7.19.618.278-.618.278.618.655.083-.483.464.127.669-.577-.382-.577.382.127-.67-.483-.463.655-.083Zm-2.211-.618-.279.618-.655.083.483.464-.126.669.577-.382.577.382-.127-.67.483-.463-.655-.083-.278-.618ZM13.99 6.32c.496.39 1.113.525 1.682.423a2.567 2.567 0 0 1-3.041-.086 2.452 2.452 0 0 1-.397-3.49 2.56 2.56 0 0 1 3.735-.233c-.82-.327-1.78-.118-2.344.576-.693.85-.53 2.11.364 2.81Z"
        />
        <path fill="#009B77" d="M0 14.8v9.6h29v-9.6z" />
        <path fill="#DD2033" d="M0 8.8v8.8h29V8.8z" />
        <path fill="#F5F7F8" d="M0 10.4V16h29v-5.6z" />
      </g>
    </CountrySymbol>
  );
});

export default UZ_Sharp;
