// WARNING: This file was generated by a script. Do not modify it manually

import { useId } from "@salt-ds/core";
import { forwardRef } from "react";

import { CountrySymbol, type CountrySymbolProps } from "../country-symbol";

export type VGProps = CountrySymbolProps;

const VG = forwardRef<SVGSVGElement, VGProps>(function VG(props: VGProps, ref) {
  const uid = useId(props.id);

  return (
    <CountrySymbol
      data-testid="VG"
      aria-label="Virgin Islands (British)"
      viewBox="0 0 20 20"
      ref={ref}
      {...props}
    >
      <mask
        id={`${uid}-VG-a`}
        x="0"
        y="0"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
      </mask>
      <g mask={`url(#${uid}-VG-a)`}>
        <path fill="#004692" d="M0 0h20v20H0z" />
        <mask
          id={`${uid}-VG-b`}
          x="0"
          y="0"
          maskUnits="userSpaceOnUse"
          style={{ maskType: "alpha" }}
        >
          <path fill="#002F6C" d="M0 10C0 4.477 4.477 0 10 0v10H0Z" />
        </mask>
        <g mask={`url(#${uid}-VG-b)`}>
          <path fill="#004692" d="M0 0h10v10H0z" />
          <path
            fill="#F5F7F8"
            d="m3.478.87-.589.59 8.202 8.201.59-.589L3.477.87ZM1.907 2.442l-.982.982 8.202 8.201.982-.982-8.202-8.201Z"
          />
          <path
            fill="#DD2033"
            d="m1.907 2.442.982-.982 8.202 8.201-.982.982-8.202-8.201Z"
          />
          <path fill="#F5F7F8" d="M10 3.333v1.389H4.722V10H3.333V3.333H10Z" />
          <path fill="#F5F7F8" d="M10-.556v1.39H1.389V10H0V-.556h10Z" />
          <path
            fill="#DD2033"
            fillRule="evenodd"
            d="M.833 10h2.5V3.333H10v-2.5H.833V10Z"
            clipRule="evenodd"
          />
        </g>
        <path
          fill="#FBD381"
          d="M17 14.722h-5.833v1.39H12v.832h4.167v-.833H17v-1.389Z"
        />
        <path
          fill="#008259"
          d="M11.167 9.722H17v2.088a4.63 4.63 0 0 1-2.917 4.301 4.63 4.63 0 0 1-2.916-4.301V9.722Z"
        />
        <path fill="#F5F7F8" d="M13.389 10.834h1.389v4.167h-1.389z" />
        <path
          fill="#F1B434"
          d="M12.139 11.111a.417.417 0 1 0 0-.833.417.417 0 0 0 0 .833Zm3.889 0a.417.417 0 1 0 0-.833.417.417 0 0 0 0 .833Zm.417.972a.417.417 0 1 1-.834 0 .417.417 0 0 1 .834 0Zm-4.306.417a.417.417 0 1 0 0-.833.417.417 0 0 0 0 .833Zm4.306.972a.417.417 0 1 1-.834 0 .417.417 0 0 1 .834 0Zm-4.306.417a.417.417 0 1 0 0-.833.417.417 0 0 0 0 .833Z"
        />
      </g>
    </CountrySymbol>
  );
});

export default VG;
