import figma from "@figma/code-connect";

import {
  SparkleIcon,
  SemanticVerySatisfiedIcon,
  SemanticVeryDissatisfiedIcon,
  StringNumberIcon,
  StringTextIcon,
  IconFigmaIcon,
  WifiDisabledIcon,
  WifiIcon,
  SignalIcon,
  WaveformIcon,
  HeadphonesDisabledIcon,
  HeadphonesIcon,
  MusicIcon,
  MusicDisabledIcon,
  BooleanIcon,
  CloudSyncIcon,
  SemanticDissatisfiedIcon,
  SemanticNeutralIcon,
  SemanticSatisfiedIcon,
  MicrophoneDisabledIcon,
  MicrophoneIcon,
  CloudDownloadIcon,
  CloudUploadIcon,
  CloudDisabledIcon,
  CloudSuccessIcon,
  SyncIcon,
  CollapseIcon,
  TypeIcon,
  LayersIcon,
  JigsawIcon,
  DragRowIcon,
  UngroupIcon,
  GroupIcon,
  SortDescendIcon,
  SortAscendIcon,
  ScalesIcon,
  WeightIcon,
  AccessibleIcon,
  AddIcon,
  AddDocumentIcon,
  ApiIcon,
  AppSwitcherIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AttachIcon,
  BankIcon,
  BankCheckIcon,
  BarChartIcon,
  BookmarkIcon,
  BrowserIcon,
  BatteryIcon,
  BuildingIcon,
  BuildingsIcon,
  BuildReportIcon,
  CalculatorIcon,
  CalendarIcon,
  CallIcon,
  CartIcon,
  ChatIcon,
  ChatGroupIcon,
  ChattingIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  CloneIcon,
  CloseIcon,
  ClosedcaptionIcon,
  ClosedcaptionDisabledIcon,
  CloudIcon,
  CoffeeIcon,
  CollapseAllIcon,
  ColumnChooserIcon,
  CommentaryIcon,
  CompassIcon,
  CookieIcon,
  CopyIcon,
  CreditCardIcon,
  CropsIcon,
  CsvIcon,
  CutIcon,
  DarkIcon,
  DashboardIcon,
  DatabaseIcon,
  DeleteIcon,
  DevicesIcon,
  DiamondIcon,
  DisplayIcon,
  DocumentIcon,
  DoubleChevronDownIcon,
  DoubleChevronLeftIcon,
  DoubleChevronRightIcon,
  DoubleChevronUpIcon,
  DownloadIcon,
  EditIcon,
  ErrorIcon,
  ErrorExecuteIcon,
  ExpandIcon,
  ExpandAllIcon,
  ExportIcon,
  FavoriteIcon,
  FilterIcon,
  FilterClearIcon,
  FlagIcon,
  FolderClosedIcon,
  FolderOpenIcon,
  Forward5Icon,
  Forward10Icon,
  Forward15Icon,
  Forward30Icon,
  GithubIcon,
  GlobeIcon,
  GridIcon,
  GuideClosedIcon,
  GuideOpenIcon,
  HelpIcon,
  HiddenIcon,
  HomeIcon,
  HospitalIcon,
  ImageIcon,
  ImportIcon,
  InboxIcon,
  InfoIcon,
  KeyIcon,
  KeyBackspaceIcon,
  KeyCapslockIcon,
  KeyCommandIcon,
  KeyControlIcon,
  KeyEnterIcon,
  KeyOptionIcon,
  KeyShiftIcon,
  KeyTabIcon,
  LaptopIcon,
  LightIcon,
  LineChartIcon,
  LinkedIcon,
  ListIcon,
  LoaderIcon,
  LocationIcon,
  LockedIcon,
  ManIcon,
  ManWomanIcon,
  MapIcon,
  MarkerIcon,
  MaximizeIcon,
  MedicalKitIcon,
  MenuIcon,
  MessageIcon,
  MicroMenuIcon,
  MinimizeIcon,
  MobileIcon,
  MouseIcon,
  MoveAllIcon,
  MoveHorizontalIcon,
  MoveVerticalIcon,
  NoteIcon,
  NotificationIcon,
  NotificationReadIcon,
  OverflowMenuIcon,
  PasteIcon,
  PauseIcon,
  PdfIcon,
  PicnicIcon,
  PinIcon,
  PivotIcon,
  PlaceInIcon,
  PlayIcon,
  PotFoodIcon,
  PresentationIcon,
  PriceLadderIcon,
  PrintIcon,
  ProgressCancelledIcon,
  ProgressClosedIcon,
  //   SuccessCircleIcon,
  ProgressCompleteIcon,
  ProgressDraftIcon,
  ProgressInprogressIcon,
  ProgressOnholdIcon,
  ProgressPendingIcon,
  ProgressRejectedIcon,
  ProgressTodoIcon,
  ProtectionIcon,
  ReceiptIcon,
  RedoIcon,
  RefreshIcon,
  RemoveIcon,
  RemoveDocumentIcon,
  Replay5Icon,
  Replay10Icon,
  Replay15Icon,
  Replay30Icon,
  RestoreIcon,
  RunReportIcon,
  SaltShakerIcon,
  SaveIcon,
  ScheduleTimeIcon,
  SearchIcon,
  SendIcon,
  SettingsIcon,
  ShareIcon,
  SignpostIcon,
  SortableAlphaIcon,
  SortableNumIcon,
  SortAlphaAscendIcon,
  SortAlphaDescendIcon,
  SortNumAscendIcon,
  SortNumDescendIcon,
  StackoverflowIcon,
  StepActiveIcon,
  StepDefaultIcon,
  StethoscopeIcon,
  StorageIcon,
  StorefrontIcon,
  //   CheckmarkIcon,
  SumIcon,
  SwapIcon,
  SymphonyIcon,
  TagIcon,
  TagClearIcon,
  TailsIcon,
  TargetIcon,
  TearOutIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  ToteIcon,
  TreeIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleRightDownIcon,
  TriangleUpIcon,
  HistoryIcon,
  UndoIcon,
  UniversalAccessIcon,
  UnlinkedIcon,
  UnlockedIcon,
  UploadIcon,
  UrgencyCriticalIcon,
  UrgencyHighIcon,
  UrgencyLowIcon,
  UrgencyMediumIcon,
  UrgencyNoneIcon,
  UserIcon,
  UserAdminIcon,
  UserBadgeIcon,
  UserGroupIcon,
  UtensilsIcon,
  VideoIcon,
  VideoDisabledIcon,
  VisibleIcon,
  VolumeDownIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  WarningIcon,
  WatchIcon,
  WomanIcon,
  WoodlandIcon,
  XlsIcon,
  ZipIcon,
} from "../components";

figma.connect(
  SparkleIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=6480-44",
);
figma.connect(
  SemanticVerySatisfiedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4098-748",
);
figma.connect(
  SemanticVeryDissatisfiedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4098-731",
);
figma.connect(
  StringNumberIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4256-300",
);
figma.connect(
  StringTextIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4256-287",
);
figma.connect(
  IconFigmaIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4256-237",
);
figma.connect(
  WifiDisabledIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4263-412",
);
figma.connect(
  WifiIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4092-619",
);
figma.connect(
  SignalIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4092-617",
);
figma.connect(
  WaveformIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4092-557",
);
figma.connect(
  HeadphonesDisabledIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4092-521",
);
figma.connect(
  HeadphonesIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4092-509",
);
figma.connect(
  MusicIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4092-471",
);
figma.connect(
  MusicDisabledIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4092-451",
);
figma.connect(
  BooleanIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4256-241",
);
figma.connect(
  CloudSyncIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4081-392",
);
figma.connect(
  SemanticDissatisfiedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3974-537",
);
figma.connect(
  SemanticNeutralIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3974-533",
);
figma.connect(
  SemanticSatisfiedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3974-517",
);
figma.connect(
  MicrophoneDisabledIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3974-502",
);
figma.connect(
  MicrophoneIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3974-495",
);
figma.connect(
  CloudDownloadIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3968-479",
);
figma.connect(
  CloudUploadIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3968-464",
);
figma.connect(
  CloudDisabledIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3968-449",
);
figma.connect(
  CloudSuccessIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3968-427",
);
figma.connect(
  SyncIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4256-215",
);
figma.connect(
  CollapseIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3968-423",
);
figma.connect(
  TypeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3078-479",
);
figma.connect(
  LayersIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3078-462",
);
figma.connect(
  JigsawIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3078-442",
);
figma.connect(
  DragRowIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=3071-26",
);
figma.connect(
  UngroupIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=2140-444",
);
figma.connect(
  GroupIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=2140-435",
);
figma.connect(
  SortDescendIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=2013-287",
);
figma.connect(
  SortAscendIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=2013-197",
);
figma.connect(
  ScalesIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1964-254",
);
figma.connect(
  WeightIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1964-234",
);
figma.connect(
  AccessibleIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1040-193",
);
figma.connect(
  AddIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8-1587",
);
figma.connect(
  AddDocumentIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8-1561",
);
figma.connect(
  ApiIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=135-1937",
);
figma.connect(
  AppSwitcherIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8-1593",
);
figma.connect(
  ArrowDownIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8-1603",
);
figma.connect(
  ArrowLeftIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=13-1561",
);
figma.connect(
  ArrowRightIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=13-1563",
);
figma.connect(
  ArrowUpIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=13-1565",
);
figma.connect(
  AttachIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8-1610",
);
figma.connect(
  BankIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1817-274",
);
figma.connect(
  BankCheckIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1573",
);
figma.connect(
  BarChartIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8-1616",
);
figma.connect(
  BookmarkIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1531",
);
figma.connect(
  BrowserIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1817-290",
);
figma.connect(
  BatteryIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1812-274",
);
figma.connect(
  BuildingIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1594",
);
figma.connect(
  BuildingsIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1638",
);
figma.connect(
  BuildReportIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8-1618",
);
figma.connect(
  CalculatorIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=137-1594",
);
figma.connect(
  CalendarIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=13-1520",
);
figma.connect(
  CallIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=13-1537",
);
figma.connect(
  CartIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-553",
);
figma.connect(
  ChatIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=19-1490",
);
figma.connect(
  ChatGroupIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=13-1587",
);
figma.connect(
  ChattingIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=21-1499",
);
figma.connect(
  ChevronDownIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=21-1509",
);
figma.connect(
  ChevronLeftIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1516",
);
figma.connect(
  ChevronRightIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1521",
);
figma.connect(
  ChevronUpIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1526",
);
figma.connect(
  ClockIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1533",
);
figma.connect(
  CloneIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1543",
);
figma.connect(
  CloseIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1550",
);
figma.connect(
  ClosedcaptionIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=135-1871",
);
figma.connect(
  ClosedcaptionDisabledIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=135-1884",
);
figma.connect(
  CloudIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=135-1846",
);
figma.connect(
  CoffeeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=136-1524",
);
figma.connect(
  CollapseAllIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1533-218",
);
figma.connect(
  ColumnChooserIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1566",
);
figma.connect(
  CommentaryIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1578",
);
figma.connect(
  CompassIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1703",
);
figma.connect(
  CookieIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1683",
);
figma.connect(
  CopyIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1589",
);
figma.connect(
  CreditCardIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1584",
);
figma.connect(
  CropsIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1223-290",
);
figma.connect(
  CsvIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1598",
);
figma.connect(
  CutIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1603",
);
figma.connect(
  DarkIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=160-1784",
);
figma.connect(
  DashboardIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1610",
);
figma.connect(
  DatabaseIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1621",
);
figma.connect(
  DeleteIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=22-1632",
);
figma.connect(
  DevicesIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1817-309",
);
figma.connect(
  DiamondIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1721",
);
figma.connect(
  DisplayIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1812-256",
);
figma.connect(
  DocumentIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1493",
);
figma.connect(
  DoubleChevronDownIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1510",
);
figma.connect(
  DoubleChevronLeftIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1514",
);
figma.connect(
  DoubleChevronRightIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1519",
);
figma.connect(
  DoubleChevronUpIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1525",
);
figma.connect(
  DownloadIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1533",
);
figma.connect(
  EditIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=28-1539",
);
figma.connect(
  ErrorIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=29-1509",
);
figma.connect(
  ErrorExecuteIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=13-1574",
);
figma.connect(
  ExpandIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=29-1539",
);
figma.connect(
  ExpandAllIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1533-203",
);
figma.connect(
  ExportIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=29-1530",
);
figma.connect(
  FavoriteIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=30-1491",
);
figma.connect(
  FilterIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=31-1503",
);
figma.connect(
  FilterClearIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1743",
);
figma.connect(
  FlagIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=31-1515",
);
figma.connect(
  FolderClosedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=32-1561",
);
figma.connect(
  FolderOpenIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=32-1579",
);
figma.connect(
  Forward5Icon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1598",
);
figma.connect(
  Forward10Icon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1611",
);
figma.connect(
  Forward15Icon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1614",
);
figma.connect(
  Forward30Icon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1617",
);
figma.connect(
  GithubIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1223-394",
);
figma.connect(
  GlobeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1624",
);
figma.connect(
  GridIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1643",
);
figma.connect(
  GuideClosedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1655",
);
figma.connect(
  GuideOpenIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1673",
);
figma.connect(
  HelpIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=33-1683",
);
figma.connect(
  HiddenIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1695",
);
figma.connect(
  HomeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1702",
);
figma.connect(
  HospitalIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-651",
);
figma.connect(
  ImageIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=105-1490",
);
figma.connect(
  ImportIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1714",
);
figma.connect(
  InboxIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1725",
);
figma.connect(
  InfoIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1739",
);
figma.connect(
  KeyIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1546",
);
figma.connect(
  KeyBackspaceIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=346-3270",
);
figma.connect(
  KeyCapslockIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=320-3140",
);
figma.connect(
  KeyCommandIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=317-3134",
);
figma.connect(
  KeyControlIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=315-3136",
);
figma.connect(
  KeyEnterIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=345-3527",
);
figma.connect(
  KeyOptionIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=317-3130",
);
figma.connect(
  KeyShiftIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=315-3130",
);
figma.connect(
  KeyTabIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=345-3512",
);
figma.connect(
  LaptopIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1812-267",
);
figma.connect(
  LightIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=160-1777",
);
figma.connect(
  LineChartIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1750",
);
figma.connect(
  LinkedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1770",
);
figma.connect(
  ListIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1775",
);
figma.connect(
  LoaderIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=47-2311",
);
figma.connect(
  LocationIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1780",
);
figma.connect(
  LockedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1799",
);
figma.connect(
  ManIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-862",
);
figma.connect(
  ManWomanIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-961",
);
figma.connect(
  MapIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1223-494",
);
figma.connect(
  MarkerIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1223-449",
);
figma.connect(
  MaximizeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=36-1810",
);
figma.connect(
  MedicalKitIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-700",
);
figma.connect(
  MenuIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1815",
);
figma.connect(
  MessageIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1822",
);
figma.connect(
  MicroMenuIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1831",
);
figma.connect(
  MinimizeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1836",
);
figma.connect(
  MobileIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1812-247",
);
figma.connect(
  MouseIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1847-214",
);
figma.connect(
  MoveAllIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1841",
);
figma.connect(
  MoveHorizontalIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1846",
);
figma.connect(
  MoveVerticalIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1851",
);
figma.connect(
  NoteIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1862",
);
figma.connect(
  NotificationIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1873",
);
figma.connect(
  NotificationReadIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1810-253",
);
figma.connect(
  OverflowMenuIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1883",
);
figma.connect(
  PasteIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1890",
);
figma.connect(
  PauseIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1901",
);
figma.connect(
  PdfIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1910",
);
figma.connect(
  PicnicIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1223-363",
);
figma.connect(
  PinIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1929",
);
figma.connect(
  PivotIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=38-1940",
);
figma.connect(
  PlaceInIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=41-1957",
);
figma.connect(
  PlayIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-1964",
);
figma.connect(
  PotFoodIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-373",
);
figma.connect(
  PresentationIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-1975",
);
figma.connect(
  PriceLadderIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-1985",
);
figma.connect(
  PrintIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-1992",
);
figma.connect(
  ProgressCancelledIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1511",
);
figma.connect(
  ProgressClosedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1515",
);
// figma.connect(
//   SuccessCircleIcon,
//   "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8892-112",
// );
figma.connect(
  ProgressCompleteIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1509",
);
figma.connect(
  ProgressDraftIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1503",
);
figma.connect(
  ProgressInprogressIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1505",
);
figma.connect(
  ProgressOnholdIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1518",
);
figma.connect(
  ProgressPendingIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1521",
);
figma.connect(
  ProgressRejectedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1524",
);
figma.connect(
  ProgressTodoIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1500",
);
figma.connect(
  ProtectionIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2003",
);
figma.connect(
  ReceiptIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=136-1491",
);
figma.connect(
  RedoIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2012",
);
figma.connect(
  RefreshIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2017",
);
figma.connect(
  RemoveIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2034",
);
figma.connect(
  RemoveDocumentIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2024",
);
figma.connect(
  Replay5Icon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2068",
);
figma.connect(
  Replay10Icon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2071",
);
figma.connect(
  Replay15Icon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2074",
);
figma.connect(
  Replay30Icon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2077",
);
figma.connect(
  RestoreIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=47-2316",
);
figma.connect(
  RunReportIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=42-2047",
);
figma.connect(
  SaltShakerIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1847-324",
);
figma.connect(
  SaveIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=43-2084",
);
figma.connect(
  ScheduleTimeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=43-2093",
);
figma.connect(
  SearchIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=43-2130",
);
figma.connect(
  SendIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2135",
);
figma.connect(
  SettingsIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2142",
);
figma.connect(
  ShareIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2155",
);
figma.connect(
  SignpostIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1223-407",
);
figma.connect(
  SortableAlphaIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1810-278",
);
figma.connect(
  SortableNumIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1810-283",
);
figma.connect(
  SortAlphaAscendIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1821",
);
figma.connect(
  SortAlphaDescendIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=133-1826",
);
figma.connect(
  SortNumAscendIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=135-1831",
);
figma.connect(
  SortNumDescendIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=135-1837",
);
figma.connect(
  StackoverflowIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2165",
);
figma.connect(
  StepActiveIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2278",
);
figma.connect(
  StepDefaultIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=45-2281",
);
figma.connect(
  StethoscopeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-749",
);
figma.connect(
  StorageIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2172",
);
figma.connect(
  StorefrontIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-471",
);
// figma.connect(
//   CheckmarkIcon,
//   "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=8892-407",
// );
figma.connect(
  SumIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2198",
);
figma.connect(
  SwapIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2210",
);
figma.connect(
  SymphonyIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2215",
);
figma.connect(
  TagIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=136-1538",
);
figma.connect(
  TagClearIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=136-1568",
);
figma.connect(
  TailsIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1777",
);
figma.connect(
  TargetIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=130-1651",
);
figma.connect(
  TearOutIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2220",
);
figma.connect(
  ThumbsDownIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=29-1497",
);
figma.connect(
  ThumbsUpIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=35-1761",
);
figma.connect(
  ToteIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-520",
);
figma.connect(
  TreeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2227",
);
figma.connect(
  TriangleDownIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2248",
);
figma.connect(
  TriangleLeftIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2251",
);
figma.connect(
  TriangleRightIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2257",
);
figma.connect(
  TriangleRightDownIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2254",
);
figma.connect(
  TriangleUpIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2260",
);
figma.connect(
  HistoryIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=4256-392",
);
figma.connect(
  UndoIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2371",
);
figma.connect(
  UniversalAccessIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1198-204",
);
figma.connect(
  UnlinkedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=44-2265",
);
figma.connect(
  UnlockedIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=47-2294",
);
figma.connect(
  UploadIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=48-2321",
);
figma.connect(
  UrgencyCriticalIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=115-1501",
);
figma.connect(
  UrgencyHighIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=115-1498",
);
figma.connect(
  UrgencyLowIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=115-1492",
);
figma.connect(
  UrgencyMediumIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=115-1495",
);
figma.connect(
  UrgencyNoneIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=105-1513",
);
figma.connect(
  UserIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2362",
);
figma.connect(
  UserAdminIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=48-2328",
);
figma.connect(
  UserBadgeIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=48-2344",
);
figma.connect(
  UserGroupIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2351",
);
figma.connect(
  UtensilsIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-193",
);
figma.connect(
  VideoIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=135-1912",
);
figma.connect(
  VideoDisabledIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=135-1925",
);
figma.connect(
  VisibleIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2378",
);
figma.connect(
  VolumeDownIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2402",
);
figma.connect(
  VolumeOffIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2405",
);
figma.connect(
  VolumeUpIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2408",
);
figma.connect(
  WarningIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2389",
);
figma.connect(
  WatchIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1823-382",
);
figma.connect(
  WomanIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1024-912",
);
figma.connect(
  WoodlandIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=1219-207",
);
figma.connect(
  XlsIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2431",
);
figma.connect(
  ZipIcon,
  "https://figma.com/file/9laF7Zn75aUMNsqSqRgAuX/?node-id=50-2424",
);
