name: Bug report 🪲
description: Report bugs in our code.
labels:
  - "type: bug 🪲"
  - "status: awaiting triage"
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Warning
        This is a public repository, so **please do not include any internal company code or sensitive data** in your bug report.
  - type: dropdown
    attributes:
      label: Package name(s)
      description: |
        Which package(s) did you observe this bug in? If you’re not sure which version your project is using, run `npm ls [package name]` or `yarn why [package name]` to find out.

        We only accept bug reports for packages shown in the menu below. If a package isn’t listed, then it’s not one that we support.
      multiple: true
      options:
        - "Core (@salt-ds/core)"
        - "Icons (@salt-ds/icons)"
        - "Theme (@salt-ds/theme)"
        - "Lab (@salt-ds/lab)"
        - "Data Grid (@salt-ds/data-grid)"
        - "AG Grid Theme (@salt-ds/ag-grid-theme)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Package version(s)
      description: Which version(s) did you observe the bug?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Tell us what's going wrong. Make sure that you copy and paste _as text_ any code, errors or log messages. Where relevant, you can also include supporting screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe the steps or code needed to reproduce this bug. Make sure that you copy and paste _as text_ any code, errors or log messages. Where relevant, you can also include supporting screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Operating system
      description: On which operating system(s) have you observed the bug?
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: iOS
        - label: Android
  - type: checkboxes
    attributes:
      label: Browser
      description: In which browser(s), if any, have you observed the bug?
      options:
        - label: Chrome
        - label: Safari
        - label: Firefox
        - label: Edge
  - type: checkboxes
    attributes:
      label: Are you a JPMorgan Chase & Co. employee?
      description: We ask this in case we need to contact you directly via internal company systems. Leave the box unticked if this doesn’t apply to you.
      options:
        - label: I am an employee of JPMorgan Chase & Co.
