name: Feature request 💡
description: Suggest new functionality, components or ideas for the Salt Design System.
labels:
  - "type: enhancement 💡"
  - "status: awaiting triage"
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Warning
        This is a public repository, so **please do not include any internal company code or sensitive data** in your bug report.
  - type: dropdown
    attributes:
      label: Area
      description: |
        Which aspect(s) of the Salt Design System does your proposed feature relate to? Select all that apply.
      multiple: true
      options:
        - UI Components
        - Documentation
        - Process
        - Tools
        - Website
    validations:
      required: true
  - type: textarea
    attributes:
      label: The problem
      description: |
        Provide a clear and concise description of what the problem is. Make sure that you copy and paste _as text_ any code, errors or log messages. Where relevant, you can also include supporting screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: The solution
      description: Tell us what functionality or behavior, for example, you would prefer instead. Feel free to attach  design mock ups or specifications you may have.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives and examples
      description: |
        Describe or share alternative solutions or features you've considered that you may have seen elsewhere. Make sure that you copy and paste _as text_ any code, errors or log messages. Where relevant, you can also include supporting screenshots.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Are you a JPMorgan Chase & Co. employee?
      description: We ask this in case we need to contact you directly via internal company systems. Leave the box unticked if this doesn’t apply to you.
      options:
        - label: I am an employee of JPMorgan Chase & Co.
