---
name: Feature request 💡
about: Suggest new functionality, components or ideas for this project
labels:
  - "type: enhancement 💡"
  - "status: awaiting triage"
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Warning
        This is a public repository, so **please do not include any company-internal code or details in your bug report**.
  - type: dropdown
    attributes:
      label: Area
      description: |
        Which aspect(s) of the Salt design system does your proposed feature relate to?
      multiple: true
      options:
        - UI Components
        - Website & documentation
        - Tools
        - Process
    validations:
      required: true
  - type: textarea
    attributes:
      label: The problem
      description: |
        A clear and concise description of what the problem is (For example: I'm always frustrated when...). Where relevant, please include screenshots as well. When including code, errors or log messages, please copy-paste them as text, not screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: The solution
      description: A clear and concise description of what you want to happen instead. Where relevant, please consider attaching design mockups or specs.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives and examples
      description: |
        A clear and concise description of any alternative solutions or features you've considered or examples of similar solutions you've seen elsewhere. Where relevant, please include screenshots as well. When including code, errors or log messages, please copy-paste them as text, not screenshots.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Are you a JPMorgan Chase employee?
      description: We ask this incase we need to contact you directly via company-internal systems. Leave this unticked if you are a not a JPMC employee.
      options:
        - label: I am an employee of JPMorgan Chase
