name: Feature request 💡
description: Want to suggest new functionality, components or ideas?
labels:
  - "type: enhancement 💡"
  - "status: awaiting triage"
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Warning
        This is a public repository, so **please do not include any internal company code or sensitive data** in your bug report. If you are an internal JPM user, please also look at your [internal options](https://go/salt-ds-support).
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug! Before you start, please check that your feature isn’t already requested by searching the [existing issues](https://github.com/jpmorganchase/salt-ds/issues?q=sort%3Aupdated-desc+is%3Aissue).
  - type: textarea
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Tell us what functionality or behavior, for example, you would prefer instead. Feel free to attach  design mock ups or specifications you may have.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives and examples
      description: Describe or share alternative solutions or features you've considered that you may have seen elsewhere.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: Providing context helps us understand the problem you're trying to solve. For example, what are you trying to accomplish? How does this feature fit into your workflow?
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Other"
  - type: checkboxes
    attributes:
      label: Are you a JPMorgan Chase & Co. employee?
      description: We ask this in case we need to contact you directly via internal company systems. Leave the box unticked if this doesn’t apply to you.
      options:
        - label: I am an employee of JPMorgan Chase & Co.
