import {
  AddIcon,
  AddDocumentIcon,
  AppSwitcherIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AttachIcon,
  BarChartIcon,
  BuildReportIcon,
  CalendarIcon,
  CallIcon,
  CallSolidIcon,
  ChatIcon,
  ChatGroupIcon,
  ChatGroupSolidIcon,
  ChatSolidIcon,
  ChattingIcon,
  ChattingSolidIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  ClockSolidIcon,
  CloneIcon,
  CloseIcon,
  CloseSmallIcon,
  ColumnChooserIcon,
  CommentaryIcon,
  CopyIcon,
  CsvIcon,
  CutIcon,
  DeleteIcon,
  DeleteSolidIcon,
  DocumentIcon,
  DoubleChevronDownIcon,
  DoubleChevronLeftIcon,
  DoubleChevronRightIcon,
  DoubleChevronUpIcon,
  DownloadIcon,
  EditIcon,
  EditSolidIcon,
  ErrorIcon,
  ErrorExecuteIcon,
  ErrorSecondaryIcon,
  ExportIcon,
  ExportSolidIcon,
  FavoriteIcon,
  FavoriteSolidIcon,
  FilterIcon,
  FilterSolidIcon,
  FlagIcon,
  FlagSolidIcon,
  FolderClosedIcon,
  FolderOpenIcon,
  GridIcon,
  GridSolidIcon,
  HelpIcon,
  HelpSecondaryIcon,
  HiddenIcon,
  HomeIcon,
  HomeSolidIcon,
  ImportIcon,
  ImportSolidIcon,
  InfoIcon,
  InfoSecondaryIcon,
  LineChartIcon,
  LineChartSolidIcon,
  LinkedIcon,
  ListIcon,
  LoaderIcon,
  LocationIcon,
  LockedIcon,
  LockedSolidIcon,
  MaximizeIcon,
  MenuIcon,
  MessageIcon,
  MessageSolidIcon,
  MicroMenuIcon,
  MinimizeIcon,
  MoveAllIcon,
  MoveHorizontalIcon,
  MoveVerticalIcon,
  NotificationIcon,
  NotificationSolidIcon,
  OverflowMenuIcon,
  PasteIcon,
  PauseIcon,
  PauseSolidIcon,
  PdfIcon,
  PinIcon,
  PinSolidIcon,
  PivotIcon,
  PlaceInIcon,
  PlayIcon,
  PlaySolidIcon,
  PriceLadderIcon,
  PrintIcon,
  PrintSolidIcon,
  RedoIcon,
  RefreshIcon,
  RemoveIcon,
  RemoveDocumentIcon,
  RestoreIcon,
  RunReportIcon,
  SaveIcon,
  SaveSolidIcon,
  ScheduleTimeIcon,
  SearchIcon,
  SendIcon,
  SettingsIcon,
  SettingsSolidIcon,
  ShareIcon,
  ShareSolidIcon,
  SuccessIcon,
  SuccessSecondaryIcon,
  SuccessTickIcon,
  SumIcon,
  SumSolidIcon,
  SwapIcon,
  TearOutIcon,
  ThumbsDownIcon,
  ThumbsDownSolidIcon,
  ThumbsUpIcon,
  ThumbsUpSolidIcon,
  TreeIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleRightDownIcon,
  TriangleUpIcon,
  UndoIcon,
  UnlinkedIcon,
  UnlockedIcon,
  UnlockedSolidIcon,
  UploadIcon,
  UserIcon,
  UserBadgeIcon,
  UserGroupIcon,
  UserGroupSolidIcon,
  UserSolidIcon,
  VisibleIcon,
  VisibleSolidIcon,
  WarningIcon,
  WarningSecondaryIcon,
  XlsIcon
} from "@jpmorganchase/uitk-icons";

export const allIconNamePairs = [
  ["add", AddIcon],
  ["add document", AddDocumentIcon],
  ["app switcher", AppSwitcherIcon],
  ["arrow down", ArrowDownIcon],
  ["arrow left", ArrowLeftIcon],
  ["arrow right", ArrowRightIcon],
  ["arrow up", ArrowUpIcon],
  ["attach", AttachIcon],
  ["bar chart", BarChartIcon],
  ["build report", BuildReportIcon],
  ["calendar", CalendarIcon],
  ["call", CallIcon],
  ["call solid", CallSolidIcon],
  ["chat", ChatIcon],
  ["chat group", ChatGroupIcon],
  ["chat group solid", ChatGroupSolidIcon],
  ["chat solid", ChatSolidIcon],
  ["chatting", ChattingIcon],
  ["chatting solid", ChattingSolidIcon],
  ["chevron down", ChevronDownIcon],
  ["chevron left", ChevronLeftIcon],
  ["chevron right", ChevronRightIcon],
  ["chevron up", ChevronUpIcon],
  ["clock", ClockIcon],
  ["clock solid", ClockSolidIcon],
  ["clone", CloneIcon],
  ["close", CloseIcon],
  ["close small", CloseSmallIcon],
  ["column chooser", ColumnChooserIcon],
  ["commentary", CommentaryIcon],
  ["copy", CopyIcon],
  ["csv", CsvIcon],
  ["cut", CutIcon],
  ["delete", DeleteIcon],
  ["delete solid", DeleteSolidIcon],
  ["document", DocumentIcon],
  ["double chevron down", DoubleChevronDownIcon],
  ["double chevron left", DoubleChevronLeftIcon],
  ["double chevron right", DoubleChevronRightIcon],
  ["double chevron up", DoubleChevronUpIcon],
  ["download", DownloadIcon],
  ["edit", EditIcon],
  ["edit solid", EditSolidIcon],
  ["error", ErrorIcon],
  ["error execute", ErrorExecuteIcon],
  ["error secondary", ErrorSecondaryIcon],
  ["export", ExportIcon],
  ["export solid", ExportSolidIcon],
  ["favorite", FavoriteIcon],
  ["favorite solid", FavoriteSolidIcon],
  ["filter", FilterIcon],
  ["filter solid", FilterSolidIcon],
  ["flag", FlagIcon],
  ["flag solid", FlagSolidIcon],
  ["folder closed", FolderClosedIcon],
  ["folder open", FolderOpenIcon],
  ["grid", GridIcon],
  ["grid solid", GridSolidIcon],
  ["help", HelpIcon],
  ["help secondary", HelpSecondaryIcon],
  ["hidden", HiddenIcon],
  ["home", HomeIcon],
  ["home solid", HomeSolidIcon],
  ["import", ImportIcon],
  ["import solid", ImportSolidIcon],
  ["info", InfoIcon],
  ["info secondary", InfoSecondaryIcon],
  ["line chart", LineChartIcon],
  ["line chart solid", LineChartSolidIcon],
  ["linked", LinkedIcon],
  ["list", ListIcon],
  ["loader", LoaderIcon],
  ["location", LocationIcon],
  ["locked", LockedIcon],
  ["locked solid", LockedSolidIcon],
  ["maximize", MaximizeIcon],
  ["menu", MenuIcon],
  ["message", MessageIcon],
  ["message solid", MessageSolidIcon],
  ["micro menu", MicroMenuIcon],
  ["minimize", MinimizeIcon],
  ["move all", MoveAllIcon],
  ["move horizontal", MoveHorizontalIcon],
  ["move vertical", MoveVerticalIcon],
  ["notification", NotificationIcon],
  ["notification solid", NotificationSolidIcon],
  ["overflow menu", OverflowMenuIcon],
  ["paste", PasteIcon],
  ["pause", PauseIcon],
  ["pause solid", PauseSolidIcon],
  ["pdf", PdfIcon],
  ["pin", PinIcon],
  ["pin solid", PinSolidIcon],
  ["pivot", PivotIcon],
  ["place in", PlaceInIcon],
  ["play", PlayIcon],
  ["play solid", PlaySolidIcon],
  ["price ladder", PriceLadderIcon],
  ["print", PrintIcon],
  ["print solid", PrintSolidIcon],
  ["redo", RedoIcon],
  ["refresh", RefreshIcon],
  ["remove", RemoveIcon],
  ["remove document", RemoveDocumentIcon],
  ["restore", RestoreIcon],
  ["run report", RunReportIcon],
  ["save", SaveIcon],
  ["save solid", SaveSolidIcon],
  ["schedule time", ScheduleTimeIcon],
  ["search", SearchIcon],
  ["send", SendIcon],
  ["settings", SettingsIcon],
  ["settings solid", SettingsSolidIcon],
  ["share", ShareIcon],
  ["share solid", ShareSolidIcon],
  ["success", SuccessIcon],
  ["success secondary", SuccessSecondaryIcon],
  ["success tick", SuccessTickIcon],
  ["sum", SumIcon],
  ["sum solid", SumSolidIcon],
  ["swap", SwapIcon],
  ["tear out", TearOutIcon],
  ["thumbs down", ThumbsDownIcon],
  ["thumbs down solid", ThumbsDownSolidIcon],
  ["thumbs up", ThumbsUpIcon],
  ["thumbs up solid", ThumbsUpSolidIcon],
  ["tree", TreeIcon],
  ["triangle down", TriangleDownIcon],
  ["triangle left", TriangleLeftIcon],
  ["triangle right", TriangleRightIcon],
  ["triangle right down", TriangleRightDownIcon],
  ["triangle up", TriangleUpIcon],
  ["undo", UndoIcon],
  ["unlinked", UnlinkedIcon],
  ["unlocked", UnlockedIcon],
  ["unlocked solid", UnlockedSolidIcon],
  ["upload", UploadIcon],
  ["user", UserIcon],
  ["user badge", UserBadgeIcon],
  ["user group", UserGroupIcon],
  ["user group solid", UserGroupSolidIcon],
  ["user solid", UserSolidIcon],
  ["visible", VisibleIcon],
  ["visible solid", VisibleSolidIcon],
  ["warning", WarningIcon],
  ["warning secondary", WarningSecondaryIcon],
  ["xls", XlsIcon]
] as const;
