import {
  AddIcon,
  AddDocumentIcon,
  AddDocumentSolidIcon,
  ApiIcon,
  AppSwitcherIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AttachIcon,
  BankCheckIcon,
  BankCheckSolidIcon,
  BarChartIcon,
  BookmarkIcon,
  BookmarkSolidIcon,
  BuildingIcon,
  BuildingsIcon,
  BuildingSolidIcon,
  BuildingsSolidIcon,
  BuildReportIcon,
  BuildReportSolidIcon,
  CalculatorIcon,
  CalculatorSolidIcon,
  CalendarIcon,
  CalendarSolidIcon,
  CallIcon,
  CallSolidIcon,
  ChatIcon,
  ChatGroupIcon,
  ChatGroupSolidIcon,
  ChatSolidIcon,
  ChattingIcon,
  ChattingSolidIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  ClockSolidIcon,
  CloneIcon,
  CloseIcon,
  ClosedcaptionIcon,
  ClosedcaptionDisabledIcon,
  ClosedcaptionSolidIcon,
  CloseSmallIcon,
  CloudIcon,
  CloudSolidIcon,
  CoffeeIcon,
  CoffeeSolidIcon,
  ColumnChooserIcon,
  ColumnChooserSolidIcon,
  CommentaryIcon,
  CommentarySolidIcon,
  CompassIcon,
  CompassSolidIcon,
  CookieIcon,
  CookieSolidIcon,
  CopyIcon,
  CopySolidIcon,
  CreditCardIcon,
  CreditCardSolidIcon,
  CsvIcon,
  CsvSolidIcon,
  CutIcon,
  DarkIcon,
  DarkSolidIcon,
  DashboardIcon,
  DashboardSolidIcon,
  DatabaseIcon,
  DatabaseSolidIcon,
  DeleteIcon,
  DeleteSolidIcon,
  DiamondIcon,
  DocumentIcon,
  DocumentSolidIcon,
  DoubleChevronDownIcon,
  DoubleChevronLeftIcon,
  DoubleChevronRightIcon,
  DoubleChevronUpIcon,
  DownloadIcon,
  EditIcon,
  EditSolidIcon,
  ErrorIcon,
  ErrorExecuteIcon,
  ErrorSolidIcon,
  ExpandIcon,
  ExportIcon,
  ExportSolidIcon,
  FavoriteIcon,
  FavoriteSolidIcon,
  FilterIcon,
  FilterClearIcon,
  FilterClearSolidIcon,
  FilterSolidIcon,
  FlagIcon,
  FlagSolidIcon,
  FolderClosedIcon,
  FolderClosedSolidIcon,
  FolderOpenIcon,
  FolderOpenSolidIcon,
  Forward10Icon,
  Forward15Icon,
  Forward30Icon,
  Forward5Icon,
  GlobeIcon,
  GlobeSolidIcon,
  GridIcon,
  GridSolidIcon,
  GuideClosedIcon,
  GuideClosedSolidIcon,
  GuideOpenIcon,
  GuideOpenSolidIcon,
  HelpIcon,
  HelpSolidIcon,
  HiddenIcon,
  HomeIcon,
  HomeSolidIcon,
  ImageIcon,
  ImageSolidIcon,
  ImportIcon,
  ImportSolidIcon,
  InboxIcon,
  InboxSolidIcon,
  InfoIcon,
  InfoSolidIcon,
  KeyIcon,
  KeySolidIcon,
  LightIcon,
  LightSolidIcon,
  LineChartIcon,
  LineChartSolidIcon,
  LinkedIcon,
  ListIcon,
  LoaderIcon,
  LocationIcon,
  LocationSolidIcon,
  LockedIcon,
  LockedSolidIcon,
  MaximizeIcon,
  MenuIcon,
  MessageIcon,
  MessageSolidIcon,
  MicroMenuIcon,
  MinimizeIcon,
  MoveAllIcon,
  MoveHorizontalIcon,
  MoveVerticalIcon,
  NoteIcon,
  NoteSolidIcon,
  NotificationIcon,
  NotificationSolidIcon,
  OverflowMenuIcon,
  PasteIcon,
  PasteSolidIcon,
  PauseIcon,
  PauseSolidIcon,
  PdfIcon,
  PdfSolidIcon,
  PinIcon,
  PinSolidIcon,
  PivotIcon,
  PivotSolidIcon,
  PlaceInIcon,
  PlayIcon,
  PlaySolidIcon,
  PresentationIcon,
  PresentationSolidIcon,
  PriceLadderIcon,
  PrintIcon,
  PrintSolidIcon,
  ProgressCancelledIcon,
  ProgressClosedIcon,
  ProgressCompleteIcon,
  ProgressDraftIcon,
  ProgressInprogressIcon,
  ProgressOnholdIcon,
  ProgressPendingIcon,
  ProgressRejectedIcon,
  ProgressTodoIcon,
  ProtectionIcon,
  ProtectionSolidIcon,
  RedoIcon,
  RefreshIcon,
  RemoveIcon,
  RemoveDocumentIcon,
  RemoveDocumentSolidIcon,
  Replay10Icon,
  Replay15Icon,
  Replay30Icon,
  Replay5Icon,
  RestoreIcon,
  RunReportIcon,
  RunReportSolidIcon,
  SaveIcon,
  SaveSolidIcon,
  ScheduleTimeIcon,
  ScheduleTimeSolidIcon,
  SearchIcon,
  SendIcon,
  SettingsIcon,
  SettingsSolidIcon,
  ShareIcon,
  ShareSolidIcon,
  SortAlphaAscendIcon,
  SortAlphaDescendIcon,
  SortNumAscendIcon,
  SortNumDescentIcon,
  StackoverflowIcon,
  StepActiveIcon,
  StepDefaultIcon,
  StepSuccessIcon,
  StorageIcon,
  StorageSolidIcon,
  SuccessIcon,
  SuccessSolidIcon,
  SuccessTickIcon,
  SumIcon,
  SumSolidIcon,
  SwapIcon,
  SymphonyIcon,
  TagIcon,
  TagClearIcon,
  TagClearSolidIcon,
  TagSolidIcon,
  TailsIcon,
  TailsSolidIcon,
  TargetIcon,
  TearOutIcon,
  ThumbsDownIcon,
  ThumbsDownSolidIcon,
  ThumbsUpIcon,
  ThumbsUpSolidIcon,
  TreeIcon,
  TreeSolidIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleRightDownIcon,
  TriangleUpIcon,
  UndoIcon,
  UnlinkedIcon,
  UnlockedIcon,
  UnlockedSolidIcon,
  UploadIcon,
  UrgencyCriticalIcon,
  UrgencyHighIcon,
  UrgencyLowIcon,
  UrgencyMediumIcon,
  UrgencyNoneIcon,
  UserIcon,
  UserAdminIcon,
  UserAdminSolidIcon,
  UserBadgeIcon,
  UserGroupIcon,
  UserGroupSolidIcon,
  UserSolidIcon,
  VideoIcon,
  VideoDisabledIcon,
  VideoSolidIcon,
  VisibleIcon,
  VisibleSolidIcon,
  VolumeDownIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  WarningIcon,
  WarningSolidIcon,
  XlsIcon,
  XlsSolidIcon,
  ZipIcon,
  ZipSolidIcon,
} from "@jpmorganchase/uitk-icons";

export const allIcons = [
  AddIcon,
  AddDocumentIcon,
  AddDocumentSolidIcon,
  ApiIcon,
  AppSwitcherIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AttachIcon,
  BankCheckIcon,
  BankCheckSolidIcon,
  BarChartIcon,
  BookmarkIcon,
  BookmarkSolidIcon,
  BuildingIcon,
  BuildingsIcon,
  BuildingSolidIcon,
  BuildingsSolidIcon,
  BuildReportIcon,
  BuildReportSolidIcon,
  CalculatorIcon,
  CalculatorSolidIcon,
  CalendarIcon,
  CalendarSolidIcon,
  CallIcon,
  CallSolidIcon,
  ChatIcon,
  ChatGroupIcon,
  ChatGroupSolidIcon,
  ChatSolidIcon,
  ChattingIcon,
  ChattingSolidIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  ClockSolidIcon,
  CloneIcon,
  CloseIcon,
  ClosedcaptionIcon,
  ClosedcaptionDisabledIcon,
  ClosedcaptionSolidIcon,
  CloseSmallIcon,
  CloudIcon,
  CloudSolidIcon,
  CoffeeIcon,
  CoffeeSolidIcon,
  ColumnChooserIcon,
  ColumnChooserSolidIcon,
  CommentaryIcon,
  CommentarySolidIcon,
  CompassIcon,
  CompassSolidIcon,
  CookieIcon,
  CookieSolidIcon,
  CopyIcon,
  CopySolidIcon,
  CreditCardIcon,
  CreditCardSolidIcon,
  CsvIcon,
  CsvSolidIcon,
  CutIcon,
  DarkIcon,
  DarkSolidIcon,
  DashboardIcon,
  DashboardSolidIcon,
  DatabaseIcon,
  DatabaseSolidIcon,
  DeleteIcon,
  DeleteSolidIcon,
  DiamondIcon,
  DocumentIcon,
  DocumentSolidIcon,
  DoubleChevronDownIcon,
  DoubleChevronLeftIcon,
  DoubleChevronRightIcon,
  DoubleChevronUpIcon,
  DownloadIcon,
  EditIcon,
  EditSolidIcon,
  ErrorIcon,
  ErrorExecuteIcon,
  ErrorSolidIcon,
  ExpandIcon,
  ExportIcon,
  ExportSolidIcon,
  FavoriteIcon,
  FavoriteSolidIcon,
  FilterIcon,
  FilterClearIcon,
  FilterClearSolidIcon,
  FilterSolidIcon,
  FlagIcon,
  FlagSolidIcon,
  FolderClosedIcon,
  FolderClosedSolidIcon,
  FolderOpenIcon,
  FolderOpenSolidIcon,
  Forward10Icon,
  Forward15Icon,
  Forward30Icon,
  Forward5Icon,
  GlobeIcon,
  GlobeSolidIcon,
  GridIcon,
  GridSolidIcon,
  GuideClosedIcon,
  GuideClosedSolidIcon,
  GuideOpenIcon,
  GuideOpenSolidIcon,
  HelpIcon,
  HelpSolidIcon,
  HiddenIcon,
  HomeIcon,
  HomeSolidIcon,
  ImageIcon,
  ImageSolidIcon,
  ImportIcon,
  ImportSolidIcon,
  InboxIcon,
  InboxSolidIcon,
  InfoIcon,
  InfoSolidIcon,
  KeyIcon,
  KeySolidIcon,
  LightIcon,
  LightSolidIcon,
  LineChartIcon,
  LineChartSolidIcon,
  LinkedIcon,
  ListIcon,
  LoaderIcon,
  LocationIcon,
  LocationSolidIcon,
  LockedIcon,
  LockedSolidIcon,
  MaximizeIcon,
  MenuIcon,
  MessageIcon,
  MessageSolidIcon,
  MicroMenuIcon,
  MinimizeIcon,
  MoveAllIcon,
  MoveHorizontalIcon,
  MoveVerticalIcon,
  NoteIcon,
  NoteSolidIcon,
  NotificationIcon,
  NotificationSolidIcon,
  OverflowMenuIcon,
  PasteIcon,
  PasteSolidIcon,
  PauseIcon,
  PauseSolidIcon,
  PdfIcon,
  PdfSolidIcon,
  PinIcon,
  PinSolidIcon,
  PivotIcon,
  PivotSolidIcon,
  PlaceInIcon,
  PlayIcon,
  PlaySolidIcon,
  PresentationIcon,
  PresentationSolidIcon,
  PriceLadderIcon,
  PrintIcon,
  PrintSolidIcon,
  ProgressCancelledIcon,
  ProgressClosedIcon,
  ProgressCompleteIcon,
  ProgressDraftIcon,
  ProgressInprogressIcon,
  ProgressOnholdIcon,
  ProgressPendingIcon,
  ProgressRejectedIcon,
  ProgressTodoIcon,
  ProtectionIcon,
  ProtectionSolidIcon,
  RedoIcon,
  RefreshIcon,
  RemoveIcon,
  RemoveDocumentIcon,
  RemoveDocumentSolidIcon,
  Replay10Icon,
  Replay15Icon,
  Replay30Icon,
  Replay5Icon,
  RestoreIcon,
  RunReportIcon,
  RunReportSolidIcon,
  SaveIcon,
  SaveSolidIcon,
  ScheduleTimeIcon,
  ScheduleTimeSolidIcon,
  SearchIcon,
  SendIcon,
  SettingsIcon,
  SettingsSolidIcon,
  ShareIcon,
  ShareSolidIcon,
  SortAlphaAscendIcon,
  SortAlphaDescendIcon,
  SortNumAscendIcon,
  SortNumDescentIcon,
  StackoverflowIcon,
  StepActiveIcon,
  StepDefaultIcon,
  StepSuccessIcon,
  StorageIcon,
  StorageSolidIcon,
  SuccessIcon,
  SuccessSolidIcon,
  SuccessTickIcon,
  SumIcon,
  SumSolidIcon,
  SwapIcon,
  SymphonyIcon,
  TagIcon,
  TagClearIcon,
  TagClearSolidIcon,
  TagSolidIcon,
  TailsIcon,
  TailsSolidIcon,
  TargetIcon,
  TearOutIcon,
  ThumbsDownIcon,
  ThumbsDownSolidIcon,
  ThumbsUpIcon,
  ThumbsUpSolidIcon,
  TreeIcon,
  TreeSolidIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleRightDownIcon,
  TriangleUpIcon,
  UndoIcon,
  UnlinkedIcon,
  UnlockedIcon,
  UnlockedSolidIcon,
  UploadIcon,
  UrgencyCriticalIcon,
  UrgencyHighIcon,
  UrgencyLowIcon,
  UrgencyMediumIcon,
  UrgencyNoneIcon,
  UserIcon,
  UserAdminIcon,
  UserAdminSolidIcon,
  UserBadgeIcon,
  UserGroupIcon,
  UserGroupSolidIcon,
  UserSolidIcon,
  VideoIcon,
  VideoDisabledIcon,
  VideoSolidIcon,
  VisibleIcon,
  VisibleSolidIcon,
  VolumeDownIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  WarningIcon,
  WarningSolidIcon,
  XlsIcon,
  XlsSolidIcon,
  ZipIcon,
  ZipSolidIcon,
];
export const allIconsNames = [
  { name: "AddIcon,", icon: AddIcon },
  { name: "AddDocumentIcon,", icon: AddDocumentIcon },
  { name: "AddDocumentSolidIcon,", icon: AddDocumentSolidIcon },
  { name: "AppSwitcherIcon,", icon: AppSwitcherIcon },
  { name: "ArrowDownIcon,", icon: ArrowDownIcon },
  { name: "ArrowLeftIcon,", icon: ArrowLeftIcon },
  { name: "ArrowRightIcon,", icon: ArrowRightIcon },
  { name: "ArrowUpIcon,", icon: ArrowUpIcon },
  { name: "AttachIcon,", icon: AttachIcon },
  { name: "BankCheckIcon,", icon: BankCheckIcon },
  { name: "BankCheckSolidIcon,", icon: BankCheckSolidIcon },
  { name: "BarChartIcon,", icon: BarChartIcon },
  { name: "BuildReportIcon,", icon: BuildReportIcon },
  { name: "CalendarIcon,", icon: CalendarIcon },
  { name: "CalendarSolidIcon,", icon: CalendarSolidIcon },
  { name: "CallIcon,", icon: CallIcon },
  { name: "CallSolidIcon,", icon: CallSolidIcon },
  { name: "ChatIcon,", icon: ChatIcon },
  { name: "ChatGroupIcon,", icon: ChatGroupIcon },
  { name: "ChatGroupSolidIcon,", icon: ChatGroupSolidIcon },
  { name: "ChatSolidIcon,", icon: ChatSolidIcon },
  { name: "ChattingIcon,", icon: ChattingIcon },
  { name: "ChattingSolidIcon,", icon: ChattingSolidIcon },
  { name: "ChevronDownIcon,", icon: ChevronDownIcon },
  { name: "ChevronLeftIcon,", icon: ChevronLeftIcon },
  { name: "ChevronRightIcon,", icon: ChevronRightIcon },
  { name: "ChevronUpIcon,", icon: ChevronUpIcon },
  { name: "ClockIcon,", icon: ClockIcon },
  { name: "ClockSolidIcon,", icon: ClockSolidIcon },
  { name: "CloneIcon,", icon: CloneIcon },
  { name: "CloseIcon,", icon: CloseIcon },
  { name: "CloseSmallIcon,", icon: CloseSmallIcon },
  { name: "ColumnChooserIcon,", icon: ColumnChooserIcon },
  { name: "ColumnChooserSolidIcon,", icon: ColumnChooserSolidIcon },
  { name: "CommentaryIcon,", icon: CommentaryIcon },
  { name: "CommentarySolidIcon,", icon: CommentarySolidIcon },
  { name: "CopyIcon,", icon: CopyIcon },
  { name: "CopySolidIcon,", icon: CopySolidIcon },
  { name: "CreditCardIcon,", icon: CreditCardIcon },
  { name: "CreditCardSolidIcon,", icon: CreditCardSolidIcon },
  { name: "CsvIcon,", icon: CsvIcon },
  { name: "CutIcon,", icon: CutIcon },
  { name: "DashboardIcon,", icon: DashboardIcon },
  { name: "DashboardSolidIcon,", icon: DashboardSolidIcon },
  { name: "DatabaseIcon,", icon: DatabaseIcon },
  { name: "DatabaseSolidIcon,", icon: DatabaseSolidIcon },
  { name: "DeleteIcon,", icon: DeleteIcon },
  { name: "DeleteSolidIcon,", icon: DeleteSolidIcon },
  { name: "DocumentIcon,", icon: DocumentIcon },
  { name: "DocumentSolidIcon,", icon: DocumentSolidIcon },
  { name: "DoubleChevronDownIcon,", icon: DoubleChevronDownIcon },
  { name: "DoubleChevronLeftIcon,", icon: DoubleChevronLeftIcon },
  { name: "DoubleChevronRightIcon,", icon: DoubleChevronRightIcon },
  { name: "DoubleChevronUpIcon,", icon: DoubleChevronUpIcon },
  { name: "DownloadIcon,", icon: DownloadIcon },
  { name: "EditIcon,", icon: EditIcon },
  { name: "EditSolidIcon,", icon: EditSolidIcon },
  { name: "ErrorIcon,", icon: ErrorIcon },
  { name: "ErrorExecuteIcon,", icon: ErrorExecuteIcon },
  { name: "ExpandIcon,", icon: ExpandIcon },
  { name: "ExportIcon,", icon: ExportIcon },
  { name: "ExportSolidIcon,", icon: ExportSolidIcon },
  { name: "FavoriteIcon,", icon: FavoriteIcon },
  { name: "FavoriteSolidIcon,", icon: FavoriteSolidIcon },
  { name: "FilterIcon,", icon: FilterIcon },
  { name: "FilterSolidIcon,", icon: FilterSolidIcon },
  { name: "FlagIcon,", icon: FlagIcon },
  { name: "FlagSolidIcon,", icon: FlagSolidIcon },
  { name: "FolderClosedIcon,", icon: FolderClosedIcon },
  { name: "FolderOpenIcon,", icon: FolderOpenIcon },
  { name: "Forward10Icon,", icon: Forward10Icon },
  { name: "Forward15Icon,", icon: Forward15Icon },
  { name: "Forward30Icon,", icon: Forward30Icon },
  { name: "Forward5Icon,", icon: Forward5Icon },
  { name: "GlobeIcon,", icon: GlobeIcon },
  { name: "GlobeSolidIcon,", icon: GlobeSolidIcon },
  { name: "GridIcon,", icon: GridIcon },
  { name: "GridSolidIcon,", icon: GridSolidIcon },
  { name: "GuideClosedIcon,", icon: GuideClosedIcon },
  { name: "GuideOpenIcon,", icon: GuideOpenIcon },
  { name: "HelpIcon,", icon: HelpIcon },
  { name: "HiddenIcon,", icon: HiddenIcon },
  { name: "HomeIcon,", icon: HomeIcon },
  { name: "HomeSolidIcon,", icon: HomeSolidIcon },
  { name: "ImportIcon,", icon: ImportIcon },
  { name: "ImportSolidIcon,", icon: ImportSolidIcon },
  { name: "InboxIcon,", icon: InboxIcon },
  { name: "InboxSolidIcon,", icon: InboxSolidIcon },
  { name: "InfoIcon,", icon: InfoIcon },
  { name: "LineChartIcon,", icon: LineChartIcon },
  { name: "LineChartSolidIcon,", icon: LineChartSolidIcon },
  { name: "LinkedIcon,", icon: LinkedIcon },
  { name: "ListIcon,", icon: ListIcon },
  { name: "LoaderIcon,", icon: LoaderIcon },
  { name: "LocationIcon,", icon: LocationIcon },
  { name: "LockedIcon,", icon: LockedIcon },
  { name: "LockedSolidIcon,", icon: LockedSolidIcon },
  { name: "MaximizeIcon,", icon: MaximizeIcon },
  { name: "MenuIcon,", icon: MenuIcon },
  { name: "MessageIcon,", icon: MessageIcon },
  { name: "MessageSolidIcon,", icon: MessageSolidIcon },
  { name: "MicroMenuIcon,", icon: MicroMenuIcon },
  { name: "MinimizeIcon,", icon: MinimizeIcon },
  { name: "MoveAllIcon,", icon: MoveAllIcon },
  { name: "MoveHorizontalIcon,", icon: MoveHorizontalIcon },
  { name: "MoveVerticalIcon,", icon: MoveVerticalIcon },
  { name: "NoteIcon,", icon: NoteIcon },
  { name: "NoteSolidIcon,", icon: NoteSolidIcon },
  { name: "NotificationIcon,", icon: NotificationIcon },
  { name: "NotificationSolidIcon,", icon: NotificationSolidIcon },
  { name: "OverflowMenuIcon,", icon: OverflowMenuIcon },
  { name: "PasteIcon,", icon: PasteIcon },
  { name: "PasteSolidIcon,", icon: PasteSolidIcon },
  { name: "PauseIcon,", icon: PauseIcon },
  { name: "PauseSolidIcon,", icon: PauseSolidIcon },
  { name: "PdfIcon,", icon: PdfIcon },
  { name: "PinIcon,", icon: PinIcon },
  { name: "PinSolidIcon,", icon: PinSolidIcon },
  { name: "PivotIcon,", icon: PivotIcon },
  { name: "PlaceInIcon,", icon: PlaceInIcon },
  { name: "PlayIcon,", icon: PlayIcon },
  { name: "PlaySolidIcon,", icon: PlaySolidIcon },
  { name: "PresentationIcon,", icon: PresentationIcon },
  { name: "PresentationSolidIcon,", icon: PresentationSolidIcon },
  { name: "PriceLadderIcon,", icon: PriceLadderIcon },
  { name: "PrintIcon,", icon: PrintIcon },
  { name: "PrintSolidIcon,", icon: PrintSolidIcon },
  { name: "ProtectionIcon,", icon: ProtectionIcon },
  { name: "ProtectionSolidIcon,", icon: ProtectionSolidIcon },
  { name: "RedoIcon,", icon: RedoIcon },
  { name: "RefreshIcon,", icon: RefreshIcon },
  { name: "RemoveIcon,", icon: RemoveIcon },
  { name: "RemoveDocumentIcon,", icon: RemoveDocumentIcon },
  { name: "RemoveDocumentSolidIcon,", icon: RemoveDocumentSolidIcon },
  { name: "Replay10Icon,", icon: Replay10Icon },
  { name: "Replay15Icon,", icon: Replay15Icon },
  { name: "Replay30Icon,", icon: Replay30Icon },
  { name: "Replay5Icon,", icon: Replay5Icon },
  { name: "RestoreIcon,", icon: RestoreIcon },
  { name: "RunReportIcon,", icon: RunReportIcon },
  { name: "SaveIcon,", icon: SaveIcon },
  { name: "SaveSolidIcon,", icon: SaveSolidIcon },
  { name: "ScheduleTimeIcon,", icon: ScheduleTimeIcon },
  { name: "SearchIcon,", icon: SearchIcon },
  { name: "SendIcon,", icon: SendIcon },
  { name: "SettingsIcon,", icon: SettingsIcon },
  { name: "SettingsSolidIcon,", icon: SettingsSolidIcon },
  { name: "ShareIcon,", icon: ShareIcon },
  { name: "ShareSolidIcon,", icon: ShareSolidIcon },
  { name: "StackoverflowIcon,", icon: StackoverflowIcon },
  { name: "StepActiveIcon,", icon: StepActiveIcon },
  { name: "StepDefaultIcon,", icon: StepDefaultIcon },
  { name: "StepSuccessIcon,", icon: StepSuccessIcon },
  { name: "StorageIcon,", icon: StorageIcon },
  { name: "StorageSolidIcon,", icon: StorageSolidIcon },
  { name: "SuccessIcon,", icon: SuccessIcon },
  { name: "SuccessTickIcon,", icon: SuccessTickIcon },
  { name: "SumIcon,", icon: SumIcon },
  { name: "SumSolidIcon,", icon: SumSolidIcon },
  { name: "SwapIcon,", icon: SwapIcon },
  { name: "SymphonyIcon,", icon: SymphonyIcon },
  { name: "TearOutIcon,", icon: TearOutIcon },
  { name: "ThumbsDownIcon,", icon: ThumbsDownIcon },
  { name: "ThumbsDownSolidIcon,", icon: ThumbsDownSolidIcon },
  { name: "ThumbsUpIcon,", icon: ThumbsUpIcon },
  { name: "ThumbsUpSolidIcon,", icon: ThumbsUpSolidIcon },
  { name: "TreeIcon,", icon: TreeIcon },
  { name: "TreeSolidIcon,", icon: TreeSolidIcon },
  { name: "TriangleDownIcon,", icon: TriangleDownIcon },
  { name: "TriangleLeftIcon,", icon: TriangleLeftIcon },
  { name: "TriangleRightIcon,", icon: TriangleRightIcon },
  { name: "TriangleRightDownIcon,", icon: TriangleRightDownIcon },
  { name: "TriangleUpIcon,", icon: TriangleUpIcon },
  { name: "UndoIcon,", icon: UndoIcon },
  { name: "UnlinkedIcon,", icon: UnlinkedIcon },
  { name: "UnlockedIcon,", icon: UnlockedIcon },
  { name: "UnlockedSolidIcon,", icon: UnlockedSolidIcon },
  { name: "UploadIcon,", icon: UploadIcon },
  { name: "UserIcon,", icon: UserIcon },
  { name: "UserAdminIcon,", icon: UserAdminIcon },
  { name: "UserAdminSolidIcon,", icon: UserAdminSolidIcon },
  { name: "UserBadgeIcon,", icon: UserBadgeIcon },
  { name: "UserGroupIcon,", icon: UserGroupIcon },
  { name: "UserGroupSolidIcon,", icon: UserGroupSolidIcon },
  { name: "UserSolidIcon,", icon: UserSolidIcon },
  { name: "VisibleIcon,", icon: VisibleIcon },
  { name: "VisibleSolidIcon,", icon: VisibleSolidIcon },
  { name: "VolumeDownIcon,", icon: VolumeDownIcon },
  { name: "VolumeOffIcon,", icon: VolumeOffIcon },
  { name: "VolumeUpIcon,", icon: VolumeUpIcon },
  { name: "WarningIcon,", icon: WarningIcon },
  { name: "XlsIcon,", icon: XlsIcon },
  { name: "ZipIcon,", icon: ZipIcon },
];
