// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type AccessibleSolidIconProps = IconProps;

export const AccessibleSolidIcon = forwardRef<
  SVGSVGElement,
  AccessibleSolidIconProps
>(function AccessibleSolidIcon(props: AccessibleSolidIconProps, ref) {
  return (
    <Icon
      data-testid="AccessibleSolidIcon"
      aria-label="accessible solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="M5.5 3a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M7 5.5V9h4l2 4h2M7 6.5h4M5 7a3.5 3.5 0 1 0 4.5 5"
        />
      </g>
    </Icon>
  );
});
