// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type AddDocumentSolidIconProps = IconProps;

export const AddDocumentSolidIcon = forwardRef<
  SVGSVGElement,
  AddDocumentSolidIconProps
>(function AddDocumentSolidIcon(props: AddDocumentSolidIconProps, ref) {
  return (
    <Icon
      data-testid="AddDocumentSolidIcon"
      aria-label="add document solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="M2.5 1.5h8l3 3v10h-11Zm8 1V4q0 .5.5.5h1.5ZM7.5 7h1v2h2v1h-2v2h-1v-2h-2V9h2Z"
        />
      </g>
    </Icon>
  );
});
