// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type AddUserIconProps = IconProps;

export const AddUserIcon = forwardRef<SVGSVGElement, AddUserIconProps>(
  function AddUserIcon(props: AddUserIconProps, ref) {
    return (
      <Icon
        data-testid="AddUserIcon"
        aria-label="add user"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M4.833 4.667a2.167 2.167 0 1 0 4.334 0 2.167 2.167 0 1 0-4.334 0ZM2.5 14v-2c0-2.167 2-3 4.5-3 1.833 0 3.333.5 4 1.5m-.5-3h4m-2-2v4"
          />
        </g>
      </Icon>
    );
  },
);
