// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type AppSwitcherIconProps = IconProps;

export const AppSwitcherIcon = forwardRef<SVGSVGElement, AppSwitcherIconProps>(
  function AppSwitcherIcon(props: AppSwitcherIconProps, ref) {
    return (
      <Icon
        data-testid="AppSwitcherIcon"
        aria-label="app switcher"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M1 1h2.545v2.545H1Zm0 5.727h2.545v2.546H1Zm0 5.728h2.545V15H1ZM6.727 1h2.546v2.545H6.727Zm0 5.727h2.546v2.546H6.727Zm0 5.728h2.546V15H6.727ZM12.455 1H15v2.545h-2.545Zm0 5.727H15v2.546h-2.545Zm0 5.728H15V15h-2.545Z"
          />
        </g>
      </Icon>
    );
  },
);
