// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ArrowRightIconProps = IconProps;

export const ArrowRightIcon = forwardRef<SVGSVGElement, ArrowRightIconProps>(
  function ArrowRightIcon(props: ArrowRightIconProps, ref) {
    return (
      <Icon
        data-testid="ArrowRightIcon"
        aria-label="arrow right"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M.25 8.667h14.452M9.248 3.213l5.454 5.454-5.454 5.453"
          />
          <path d="M13.93 7.895a1.09 1.09 0 0 1 0 1.543l.772-.771Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M13.93 7.895a1.09 1.09 0 0 1 0 1.543"
          />
          <path d="M12.84 10.529a1.09 1.09 0 0 0-.771-1.862h2.633Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M12.84 10.529a1.09 1.09 0 0 0-.771-1.862"
          />
          <path d="M12.069 8.667a1.09 1.09 0 0 0 .77-1.862l1.863 1.862Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M12.069 8.667a1.09 1.09 0 0 0 .77-1.862"
          />
          <path d="M11.542 8.667a1.309 1.309 0 0 1 .925 2.234l2.235-2.234Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M11.542 8.667a1.309 1.309 0 0 1 .925 2.234"
          />
          <path d="M11.542 8.667a1.309 1.309 0 0 0 .925-2.235l2.235 2.235Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M11.542 8.667a1.309 1.309 0 0 0 .925-2.235"
          />
        </g>
      </Icon>
    );
  },
);
