// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type BankCheckIconProps = IconProps;

export const BankCheckIcon = forwardRef<SVGSVGElement, BankCheckIconProps>(
  function BankCheckIcon(props: BankCheckIconProps, ref) {
    return (
      <Icon
        data-testid="BankCheckIcon"
        aria-label="bank check"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="M1.5 3.5h13v9h-13Z" />
            <path d="M1.5 5q0 .5.5.5h12q.5 0 .5-.5m-13 1q0-.5.5-.5h12q.5 0 .5.5M3.25 8H8m2.25 0h2.5m-9.5 2.25H11" />
          </g>
        </g>
      </Icon>
    );
  },
);
