// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type BatterySolidIconProps = IconProps;

export const BatterySolidIcon = forwardRef<
  SVGSVGElement,
  BatterySolidIconProps
>(function BatterySolidIcon(props: BatterySolidIconProps, ref) {
  return (
    <Icon
      data-testid="BatterySolidIcon"
      aria-label="battery solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M4.23 2.615h.467a1.15 1.15 0 0 0 1.15-1.148V1h4.307v.467a1.15 1.15 0 0 0 1.149 1.148h.466V15H4.231Zm1.347 1.077h4.846q.27 0 .27.27V4.5q0 .27-.27.27H5.577q-.27 0-.27-.27v-.538q0-.27.27-.27"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M4.23 2.615h.467a1.15 1.15 0 0 0 1.15-1.148V1h4.307v.467a1.15 1.15 0 0 0 1.149 1.148h.466V15H4.231Z"
        />
        <path d="M11.77 13.923A1.077 1.077 0 0 1 10.691 15h1.077Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M11.77 13.923A1.077 1.077 0 0 1 10.691 15"
        />
        <path d="M5.308 15a1.077 1.077 0 0 1-1.077-1.077V15Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M5.308 15a1.077 1.077 0 0 1-1.077-1.077"
        />
      </g>
    </Icon>
  );
});
