// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type BrowserIconProps = IconProps;

export const BrowserIcon = forwardRef<SVGSVGElement, BrowserIconProps>(
  function BrowserIcon(props: BrowserIconProps, ref) {
    return (
      <Icon
        data-testid="BrowserIcon"
        aria-label="browser"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M1.667 2.333h12.666v11.334H1.667Z"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.5 5.5h11q.833 0 .833.833v6.5q0 .834-.833.834h-11q-.833 0-.833-.834v-6.5q0-.833.833-.833Z"
          />
          <path
            fillRule="evenodd"
            d="M3 3.917a.333.333 0 1 0 .667 0 .333.333 0 1 0-.667 0m1.667 0a.333.333 0 1 0 .666 0 .333.333 0 1 0-.666 0"
          />
        </g>
      </Icon>
    );
  },
);
