// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CalculatorSolidIconProps = IconProps;

export const CalculatorSolidIcon = forwardRef<
  SVGSVGElement,
  CalculatorSolidIconProps
>(function CalculatorSolidIcon(props: CalculatorSolidIconProps, ref) {
  return (
    <Icon
      data-testid="CalculatorSolidIcon"
      aria-label="calculator solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M2.615 1h10.77v14H2.615Zm2.513 2.154h5.744q.359 0 .359.359v1.436q0 .359-.36.359H5.129q-.359 0-.359-.36V3.514q0-.36.36-.36M4.23 8h1.077v1.077H4.23Zm0 3.23h1.077v1.078H4.23ZM7.46 8h1.077v1.077H7.462Zm0 3.23h1.077v1.078H7.462ZM10.693 8h1.077v1.077h-1.077Zm0 3.23h1.077v1.078h-1.077Z"
        />
        <path d="M4.949 8a.36.36 0 0 1 .359.359V8zm.359.718a.36.36 0 0 1-.36.359h.36zm-.718.359a.36.36 0 0 1-.36-.359v.359zm-.36-.718A.36.36 0 0 1 4.59 8h-.36zm.719 2.871a.36.36 0 0 1 .359.36v-.36zm.359.719a.36.36 0 0 1-.36.359h.36zm-.718.359a.36.36 0 0 1-.36-.36v.36zm-.36-.718a.36.36 0 0 1 .36-.36h-.36zM8.18 8a.36.36 0 0 1 .358.359V8zm.358.718a.36.36 0 0 1-.358.359h.358zm-.718.359a.36.36 0 0 1-.358-.359v.359zm-.358-.718A.36.36 0 0 1 7.82 8h-.358zm.718 2.871a.36.36 0 0 1 .358.36v-.36zm.358.719a.36.36 0 0 1-.358.359h.358zm-.718.359a.36.36 0 0 1-.358-.36v.36zm-.358-.718a.36.36 0 0 1 .358-.36h-.358zM11.41 8a.36.36 0 0 1 .36.359V8zm.36.718a.36.36 0 0 1-.36.359h.36zm-.719.359a.36.36 0 0 1-.359-.359v.359zm-.359-.718a.36.36 0 0 1 .36-.359h-.36zm.718 2.871a.36.36 0 0 1 .36.36v-.36zm.36.719a.36.36 0 0 1-.36.359h.36zm-.719.359a.36.36 0 0 1-.359-.36v.36zm-.359-.718a.36.36 0 0 1 .36-.36h-.36z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M2.615 1h10.77v14H2.615Z"
        />
        <path d="M12.308 1a1.077 1.077 0 0 1 1.077 1.077V1Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M12.308 1a1.077 1.077 0 0 1 1.077 1.077"
        />
        <path d="M13.385 13.923A1.077 1.077 0 0 1 12.308 15h1.077Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M13.385 13.923A1.077 1.077 0 0 1 12.308 15"
        />
        <path d="M3.692 15a1.077 1.077 0 0 1-1.077-1.077V15Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M3.692 15a1.077 1.077 0 0 1-1.077-1.077"
        />
        <path d="M2.615 2.077A1.077 1.077 0 0 1 3.692 1H2.615Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M2.615 2.077A1.077 1.077 0 0 1 3.692 1"
        />
      </g>
    </Icon>
  );
});
