// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ChartScatterSolidIconProps = IconProps;

export const ChartScatterSolidIcon = forwardRef<
  SVGSVGElement,
  ChartScatterSolidIconProps
>(function ChartScatterSolidIcon(props: ChartScatterSolidIconProps, ref) {
  return (
    <Icon
      data-testid="ChartScatterSolidIcon"
      aria-label="chart scatter solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1 .25V15h14.75"
        />
        <path
          fillRule="evenodd"
          d="M3.364 11.029a1.324 1.324 0 1 0 2.647 0 1.324 1.324 0 1 0-2.647 0M5.35 6.49a1.324 1.324 0 1 0 2.647 0 1.324 1.324 0 1 0-2.648 0M9.32 9.327a1.324 1.324 0 1 0 2.648 0 1.324 1.324 0 1 0-2.648 0m3.404-6.807a1.324 1.324 0 1 0 2.648 0 1.324 1.324 0 1 0-2.648 0"
        />
      </g>
    </Icon>
  );
});
