// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ChartBoxPlotIconProps = IconProps;

export const ChartBoxPlotIcon = forwardRef<
  SVGSVGElement,
  ChartBoxPlotIconProps
>(function ChartBoxPlotIcon(props: ChartBoxPlotIconProps, ref) {
  return (
    <Icon
      data-testid="ChartBoxPlotIcon"
      aria-label="chart box plot"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M4.23 1v3.23m0 7.54V15M2.078 1h4.308M2.077 15h4.308M2.077 8h4.308m5.384-5.923v3.23m0 7.54V15M9.615 2.077h4.308M9.615 15h4.308M9.615 9.077h4.308M2.077 4.23h4.308v7.54H2.077Zm7.538 1.078h4.308v7.538H9.615Z"
        />
      </g>
    </Icon>
  );
});
