// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ChattingSolidIconProps = IconProps;

export const ChattingSolidIcon = forwardRef<
  SVGSVGElement,
  ChattingSolidIconProps
>(function ChattingSolidIcon(props: ChattingSolidIconProps, ref) {
  return (
    <Icon
      data-testid="ChattingSolidIcon"
      aria-label="chatting solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="M2 2.5h12v9H6L3 14v-2.5H2ZM4.333 7a.667.667 0 1 0 1.334 0 .667.667 0 1 0-1.334 0m3 0a.667.667 0 1 0 1.334 0 .667.667 0 1 0-1.334 0m3 0a.667.667 0 1 0 1.334 0 .667.667 0 1 0-1.334 0"
        />
      </g>
    </Icon>
  );
});
