// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ChatSolidIconProps = IconProps;

export const ChatSolidIcon = forwardRef<SVGSVGElement, ChatSolidIconProps>(
  function ChatSolidIcon(props: ChatSolidIconProps, ref) {
    return (
      <Icon
        data-testid="ChatSolidIcon"
        aria-label="chat solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path fillRule="evenodd" d="M2 2.5h12v9H6L3 14v-2.5H2Z" />
        </g>
      </Icon>
    );
  },
);
