// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ChevronRightIconProps = IconProps;

export const ChevronRightIcon = forwardRef<
  SVGSVGElement,
  ChevronRightIconProps
>(function ChevronRightIcon(props: ChevronRightIconProps, ref) {
  return (
    <Icon
      data-testid="ChevronRightIcon"
      aria-label="chevron right"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M8.593 5.618 9 6l-.407.382L3.661 11 3 10.236 7.524 6 3 1.764 3.66 1l4.933 4.618Z" />
    </Icon>
  );
});
