// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ClockIconProps = IconProps;

export const ClockIcon = forwardRef<SVGSVGElement, ClockIconProps>(
  function ClockIcon(props: ClockIconProps, ref) {
    return (
      <Icon
        data-testid="ClockIcon"
        aria-label="clock"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="M1 8a7 7 0 1 0 14 0A7 7 0 1 0 1 8Z" />
            <path d="M8 3.154V8l3.23 2.154" />
          </g>
        </g>
      </Icon>
    );
  },
);
