// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ClosedcaptionDisabledIconProps = IconProps;

export const ClosedcaptionDisabledIcon = forwardRef<
  SVGSVGElement,
  ClosedcaptionDisabledIconProps
>(function ClosedcaptionDisabledIcon(
  props: ClosedcaptionDisabledIconProps,
  ref,
) {
  return (
    <Icon
      data-testid="ClosedcaptionDisabledIcon"
      aria-label="closedcaption disabled"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M6.385 3.154H15v8.615m-5.385 1.077H1V4.231"
        />
        <path
          fillRule="evenodd"
          d="m3.692 5.596.827.827q-.288.106-.288.5v2.154q0 .538.538.538h2.154v1.077H4.77q-1.615 0-1.615-1.615V6.923q0-.933.538-1.327m9.154-.288v1.077h-2.154q-.538 0-.538.538V8.25L9.077 7.173v-.25q0-1.615 1.615-1.615Zm-.25 5.384L11.52 9.615h1.327v1.077z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="m1.538 1.538 12.924 12.924"
        />
      </g>
    </Icon>
  );
});
