// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CloseSmallIconProps = IconProps;

export const CloseSmallIcon = forwardRef<SVGSVGElement, CloseSmallIconProps>(
  function CloseSmallIcon(props: CloseSmallIconProps, ref) {
    return (
      <Icon
        data-testid="CloseSmallIcon"
        aria-label="close small"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="m.768.768 14.464 14.464m0-14.464L.768 15.232"
          />
        </g>
      </Icon>
    );
  },
);
