// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ClosedcaptionIconProps = IconProps;

export const ClosedcaptionIcon = forwardRef<
  SVGSVGElement,
  ClosedcaptionIconProps
>(function ClosedcaptionIcon(props: ClosedcaptionIconProps, ref) {
  return (
    <Icon
      data-testid="ClosedcaptionIcon"
      aria-label="closedcaption"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M4.306 8q-.555 0-.961-.213a1.43 1.43 0 0 1-.626-.651Q2.5 6.697 2.5 6.02q0-.705.24-1.15.24-.446.665-.658A2.2 2.2 0 0 1 4.383 4q.35 0 .633.07.286.066.484.163l-.247.656a4 4 0 0 0-.442-.147q-.226-.06-.435-.06-.342 0-.572.15a.9.9 0 0 0-.34.447q-.109.296-.109.735a2 2 0 0 0 .113.718.9.9 0 0 0 .336.439 1 1 0 0 0 .548.146q.321 0 .576-.077.255-.076.48-.198v.71a1.8 1.8 0 0 1-.477.185Q4.676 8 4.306 8m4 0q-.555 0-.961-.213a1.43 1.43 0 0 1-.626-.651Q6.5 6.697 6.5 6.02q0-.705.24-1.15.24-.446.665-.658A2.2 2.2 0 0 1 8.383 4q.35 0 .633.07.286.066.484.163l-.247.656a4 4 0 0 0-.442-.147q-.226-.06-.435-.06-.342 0-.572.15a.9.9 0 0 0-.34.447q-.108.296-.109.735a2 2 0 0 0 .113.718.9.9 0 0 0 .336.439 1 1 0 0 0 .548.146q.321 0 .576-.077.255-.076.48-.198v.71a1.8 1.8 0 0 1-.477.185Q8.676 8 8.306 8" />
      <path
        fillRule="evenodd"
        d="M0 11V1h12v10zm1-9h10v8H1z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
