// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CloseIconProps = IconProps;

export const CloseIcon = forwardRef<SVGSVGElement, CloseIconProps>(
  function CloseIcon(props: CloseIconProps, ref) {
    return (
      <Icon
        data-testid="CloseIcon"
        aria-label="close"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="m3 3 10 10m0-10L3 13"
          />
        </g>
      </Icon>
    );
  },
);
