// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ClosedcaptionIconProps = IconProps;

export const ClosedcaptionIcon = forwardRef<
  SVGSVGElement,
  ClosedcaptionIconProps
>(function ClosedcaptionIcon(props: ClosedcaptionIconProps, ref) {
  return (
    <Icon
      data-testid="ClosedcaptionIcon"
      aria-label="closedcaption"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1 3.154h14v9.692H1Z"
        />
        <path
          fillRule="evenodd"
          d="M5.127 6.076q-.385 0-.688.13-.298.129-.506.37-.212.247-.327.6-.117.362-.117.82 0 .609.187 1.05.179.42.532.649t.902.229q.326 0 .613-.055.294-.056.573-.141l.255-.078v.925l-.128.048q-.3.113-.63.167-.325.054-.768.054-.842 0-1.416-.356-.579-.358-.866-1.01-.28-.633-.28-1.485 0-.617.175-1.133.177-.522.519-.905.345-.386.846-.595.496-.207 1.131-.207.412 0 .796.082.387.082.701.238l.174.086-.406.859-.177-.081q-.233-.107-.512-.185-.268-.076-.583-.076m6.857 0q-.386 0-.689.13-.298.129-.506.37-.212.247-.326.6-.118.362-.118.82 0 .609.187 1.05.18.42.532.649.354.229.902.229.327 0 .613-.055.295-.056.573-.141l.255-.078v.925l-.128.048q-.3.113-.629.167-.326.054-.768.054-.842 0-1.417-.356-.579-.358-.866-1.01-.28-.633-.28-1.485 0-.617.175-1.133.177-.522.52-.905.344-.386.845-.595.497-.207 1.132-.207.412 0 .795.082.387.082.702.238l.173.086-.405.859-.178-.081q-.232-.107-.512-.185-.268-.076-.582-.076"
        />
      </g>
    </Icon>
  );
});
