// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ClosedcaptionDisabledSolidIconProps = IconProps;

export const ClosedcaptionDisabledSolidIcon = forwardRef<
  SVGSVGElement,
  ClosedcaptionDisabledSolidIconProps
>(function ClosedcaptionDisabledSolidIcon(
  props: ClosedcaptionDisabledSolidIconProps,
  ref,
) {
  return (
    <Icon
      data-testid="ClosedcaptionDisabledSolidIcon"
      aria-label="closedcaption disabled solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M3.82 2.397h11.94v11.206h-.734Zm-3.58 0h.734L12.18 13.603H.24Zm3.713 2.98q-.472.207-.802.575-.343.383-.52.907-.174.516-.174 1.134 0 .853.28 1.487.287.653.866 1.011.576.356 1.419.356.443 0 .769-.054.33-.054.63-.167l.128-.048v-.926l-.255.078q-.28.085-.574.141-.287.055-.614.055-.548 0-.903-.23-.353-.228-.532-.65-.188-.44-.188-1.05 0-.459.118-.82.115-.354.327-.601.208-.242.507-.37.123-.054.261-.086zm8.307 5.46q.216-.014.396-.044.33-.054.63-.167l.128-.048v-.926l-.255.078q-.28.085-.574.141-.287.055-.614.055-.459 0-.782-.16zM10.595 9.17q-.032-.06-.06-.125-.187-.44-.187-1.05 0-.459.118-.82.114-.354.327-.601.208-.242.507-.37.303-.131.689-.131.315 0 .583.075.28.08.513.186l.177.08.407-.86-.175-.085q-.314-.156-.702-.239-.384-.082-.796-.082-.636 0-1.133.208-.502.21-.847.595-.343.383-.52.907-.161.477-.174 1.04z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="m1.53 1.53 12.94 12.94"
        />
      </g>
    </Icon>
  );
});
