// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CloudSyncSolidIconProps = IconProps;

export const CloudSyncSolidIcon = forwardRef<
  SVGSVGElement,
  CloudSyncSolidIconProps
>(function CloudSyncSolidIcon(props: CloudSyncSolidIconProps, ref) {
  return (
    <Icon
      data-testid="CloudSyncSolidIcon"
      aria-label="cloud sync solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M4.563 10.102q-1.568 0-2.676-1.11T.777 6.317q0-3.133 3.008-3.707Q5.2.24 8 .24q3.738 0 4.726 3.514 2.496.495 2.496 3.136 0 3.213-3.213 3.213H8.35q0-.045-.007-.089h2.261q.071 0 .14-.014t.135-.04.125-.067.108-.09.09-.108.066-.124.041-.135.014-.14V8.128q0-.07-.014-.14t-.04-.135-.067-.124-.09-.109-.108-.09-.125-.066-.134-.04-.14-.014H8.341q.012-.084.005-.168t-.033-.165-.07-.152-.105-.132l-.824-.825q-.05-.05-.11-.089-.058-.04-.124-.066t-.134-.041-.14-.014-.14.014-.135.04-.125.067-.109.09L4.064 8.202q-.05.05-.09.11-.04.058-.066.123t-.041.135-.014.14.014.14.04.135.067.124.09.11l.882.882z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M10.603 8.711H5.397M7.219 6.89 5.397 8.71l1.822 1.823m-1.822 2.864h5.206m-1.822-1.823 1.822 1.823-1.822 1.822"
        />
      </g>
    </Icon>
  );
});
