// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CloudUploadIconProps = IconProps;

export const CloudUploadIcon = forwardRef<SVGSVGElement, CloudUploadIconProps>(
  function CloudUploadIcon(props: CloudUploadIconProps, ref) {
    return (
      <Icon
        data-testid="CloudUploadIcon"
        aria-label="cloud upload"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="M4.497 11.975a3.503 3.503 0 0 1-.57-6.961 4.673 4.673 0 0 1 8.605 1.156 2.92 2.92 0 0 1-.445 5.805h-1.964m-4.246 0h-1.38" />
            <path d="M8 14.098V6.666m-2.389 2.39L8 6.665l2.389 2.39" />
          </g>
        </g>
      </Icon>
    );
  },
);
