// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CloudDisabledSolidIconProps = IconProps;

export const CloudDisabledSolidIcon = forwardRef<
  SVGSVGElement,
  CloudDisabledSolidIconProps
>(function CloudDisabledSolidIcon(props: CloudDisabledSolidIconProps, ref) {
  return (
    <Icon
      data-testid="CloudDisabledSolidIcon"
      aria-label="cloud disabled solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M4.314 13.122q-1.683 0-2.872-1.19t-1.19-2.87q0-3.2 2.924-3.912l7.971 7.972Zm10.216-.567L5.233 3.258Q6.408 2.543 8 2.543q4.01 0 5.07 3.769 2.677.53 2.677 3.364 0 2.048-1.217 2.879"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="m1.297 1.297 13.406 13.406"
        />
      </g>
    </Icon>
  );
});
