// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CloudIconProps = IconProps;

export const CloudIcon = forwardRef<SVGSVGElement, CloudIconProps>(
  function CloudIcon(props: CloudIconProps, ref) {
    return (
      <Icon
        data-testid="CloudIcon"
        aria-label="cloud"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M4.7 12.25a3.3 3.3 0 0 1-.536-6.557 4.402 4.402 0 0 1 8.106 1.089 2.75 2.75 0 0 1-.42 5.468z"
          />
        </g>
      </Icon>
    );
  },
);
