// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, IconProps } from "../icon";

export type CloudSyncSolidIconProps = IconProps;

export const CloudSyncSolidIcon = forwardRef<
  SVGSVGElement,
  CloudSyncSolidIconProps
>(function CloudSyncSolidIcon(props: CloudSyncSolidIconProps, ref) {
  return (
    <Icon
      data-testid="CloudSyncSolidIcon"
      aria-label="cloud sync solid"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M3 10a3 3 0 0 1-.487-5.96 4.002 4.002 0 0 1 7.369.99 2.5 2.5 0 0 1 1.343 4.28L7.537 5.62h-1.38L4.12 3.586.586 7.12 3.464 10H3Z" />
      <path d="m4.121 9.243.707-.707-.914-.915H7v-1H3.914l.914-.914L4.121 5 2 7.121l2.121 2.122Zm3.758-1.866-.707.707.914.915H5v1h3.086l-.914.914.707.707L10 9.499 7.879 7.377Z" />
    </Icon>
  );
});
