// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CloudIconProps = IconProps;

export const CloudIcon = forwardRef<SVGSVGElement, CloudIconProps>(
  function CloudIcon(props: CloudIconProps, ref) {
    return (
      <Icon
        data-testid="CloudIcon"
        aria-label="cloud"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M4.497 12.661a3.503 3.503 0 0 1-.57-6.96 4.673 4.673 0 0 1 8.605 1.156 2.92 2.92 0 0 1-.445 5.804z"
          />
        </g>
      </Icon>
    );
  },
);
