// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CloudDownloadSolidIconProps = IconProps;

export const CloudDownloadSolidIcon = forwardRef<
  SVGSVGElement,
  CloudDownloadSolidIconProps
>(function CloudDownloadSolidIcon(props: CloudDownloadSolidIconProps, ref) {
  return (
    <Icon
      data-testid="CloudDownloadSolidIcon"
      aria-label="cloud download solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M4.497 11.241q-1.762 0-3.008-1.246T.243 6.988q0-3.326 3.015-4.085a.53.53 0 0 0 .31-.217Q5.118.399 8 .399q3.985 0 5.127 3.633a7 7 0 0 0-.084-.253.53.53 0 0 0 .347.33q2.367.714 2.367 3.463 0 3.67-3.67 3.67h-2.87V6.51q0-.037-.004-.073-.004-.037-.01-.073t-.019-.072-.024-.07-.032-.066-.038-.063-.044-.059-.049-.054-.055-.05-.059-.044-.063-.037-.066-.032-.07-.025-.071-.018-.073-.01q-.036-.004-.073-.004h-.934q-.037 0-.073.004-.037.003-.073.01t-.071.018-.07.025-.066.032-.063.037-.06.044-.054.05-.05.054-.043.06-.038.062-.032.067-.024.07-.018.07-.011.074-.004.073v4.731Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.8)"
          d="M8 6.51v8.227m-2.123-2.123L8 14.737l2.123-2.123"
        />
        <path d="M7.4 14.137a.85.85 0 0 0 1.2 0l-.6.6Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.8)"
          d="M7.4 14.137a.85.85 0 0 0 1.2 0"
        />
        <path d="M6.938 13.676A.622.622 0 0 0 8 13.236v1.501Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.8)"
          d="M6.938 13.676A.622.622 0 0 0 8 13.236"
        />
        <path d="M8 13.236a.622.622 0 0 0 1.062.44L8 14.737Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.8)"
          d="M8 13.236a.622.622 0 0 0 1.062.44"
        />
        <path d="M8 12.738a.828.828 0 0 1-1.414.586L8 14.737Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.8)"
          d="M8 12.738a.828.828 0 0 1-1.414.586"
        />
        <path d="M8 12.738a.828.828 0 0 0 1.414.586L8 14.737Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.8)"
          d="M8 12.738a.828.828 0 0 0 1.414.586"
        />
      </g>
    </Icon>
  );
});
