// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CoffeeSolidIconProps = IconProps;

export const CoffeeSolidIcon = forwardRef<SVGSVGElement, CoffeeSolidIconProps>(
  function CoffeeSolidIcon(props: CoffeeSolidIconProps, ref) {
    return (
      <Icon
        data-testid="CoffeeSolidIcon"
        aria-label="coffee solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M1.343 4.894h9.287v5.462q0 2.186-2.186 2.186H3.528q-2.185 0-2.185-2.186Z"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M10.63 5.44h2.185a2.185 2.185 0 0 1 0 4.37H10.63M.25 14.727h12.565M3.528.523v2.185M7.898.523v2.185"
          />
        </g>
      </Icon>
    );
  },
);
