// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CollapseIconProps = IconProps;

export const CollapseIcon = forwardRef<SVGSVGElement, CollapseIconProps>(
  function CollapseIcon(props: CollapseIconProps, ref) {
    return (
      <Icon
        data-testid="CollapseIcon"
        aria-label="collapse"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="m.775.775 4.817 4.817m-4.817 0h4.817V.775m9.633 0-4.817 4.817m0-4.817v4.817h4.817M.775 15.225l4.817-4.817m-4.817 0h4.817v4.817m9.633 0-4.817-4.817m0 4.817v-4.817h4.817"
          />
        </g>
      </Icon>
    );
  },
);
