// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ColumnChooserSolidIconProps = IconProps;

export const ColumnChooserSolidIcon = forwardRef<
  SVGSVGElement,
  ColumnChooserSolidIconProps
>(function ColumnChooserSolidIcon(props: ColumnChooserSolidIconProps, ref) {
  return (
    <Icon
      data-testid="ColumnChooserSolidIcon"
      aria-label="column chooser solid"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M0 12V0h12v12zM1 2h10v1H6v1h3v1H6v1h3v1H6v1h3v1H6v2H5V3H1zm0 2h3v1H1zm3 2H1v1h3zm0 2H1v1h3z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
