// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CommentarySolidIconProps = IconProps;

export const CommentarySolidIcon = forwardRef<
  SVGSVGElement,
  CommentarySolidIconProps
>(function CommentarySolidIcon(props: CommentarySolidIconProps, ref) {
  return (
    <Icon
      data-testid="CommentarySolidIcon"
      aria-label="commentary solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M.25.573h15.5v11.625H5.417l-3.875 3.23v-3.23H.25Zm3.23 2.583h9.04v1.292H3.48Zm0 2.584h9.04v1.29H3.48Zm0 2.583h5.812v1.292H3.479Z"
        />
      </g>
    </Icon>
  );
});
