// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CompassIconProps = IconProps;

export const CompassIcon = forwardRef<SVGSVGElement, CompassIconProps>(
  function CompassIcon(props: CompassIconProps, ref) {
    return (
      <Icon
        data-testid="CompassIcon"
        aria-label="compass"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="M1.5 8a6.5 6.5 0 1 0 13 0 6.5 6.5 0 1 0-13 0Z" />
            <path d="m10.5 5.5-1 4-4 1 1-4Z" />
          </g>
        </g>
      </Icon>
    );
  },
);
