// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CropsSolidIconProps = IconProps;

export const CropsSolidIcon = forwardRef<SVGSVGElement, CropsSolidIconProps>(
  function CropsSolidIcon(props: CropsSolidIconProps, ref) {
    return (
      <Icon
        data-testid="CropsSolidIcon"
        aria-label="crops solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M8.287 7.139c-3.444 0-5.167-1.722-5.167-4.593 3.445 0 5.167 1.723 5.167 4.593m0 4.592c-3.444 0-5.167-1.722-5.167-4.592 3.445 0 5.167 1.722 5.167 4.592m0-6.888c0-3.445 1.722-4.593 3.444-4.593 0 2.87-1.148 4.593-3.444 4.593m0 4.592c0-3.444 1.722-4.592 4.593-4.592 0 2.87-1.723 4.592-4.593 4.592m0 4.593c0-3.445 1.722-4.593 4.593-4.593 0 2.87-1.723 4.593-4.593 4.593"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M8.287 1.398V15.75"
          />
        </g>
      </Icon>
    );
  },
);
