// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type CurrencyExchangeIconProps = IconProps;

export const CurrencyExchangeIcon = forwardRef<
  SVGSVGElement,
  CurrencyExchangeIconProps
>(function CurrencyExchangeIcon(props: CurrencyExchangeIconProps, ref) {
  return (
    <Icon
      data-testid="CurrencyExchangeIcon"
      aria-label="currency exchange"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M7.296 1.172A5 5 0 0 0 1 6.002H0a6 6 0 0 1 11.002-3.317V1.5h1v3H9v-1h1.332A5.028 5.028 0 0 0 9.12 2.093a4.981 4.981 0 0 0-1.825-.92Zm-2.59 9.659A5 5 0 0 0 11 6.001h1A6 6 0 0 1 1 9.319l.001 1.183H0v-3h3v1H1.67a5.03 5.03 0 0 0 1.21 1.41 4.98 4.98 0 0 0 1.826.92Z" />
      <path d="M6.548 3.142c.452.063.86.183 1.113.269l-.32.948c-.357-.12-.947-.282-1.458-.256-.251.013-.442.07-.572.16a.642.642 0 0 0-.253.378l-.022.091c-.033.17-.016.26 0 .306a.274.274 0 0 0 .109.129c.163.118.435.194.856.295.367.087.86.197 1.247.434.205.126.4.297.54.534.142.24.212.52.212.83 0 .528-.217.94-.588 1.208-.256.186-.56.285-.864.334v.896H5.55v-.875A6.144 6.144 0 0 1 4 8.477l.354-.934c.446.17 1.204.337 1.822.297.31-.021.525-.09.651-.182.099-.071.175-.175.175-.398a.611.611 0 0 0-.072-.319.572.572 0 0 0-.202-.192c-.224-.137-.541-.215-.958-.315-.364-.087-.854-.199-1.21-.456a1.27 1.27 0 0 1-.461-.597c-.095-.26-.1-.545-.041-.843l.043-.179c.116-.403.34-.712.646-.922.249-.17.529-.262.803-.304V2.3h.998v.841Z" />
    </Icon>
  );
});
