// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DarkSolidIconProps = IconProps;

export const DarkSolidIcon = forwardRef<SVGSVGElement, DarkSolidIconProps>(
  function DarkSolidIcon(props: DarkSolidIconProps, ref) {
    return (
      <Icon
        data-testid="DarkSolidIcon"
        aria-label="dark solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M7.087 1.226a6.94 6.94 0 1 0 6.89 10.815 7.65 7.65 0 0 1-6.89-10.815"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M7.087 1.226a6.94 6.94 0 1 0 6.89 10.815 7.65 7.65 0 0 1-6.89-10.815Z"
          />
          <path d="M12.967 13.189a.747.747 0 0 0-.362-1.286 7.7 7.7 0 0 0 1.372.138 7 7 0 0 1-1.01 1.148" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M12.967 13.189a.747.747 0 0 0-.362-1.286"
          />
          <path d="M6.633 2.527a.747.747 0 0 0-1.013-.871 7 7 0 0 1 1.467-.43 7.7 7.7 0 0 0-.454 1.302" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M6.633 2.527a.747.747 0 0 0-1.013-.871"
          />
        </g>
      </Icon>
    );
  },
);
