// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DatasetManagerIconProps = IconProps;

export const DatasetManagerIcon = forwardRef<
  SVGSVGElement,
  DatasetManagerIconProps
>(function DatasetManagerIcon(props: DatasetManagerIconProps, ref) {
  return (
    <Icon
      data-testid="DatasetManagerIcon"
      aria-label="dataset manager"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.5 3.5c0-2.667 11-2.667 11 0a.95.95 0 0 1-.11.443M6.893 5.5C4.18 5.483 1.5 4.816 1.5 3.5m0 0V11q0 2.236 3 2.472M1.5 7.5q0 2 3.5 2h1.626M8.25 7.75a2.25 2.25 0 1 0 4.5 0 2.25 2.25 0 1 0-4.5 0ZM6.5 15v-1.5q0-1.5 4-1.5t4 1.5V15Z"
        />
      </g>
    </Icon>
  );
});
