// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, IconProps } from "../icon";

export type DatabaseSolidIconProps = IconProps;

export const DatabaseSolidIcon = forwardRef<
  SVGSVGElement,
  DatabaseSolidIconProps
>(function DatabaseSolidIcon(props: DatabaseSolidIconProps, ref) {
  return (
    <Icon
      data-testid="DatabaseSolidIcon"
      aria-label="database solid"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M0 5.5V0h12v5.5H0Zm2-3.25h1v1H2v-1Zm2 0h1v1H4v-1ZM0 12V6.5h12V12H0Zm2-3.25h1v1H2v-1Zm2 0h1v1H4v-1Z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
