// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DatabaseSolidIconProps = IconProps;

export const DatabaseSolidIcon = forwardRef<
  SVGSVGElement,
  DatabaseSolidIconProps
>(function DatabaseSolidIcon(props: DatabaseSolidIconProps, ref) {
  return (
    <Icon
      data-testid="DatabaseSolidIcon"
      aria-label="database solid"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M0 5.5V0h12v5.5zm2-3.25h1v1H2zm2 0h1v1H4zM0 12V6.5h12V12zm2-3.25h1v1H2zm2 0h1v1H4z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
