// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DevicesSolidIconProps = IconProps;

export const DevicesSolidIcon = forwardRef<
  SVGSVGElement,
  DevicesSolidIconProps
>(function DevicesSolidIcon(props: DevicesSolidIconProps, ref) {
  return (
    <Icon
      data-testid="DevicesSolidIcon"
      aria-label="devices solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="M1.167 2h11.666v2.417h-1.666c-.216 0-.446.025-.687.106a1.8 1.8 0 0 0-.697.427c-.203.202-.347.455-.427.696s-.106.472-.106.687V11H1.167Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M7 11v2.667m-2.25 0h4.5"
        />
        <path
          fillRule="evenodd"
          d="M10.5 7.667h4v6q0 .666-.667.666h-2.666q-.667 0-.667-.666ZM12 12.5a.5.5 0 1 0 1 0 .5.5 0 1 0-1 0"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M11.167 5.667h2.666q.667 0 .667.666v7.334q0 .666-.667.666h-2.666q-.667 0-.667-.666V6.333q0-.666.667-.666Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M10.5 7.167q0 .5.5.5h3q.5 0 .5-.5m-4 1q0-.5.5-.5h3q.5 0 .5.5"
        />
      </g>
    </Icon>
  );
});
