// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DisplayIconProps = IconProps;

export const DisplayIcon = forwardRef<SVGSVGElement, DisplayIconProps>(
  function DisplayIcon(props: DisplayIconProps, ref) {
    return (
      <Icon
        data-testid="DisplayIcon"
        aria-label="display"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path
          fillRule="evenodd"
          d="M0 9h5v2H3v1h6v-1H7V9h5V0H0zm11-8H1v7h10z"
          clipRule="evenodd"
        />
      </Icon>
    );
  },
);
