// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DisplaySolidIconProps = IconProps;

export const DisplaySolidIcon = forwardRef<
  SVGSVGElement,
  DisplaySolidIconProps
>(function DisplaySolidIcon(props: DisplaySolidIconProps, ref) {
  return (
    <Icon
      data-testid="DisplaySolidIcon"
      aria-label="display solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path fillRule="evenodd" d="M1.333 2h13.334v10H1.333Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M2.667 14h10.666M2.667 14h4Q7 14 7 13.667V12q0-.333-.333-.333m2.666 0Q9 11.667 9 12v1.667Q9 14 9.333 14h4"
        />
      </g>
    </Icon>
  );
});
