// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DivideIconProps = IconProps;

export const DivideIcon = forwardRef<SVGSVGElement, DivideIconProps>(
  function DivideIcon(props: DivideIconProps, ref) {
    return (
      <Icon
        data-testid="DivideIcon"
        aria-label="divide"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.5 8h11"
          />
          <path
            fillRule="evenodd"
            d="M7 3.5a1 1 0 1 0 2 0 1 1 0 1 0-2 0m0 9a1 1 0 1 0 2 0 1 1 0 1 0-2 0"
          />
        </g>
      </Icon>
    );
  },
);
