// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DocumentEditIconProps = IconProps;

export const DocumentEditIcon = forwardRef<
  SVGSVGElement,
  DocumentEditIconProps
>(function DocumentEditIcon(props: DocumentEditIconProps, ref) {
  return (
    <Icon
      data-testid="DocumentEditIcon"
      aria-label="document edit"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M8.156 1H2v10h5V8h3V5h1v5l-2 2H1V0h7.156zM8 11h.586L10 9.586V9H8z"
        clipRule="evenodd"
      />
      <path d="m10.94 2.475-3.89 3.89-2.121.706.707-2.122 3.888-3.888zM10.232.354a.5.5 0 0 1 .708 0l.707.707a.5.5 0 0 1 0 .707l-.354.353L9.879.707z" />
    </Icon>
  );
});
