// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DocumentIconProps = IconProps;

export const DocumentIcon = forwardRef<SVGSVGElement, DocumentIconProps>(
  function DocumentIcon(props: DocumentIconProps, ref) {
    return (
      <Icon
        data-testid="DocumentIcon"
        aria-label="document"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path
          fillRule="evenodd"
          d="M1 12V0h8l2 2v10zm9-1V4H7V1H2v10zm0-8.586V3H8V1h.586z"
          clipRule="evenodd"
        />
      </Icon>
    );
  },
);
