// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DocumentSearchIconProps = IconProps;

export const DocumentSearchIcon = forwardRef<
  SVGSVGElement,
  DocumentSearchIconProps
>(function DocumentSearchIcon(props: DocumentSearchIconProps, ref) {
  return (
    <Icon
      data-testid="DocumentSearchIcon"
      aria-label="document search"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <g
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
        >
          <path d="M7.761 14.5H2.5v-13h8l3 3v2.394m-3-5.394V4q0 .5.5.5h2.5M5 6.5h2m-2 3h1" />
          <path d="M7.5 10.5a3 3 0 1 0 6 0 3 3 0 1 0-6 0Zm5.12 2.12L15 15" />
        </g>
      </g>
    </Icon>
  );
});
