// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type DoubleChevronDownIconProps = IconProps;

export const DoubleChevronDownIcon = forwardRef<
  SVGSVGElement,
  DoubleChevronDownIconProps
>(function DoubleChevronDownIcon(props: DoubleChevronDownIconProps, ref) {
  return (
    <Icon
      data-testid="DoubleChevronDownIcon"
      aria-label="double chevron down"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M.755.782 8 8.027 15.245.782M.755 7.447 8 14.692l7.245-7.245"
        />
      </g>
    </Icon>
  );
});
