// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type EditSolidIconProps = IconProps;

export const EditSolidIcon = forwardRef<SVGSVGElement, EditSolidIconProps>(
  function EditSolidIcon(props: EditSolidIconProps, ref) {
    return (
      <Icon
        data-testid="EditSolidIcon"
        aria-label="edit solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="m1.453 11.025 8.66-8.661 3.523 3.522-8.66 8.661Zm-.64 1.352 2.81 2.81-3.373.563Zm10.287-11L12.227.25l3.523 3.523L14.623 4.9Z"
          />
        </g>
      </Icon>
    );
  },
);
