// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type EqualIconProps = IconProps;

export const EqualIcon = forwardRef<SVGSVGElement, EqualIconProps>(
  function EqualIcon(props: EqualIconProps, ref) {
    return (
      <Icon
        data-testid="EqualIcon"
        aria-label="equal"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M10 8H2V7h8zm0-3H2V4h8z" />
      </Icon>
    );
  },
);
