// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ErrorSolidIconProps = IconProps;

export const ErrorSolidIcon = forwardRef<SVGSVGElement, ErrorSolidIconProps>(
  function ErrorSolidIcon(props: ErrorSolidIconProps, ref) {
    return (
      <Icon
        data-testid="ErrorSolidIcon"
        aria-label="error solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M4.865.268h6.27l4.597 4.597v6.27l-4.597 4.597h-6.27L.268 11.135v-6.27ZM7 4.625h2v3.75H7Zm0 5.75a1 1 0 1 0 2 0 1 1 0 1 0-2 0"
          />
        </g>
      </Icon>
    );
  },
);
