// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ExpandIconProps = IconProps;

export const ExpandIcon = forwardRef<SVGSVGElement, ExpandIconProps>(
  function ExpandIcon(props: ExpandIconProps, ref) {
    return (
      <Icon
        data-testid="ExpandIcon"
        aria-label="expand"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M1 5.455V1h4.455M1 1l5.09 5.09M10.546 1H15v4.455M15 1 9.91 6.09M15 10.546V15h-4.455M15 15 9.91 9.91M5.454 15H1v-4.455M1 15l5.09-5.09"
          />
        </g>
      </Icon>
    );
  },
);
