// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ExpandAllHorizontalIconProps = IconProps;

export const ExpandAllHorizontalIcon = forwardRef<
  SVGSVGElement,
  ExpandAllHorizontalIconProps
>(function ExpandAllHorizontalIcon(props: ExpandAllHorizontalIconProps, ref) {
  return (
    <Icon
      data-testid="ExpandAllHorizontalIcon"
      aria-label="expand all horizontal"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="m0 6 4 4 1-1-3-3 3-3-1-1zm12 0-4 4-1-1 3-3-3-3 1-1z" />
    </Icon>
  );
});
