// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ExportIconProps = IconProps;

export const ExportIcon = forwardRef<SVGSVGElement, ExportIconProps>(
  function ExportIcon(props: ExportIconProps, ref) {
    return (
      <Icon
        data-testid="ExportIcon"
        aria-label="export"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M6 2.5H2.5v11H6M5 8h9.5M11 4.5 14.5 8 11 11.5"
          />
        </g>
      </Icon>
    );
  },
);
