// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ExportSolidIconProps = IconProps;

export const ExportSolidIcon = forwardRef<SVGSVGElement, ExportSolidIconProps>(
  function ExportSolidIcon(props: ExportSolidIconProps, ref) {
    return (
      <Icon
        data-testid="ExportSolidIcon"
        aria-label="export solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M.25.25h15.5v15.5H.25Zm5.365 1.788V.846H.846v14.308h4.77v-1.192H2.037V2.038ZM4.423 7.404v1.192h9.062L10.98 11.1l.834.835L15.75 8l-3.935-3.935-.834.835 2.504 2.504Z"
          />
        </g>
      </Icon>
    );
  },
);
