// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type FilterIconProps = IconProps;

export const FilterIcon = forwardRef<SVGSVGElement, FilterIconProps>(
  function FilterIcon(props: FilterIconProps, ref) {
    return (
      <Icon
        data-testid="FilterIcon"
        aria-label="filter"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M1.903 1.668h12.194l-4.434 4.99V12.2l-3.326 1.663V6.657Z"
          />
        </g>
      </Icon>
    );
  },
);
