// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type FirstIconProps = IconProps;

export const FirstIcon = forwardRef<SVGSVGElement, FirstIconProps>(
  function FirstIcon(props: FirstIconProps, ref) {
    return (
      <Icon
        data-testid="FirstIcon"
        aria-label="first"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.332.767v14.466M13.904.767 6.671 8l7.233 7.233"
          />
        </g>
      </Icon>
    );
  },
);
