// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type FlagIconProps = IconProps;

export const FlagIcon = forwardRef<SVGSVGElement, FlagIconProps>(
  function FlagIcon(props: FlagIconProps, ref) {
    return (
      <Icon
        data-testid="FlagIcon"
        aria-label="flag"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M3.5 3h4l2 2h4l-2 3 2 3h-5l-2-2h-3Zm0-1.5v13"
          />
        </g>
      </Icon>
    );
  },
);
