// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type FolderClosedIconProps = IconProps;

export const FolderClosedIcon = forwardRef<
  SVGSVGElement,
  FolderClosedIconProps
>(function FolderClosedIcon(props: FolderClosedIconProps, ref) {
  return (
    <Icon
      data-testid="FolderClosedIcon"
      aria-label="folder closed"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M2.5 13.5V3h4l2 2h5v8.5Zm0-6.5h11"
        />
      </g>
    </Icon>
  );
});
