// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type Forward10IconProps = IconProps;

export const Forward10Icon = forwardRef<SVGSVGElement, Forward10IconProps>(
  function Forward10Icon(props: Forward10IconProps, ref) {
    return (
      <Icon
        data-testid="Forward10Icon"
        aria-label="forward 10"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M13.686 3.917C12.769 3 11.83 1.999 10.629 1.512A7 7 0 1 0 15 8m-1.314-7v2.917h-2.917"
          />
          <path d="M13.686 1.828a.894.894 0 0 1-1.47.684c.517.436.996.931 1.47 1.405z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M13.686 1.828a.894.894 0 0 1-1.47.684"
          />
          <path d="M11.425 3.917a.894.894 0 0 0 .552-1.599c.61.479 1.164 1.054 1.709 1.599z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M11.425 3.917a.894.894 0 0 0 .552-1.599"
          />
          <path
            fillRule="evenodd"
            d="M6.403 5.523v4.927h-.622V6.3l-1.256.458v-.562l1.78-.673Z"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.18)"
            d="M6.403 5.523v4.927h-.622V6.3l-1.256.458v-.562l1.78-.673Z"
          />
          <path
            fillRule="evenodd"
            d="M11.475 7.61v.747q0 .602-.108 1.016t-.31.666-.486.366q-.284.112-.641.112-.283 0-.522-.07t-.429-.228-.324-.408-.206-.613q-.07-.36-.07-.841V7.61q0-.603.109-1.01t.311-.654.487-.356.637-.107q.286 0 .527.069.24.069.43.218.188.15.32.398.133.247.204.604t.07.838m-.625.848v-.953q0-.33-.039-.58t-.113-.43-.186-.289-.26-.163-.328-.052q-.222 0-.393.082-.172.083-.288.261t-.177.468-.06.703v.953q0 .33.038.582.039.252.116.436.078.183.189.301t.257.173.325.056q.229 0 .4-.088t.288-.274.174-.481.057-.705"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.18)"
            d="M11.475 7.61v.747q0 .602-.108 1.016t-.31.666-.486.366q-.284.112-.641.112-.283 0-.522-.07t-.429-.228-.324-.408-.206-.613q-.07-.36-.07-.841V7.61q0-.603.109-1.01t.311-.654.487-.356.637-.107q.286 0 .527.069.24.069.43.218.188.15.32.398.133.247.204.604t.07.838Zm-.626.848v-.953q0-.33-.039-.58t-.113-.43-.186-.289-.26-.163-.328-.052q-.222 0-.393.082-.172.083-.288.261t-.177.468-.06.703v.953q0 .33.038.582.039.252.116.436.078.183.189.301t.257.173.325.056q.229 0 .4-.088t.288-.274.174-.481.057-.705Z"
          />
        </g>
      </Icon>
    );
  },
);
