// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type GlobeSolidIconProps = IconProps;

export const GlobeSolidIcon = forwardRef<SVGSVGElement, GlobeSolidIconProps>(
  function GlobeSolidIcon(props: GlobeSolidIconProps, ref) {
    return (
      <Icon
        data-testid="GlobeSolidIcon"
        aria-label="globe solid"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M6.04 10.802C6.827 9.882 7.368 8.94 7.678 8H4.355c.325.942.883 1.882 1.686 2.802ZM7.919 7a5.907 5.907 0 0 0-.031-2H4.095a5.911 5.911 0 0 0 .002 2h3.822Zm-.305-3c-.328-.91-.876-1.82-1.655-2.709-.762.89-1.293 1.8-1.607 2.709h3.262Z" />
        <path
          fillRule="evenodd"
          d="M12 6A6 6 0 1 1 0 6a6 6 0 0 1 12 0ZM3.01 6c0-.334.024-.668.073-1H1.1c.07-.348.177-.683.316-1h1.887c.288-.976.786-1.932 1.487-2.853a5.011 5.011 0 0 1 2.33-.021c.725.926 1.244 1.89 1.55 2.874h1.915c.139.317.245.652.316 1H8.903a6.91 6.91 0 0 1 .026 2H10.9c-.07.348-.177.683-.316 1H8.722c-.272.968-.751 1.917-1.427 2.83a5.006 5.006 0 0 1-2.502.023c-.7-.92-1.199-1.876-1.488-2.853H1.416A4.962 4.962 0 0 1 1.1 7h1.984a6.908 6.908 0 0 1-.074-1Z"
          clipRule="evenodd"
        />
      </Icon>
    );
  },
);
