// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type GlobeSolidIconProps = IconProps;

export const GlobeSolidIcon = forwardRef<SVGSVGElement, GlobeSolidIconProps>(
  function GlobeSolidIcon(props: GlobeSolidIconProps, ref) {
    return (
      <Icon
        data-testid="GlobeSolidIcon"
        aria-label="globe solid"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M6.04 10.802C6.827 9.882 7.368 8.94 7.678 8H4.355c.325.942.883 1.882 1.686 2.802M7.919 7a5.9 5.9 0 0 0-.031-2H4.095a5.9 5.9 0 0 0 .002 2zm-.305-3c-.328-.91-.876-1.82-1.655-2.709-.762.89-1.293 1.8-1.607 2.709z" />
        <path
          fillRule="evenodd"
          d="M12 6A6 6 0 1 1 0 6a6 6 0 0 1 12 0M3.01 6q0-.502.073-1H1.1q.106-.523.316-1h1.887c.288-.976.786-1.932 1.487-2.853a5 5 0 0 1 2.33-.021c.725.926 1.244 1.89 1.55 2.874h1.915q.209.477.316 1H8.903a7 7 0 0 1 .026 2H10.9q-.106.523-.316 1H8.722c-.272.968-.751 1.917-1.427 2.83a5 5 0 0 1-2.502.023c-.7-.92-1.199-1.876-1.488-2.853H1.416A5 5 0 0 1 1.1 7h1.984a7 7 0 0 1-.074-1"
          clipRule="evenodd"
        />
      </Icon>
    );
  },
);
