// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type GridIconProps = IconProps;

export const GridIcon = forwardRef<SVGSVGElement, GridIconProps>(
  function GridIcon(props: GridIconProps, ref) {
    return (
      <Icon
        data-testid="GridIcon"
        aria-label="grid"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path
          fillRule="evenodd"
          d="M0 5V0h5v5zm1-4h3v3H1zm6 4V0h5v5zm1-4h3v3H8zM7 7v5h5V7zm4 1H8v3h3zM0 12V7h5v5zm1-4h3v3H1z"
          clipRule="evenodd"
        />
      </Icon>
    );
  },
);
