// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type GroupIconProps = IconProps;

export const GroupIcon = forwardRef<SVGSVGElement, GroupIconProps>(
  function GroupIcon(props: GroupIconProps, ref) {
    return (
      <Icon
        data-testid="GroupIcon"
        aria-label="group"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="M1.02 1.02h13.96v13.96H1.02Z" />
            <path d="M8.566 6.868v-2.83H4.038v4.528h2.83" />
            <path d="M6.868 6.868h5.094v5.094H6.868Z" />
          </g>
        </g>
      </Icon>
    );
  },
);
