// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type GuideClosedSolidIconProps = IconProps;

export const GuideClosedSolidIcon = forwardRef<
  SVGSVGElement,
  GuideClosedSolidIconProps
>(function GuideClosedSolidIcon(props: GuideClosedSolidIconProps, ref) {
  return (
    <Icon
      data-testid="GuideClosedSolidIcon"
      aria-label="guide closed solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="M4.5 2.5h9v11h-9Zm1.5 1h1v9H6ZM8.5 5h3v1h-3Zm0 3h3v1h-3Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M2.5 5h2m-2 3h2m-2 3h2"
        />
      </g>
    </Icon>
  );
});
