// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type GuideOpenIconProps = IconProps;

export const GuideOpenIcon = forwardRef<SVGSVGElement, GuideOpenIconProps>(
  function GuideOpenIcon(props: GuideOpenIconProps, ref) {
    return (
      <Icon
        data-testid="GuideOpenIcon"
        aria-label="guide open"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M8 2.893Q6.864 1.19 4.59 1.19H.993v11.364h3.599q2.273 0 3.409 1.704 1.136-1.704 3.41-1.704h3.598V1.189H11.41q-2.274 0-3.41 1.704Z"
          />
          <path d="M2.129 1.189A1.136 1.136 0 0 0 .992 2.325V1.19Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.129 1.189A1.136 1.136 0 0 0 .992 2.325"
          />
          <path d="M.992 11.416a1.136 1.136 0 0 0 1.137 1.137H.992Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M.992 11.416a1.136 1.136 0 0 0 1.137 1.137"
          />
          <path d="M13.871 12.553a1.136 1.136 0 0 0 1.137-1.137v1.137Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M13.871 12.553a1.136 1.136 0 0 0 1.137-1.137"
          />
          <path d="M15.008 2.325A1.136 1.136 0 0 0 13.87 1.19h1.137Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M15.008 2.325A1.136 1.136 0 0 0 13.87 1.19"
          />
          <path d="M7.305 13.463a1.06 1.06 0 0 0 1.39 0q-.39.335-.695.794-.306-.459-.695-.794" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M7.305 13.463a1.06 1.06 0 0 0 1.39 0"
          />
          <path d="M8.695 2.099a1.06 1.06 0 0 1-1.39 0q.39.335.695.794.306-.459.695-.794" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M8.695 2.099a1.06 1.06 0 0 1-1.39 0M8 2.893v11.364m-4.735-9.66h2.273m-2.273 3.41h2.273m4.924-3.41h2.273m-2.273 3.41h2.273"
          />
        </g>
      </Icon>
    );
  },
);
