// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type HandshakeSolidIconProps = IconProps;

export const HandshakeSolidIcon = forwardRef<
  SVGSVGElement,
  HandshakeSolidIconProps
>(function HandshakeSolidIcon(props: HandshakeSolidIconProps, ref) {
  return (
    <Icon
      data-testid="HandshakeSolidIcon"
      aria-label="handshake solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M.25 5.777 5.417.61 7.205 2.4 8.994.61l6.756 6.757-2.226 2.225.2.199q.953.954 0 1.908l-2.386 2.384q-.953.954-1.907 0l-.373-.372a1.6 1.6 0 0 1-.18.216l-.994.994a1.55 1.55 0 1 1-2.192-2.192l.993-.994a1.6 1.6 0 0 1 .244-.199l-.116-.121a1.6 1.6 0 0 1-.201.247l-.994.994a1.55 1.55 0 1 1-2.192-2.193l.994-.993a1.6 1.6 0 0 1 .312-.241L4.59 9.08a1.6 1.6 0 0 1-.244.316l-.994.993A1.55 1.55 0 1 1 1.16 8.197l.755-.755Zm6.28-1.63q-.477.477 0 .954t.953 0l.716-.715q.318-.318.636 0l4.411 4.411.835-.834-5.087-5.405ZM2.847 9.884l.994-.993a.835.835 0 0 0-1.18-1.18l-.994.993a.835.835 0 0 0 1.18 1.18m2.266 2.266.993-.994a.835.835 0 0 0-1.18-1.18l-.994.994a.835.835 0 0 0 1.18 1.18m2.266 2.265.994-.993a.835.835 0 0 0-1.18-1.18l-.994.993a.835.835 0 0 0 1.18 1.18"
        />
      </g>
    </Icon>
  );
});
