// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type HandshakeIconProps = IconProps;

export const HandshakeIcon = forwardRef<SVGSVGElement, HandshakeIconProps>(
  function HandshakeIcon(props: HandshakeIconProps, ref) {
    return (
      <Icon
        data-testid="HandshakeIcon"
        aria-label="handshake"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="m1.31 6.234 4.47-4.47 1.547 1.547 1.547-1.547L14.72 7.61l-1.926 1.925.379.378q.618.62 0 1.238t-1.238 0q.619.619 0 1.238t-1.238 0q.62.618 0 1.237t-1.237 0l-.529-.528a1.3 1.3 0 0 1-.156.187l-.86.86a1.34 1.34 0 1 1-1.896-1.897l.86-.859a1.3 1.3 0 0 1 .21-.172l-.1-.105a1.3 1.3 0 0 1-.174.214l-.86.859a1.34 1.34 0 1 1-1.896-1.896l.86-.86a1.3 1.3 0 0 1 .27-.208l-.123-.129a1.3 1.3 0 0 1-.21.274l-.86.86A1.34 1.34 0 1 1 2.1 8.329l.653-.653Z" />
            <path d="M7.327 3.311 6.296 4.343q-.757.756 0 1.512.756.757 1.512 0l.654-.653 4.331 4.332" />
          </g>
        </g>
      </Icon>
    );
  },
);
