// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type HeadphonesDisabledIconProps = IconProps;

export const HeadphonesDisabledIcon = forwardRef<
  SVGSVGElement,
  HeadphonesDisabledIconProps
>(function HeadphonesDisabledIcon(props: HeadphonesDisabledIconProps, ref) {
  return (
    <Icon
      data-testid="HeadphonesDisabledIcon"
      aria-label="headphones disabled"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <g
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
        >
          <path d="M1.742 11.24V7.259a6.3 6.3 0 0 1 .23-1.68M4.59 2.01a6.258 6.258 0 0 1 9.667 5.248v3.766" />
          <path d="M2.197 8.965H4.7q.455 0 .455.455v4.78q0 .455-.455.455H2.197q-.455 0-.455-.455V9.42q0-.455.455-.455Zm9.76 0h1.846q.455 0 .455.455v1.846M1.173 1.569l13.654 13.654" />
        </g>
      </g>
    </Icon>
  );
});
