// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type HolidaySolidIconProps = IconProps;

export const HolidaySolidIcon = forwardRef<
  SVGSVGElement,
  HolidaySolidIconProps
>(function HolidaySolidIcon(props: HolidaySolidIconProps, ref) {
  return (
    <Icon
      data-testid="HolidaySolidIcon"
      aria-label="holiday solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="M2.5 4a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M4 1.333V2.75m0 2.5v1.417M1.333 4H2.75m2.5 0h1.417M2.083 2.083l1.033 1.033m1.768 1.768 1.033 1.033m-3.834 0 1.033-1.033m1.768-1.768 1.033-1.033"
        />
        <path
          fillRule="evenodd"
          d="M6.667 7.5Q9 3.833 12 5.833q2.5 1.5 2 3.667Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M10.5 8.5 9 14m-7.5 0h13"
        />
      </g>
    </Icon>
  );
});
