// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type HospitalIconProps = IconProps;

export const HospitalIcon = forwardRef<SVGSVGElement, HospitalIconProps>(
  function HospitalIcon(props: HospitalIconProps, ref) {
    return (
      <Icon
        data-testid="HospitalIcon"
        aria-label="hospital"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M4.03.988h7.94v13.988H4.03Z"
          />
          <path d="M10.835.988a1.134 1.134 0 0 1 1.135 1.134V.988Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M10.835.988a1.134 1.134 0 0 1 1.135 1.134"
          />
          <path d="M11.97 13.842a1.134 1.134 0 0 1-1.135 1.134h1.135Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M11.97 13.842a1.134 1.134 0 0 1-1.135 1.134"
          />
          <path d="M5.165 14.976a1.134 1.134 0 0 1-1.135-1.134v1.134Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M5.165 14.976a1.134 1.134 0 0 1-1.135-1.134"
          />
          <path d="M4.03 2.122A1.134 1.134 0 0 1 5.165.988H4.03Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M4.03 2.122A1.134 1.134 0 0 1 5.165.988m-3.97 13.988h13.61"
          />
          <path d="M2.745 14.976a1.285 1.285 0 0 0 1.285-1.285v1.285Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.745 14.976a1.285 1.285 0 0 0 1.285-1.285"
          />
          <path d="M5.316 14.976a1.285 1.285 0 0 1-1.286-1.285v1.285Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M5.316 14.976a1.285 1.285 0 0 1-1.286-1.285"
          />
          <path d="M10.684 14.976a1.285 1.285 0 0 0 1.286-1.285v1.285Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M10.684 14.976a1.285 1.285 0 0 0 1.286-1.285"
          />
          <path d="M13.255 14.976a1.285 1.285 0 0 1-1.285-1.285v1.285Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M13.255 14.976a1.285 1.285 0 0 1-1.285-1.285M5.732 9.684h1.134m2.268 0h1.134m-3.402 5.292V12.52h2.268v2.457"
          />
          <path d="M6.866 13.653A1.134 1.134 0 0 1 8 12.52H6.866Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M6.866 13.653A1.134 1.134 0 0 1 8 12.52"
          />
          <path d="M8 12.519a1.134 1.134 0 0 1 1.134 1.134V12.52Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M8 12.519a1.134 1.134 0 0 1 1.134 1.134"
          />
          <path d="M5.807 14.976a1.06 1.06 0 0 0 1.059-1.058v1.058Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M5.807 14.976a1.06 1.06 0 0 0 1.059-1.058"
          />
          <path d="M10.193 14.976a1.06 1.06 0 0 1-1.059-1.058v1.058Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M10.193 14.976a1.06 1.06 0 0 1-1.059-1.058"
          />
          <path
            fillRule="evenodd"
            d="M7.2 2.906h1.6V3.97a.4.4 0 0 0 .4.4h1.064v1.6H9.2a.4.4 0 0 0-.4.4v1.064H7.2V6.37a.4.4 0 0 0-.4-.4H5.736v-1.6H6.8a.4.4 0 0 0 .4-.4Z"
          />
        </g>
      </Icon>
    );
  },
);
