// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, IconProps } from "../icon";

export type IconFigmaIconProps = IconProps;

export const IconFigmaIcon = forwardRef<SVGSVGElement, IconFigmaIconProps>(
  function IconFigmaIcon(props: IconFigmaIconProps, ref) {
    return (
      <Icon
        data-testid="IconFigmaIcon"
        aria-label="icon figma"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path
          fillRule="evenodd"
          d="M4 1a2 2 0 0 0-1.323 3.5A1.995 1.995 0 0 0 2 6c0 .597.262 1.134.677 1.5A2 2 0 0 0 4 11h.25A2.25 2.25 0 0 0 6.5 8.75V7.475A1.75 1.75 0 1 0 8.786 4.84 2 2 0 0 0 8 1H4Zm1.5 1H4a1 1 0 0 0 0 2h1.5V2Zm0 5V5H4a1 1 0 0 0 0 2h1.5ZM4 8a1 1 0 0 0 0 2h.25c.69 0 1.25-.56 1.25-1.25V8H4Zm2.525-3a1.768 1.768 0 0 0-.025.025V5h.025ZM6.5 4H8a1 1 0 1 0 0-2H6.5v2Zm2 2.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"
          clipRule="evenodd"
        />
      </Icon>
    );
  }
);
