// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ImageSolidIconProps = IconProps;

export const ImageSolidIcon = forwardRef<SVGSVGElement, ImageSolidIconProps>(
  function ImageSolidIcon(props: ImageSolidIconProps, ref) {
    return (
      <Icon
        data-testid="ImageSolidIcon"
        aria-label="image solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M1.442.25h9.539l3.577 3.577V15.75H1.442Zm9.539 1.192v1.789q0 .596.596.596h1.788ZM3.827 7.404a1.192 1.192 0 1 0 2.385 0 1.192 1.192 0 1 0-2.385 0m0 5.961 2.683-2.98 2.086 1.788 2.385-2.98 1.788 2.086v2.086Z"
          />
        </g>
      </Icon>
    );
  },
);
