// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ImageSolidIconProps = IconProps;

export const ImageSolidIcon = forwardRef<SVGSVGElement, ImageSolidIconProps>(
  function ImageSolidIcon(props: ImageSolidIconProps, ref) {
    return (
      <Icon
        data-testid="ImageSolidIcon"
        aria-label="image solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fillRule="evenodd"
            d="M2.5 1.5h8l3 3v10h-11Zm8 1V4q0 .5.5.5h1.5Zm-6 5a1 1 0 1 0 2 0 1 1 0 1 0-2 0m0 5L6.75 10l1.75 1.5 2-2.5 1.5 1.75v1.75Z"
          />
        </g>
      </Icon>
    );
  },
);
