// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type InboxSolidIconProps = IconProps;

export const InboxSolidIcon = forwardRef<SVGSVGElement, InboxSolidIconProps>(
  function InboxSolidIcon(props: InboxSolidIconProps, ref) {
    return (
      <Icon
        data-testid="InboxSolidIcon"
        aria-label="inbox solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path fillRule="evenodd" d="M2.5 9h3l1 2h3l1-2h3v4.5h-11Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.5 6.5V9m11-2.5V9M8 1.5v7m-3-3 3 3 3-3"
          />
        </g>
      </Icon>
    );
  },
);
