// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type KeySolidIconProps = IconProps;

export const KeySolidIcon = forwardRef<SVGSVGElement, KeySolidIconProps>(
  function KeySolidIcon(props: KeySolidIconProps, ref) {
    return (
      <Icon
        data-testid="KeySolidIcon"
        aria-label="key solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M6.558 9.106a4.181 4.181 0 1 1 2.548-2.548L15 12.45V15h-2.549v-2.39h-2.389v-2.389ZM3.969 5.164a1.195 1.195 0 1 0 2.39 0 1.195 1.195 0 1 0-2.39 0"
          />
          <path d="M9.178 6.337a.4.4 0 0 0 .1.393l-.172-.172a4 4 0 0 0 .072-.221m3.273 6.672a.4.4 0 0 0-.398-.398h.398zm-2.389-2.497a.4.4 0 0 0-.277-.379l.277.088zm-3.38-1.366a.4.4 0 0 0-.242 0l.118-.04z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M6.558 9.106a4.181 4.181 0 1 1 2.548-2.548L15 12.45V15h-2.549v-2.39h-2.389v-2.389Z"
          />
          <path d="M14.65 12.102a1.2 1.2 0 0 1 .35.844v-.495Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M14.65 12.102a1.2 1.2 0 0 1 .35.844"
          />
          <path d="M15 13.805A1.195 1.195 0 0 1 13.805 15H15Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M15 13.805A1.195 1.195 0 0 1 13.805 15"
          />
          <path d="M13.646 15a1.195 1.195 0 0 1-1.195-1.195V15Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M13.646 15a1.195 1.195 0 0 1-1.195-1.195"
          />
          <path d="M12.451 13.805a1.195 1.195 0 0 0-1.194-1.194h1.194Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M12.451 13.805a1.195 1.195 0 0 0-1.194-1.194"
          />
          <path d="M11.257 12.61a1.195 1.195 0 0 1-1.195-1.194v1.195Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M11.257 12.61a1.195 1.195 0 0 1-1.195-1.194"
          />
          <path d="M10.062 11.095a1.195 1.195 0 0 0-.832-1.139l.832.265Z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M10.062 11.095a1.195 1.195 0 0 0-.832-1.139"
          />
          <path d="M9.267 5.97a1.2 1.2 0 0 0 .327 1.076l-.488-.488a4 4 0 0 0 .16-.587" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M9.267 5.97a1.2 1.2 0 0 0 .327 1.076"
          />
          <path d="M6.914 9.22a1.2 1.2 0 0 0-.67-.016 4 4 0 0 0 .314-.098z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M6.914 9.22a1.2 1.2 0 0 0-.67-.016"
          />
        </g>
      </Icon>
    );
  },
);
