// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type KeySolidIconProps = IconProps;

export const KeySolidIcon = forwardRef<SVGSVGElement, KeySolidIconProps>(
  function KeySolidIcon(props: KeySolidIconProps, ref) {
    return (
      <Icon
        data-testid="KeySolidIcon"
        aria-label="key solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fillRule="evenodd"
            d="M6.933 9.067a3.5 3.5 0 1 1 2.134-2.134L14 11.867V14h-2.133v-2h-2v-2Zm-2.166-3.3a1 1 0 1 0 2 0 1 1 0 1 0-2 0"
          />
        </g>
      </Icon>
    );
  },
);
