// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type KeyTabIconProps = IconProps;

export const KeyTabIcon = forwardRef<SVGSVGElement, KeyTabIconProps>(
  function KeyTabIcon(props: KeyTabIconProps, ref) {
    return (
      <Icon
        data-testid="KeyTabIcon"
        aria-label="key tab"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2 8h9.5m-4-4 4 4-4 4M14 3v10"
          />
        </g>
      </Icon>
    );
  },
);
