// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type LayersSolidIconProps = IconProps;

export const LayersSolidIcon = forwardRef<SVGSVGElement, LayersSolidIconProps>(
  function LayersSolidIcon(props: LayersSolidIconProps, ref) {
    return (
      <Icon
        data-testid="LayersSolidIcon"
        aria-label="layers solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="m8 1.865 6.135 3.15L8 8.165l-6.135-3.15Z"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="m8 1.865 6.135 3.15L8 8.165l-6.135-3.15Z"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M1.865 8 8 11.15 14.135 8m-12.27 2.985L8 14.135l6.135-3.15"
          />
        </g>
      </Icon>
    );
  },
);
