// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type LessThanEqualToIconProps = IconProps;

export const LessThanEqualToIcon = forwardRef<
  SVGSVGElement,
  LessThanEqualToIconProps
>(function LessThanEqualToIcon(props: LessThanEqualToIconProps, ref) {
  return (
    <Icon
      data-testid="LessThanEqualToIcon"
      aria-label="less than equal to"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="m13.038.893-8.977 5.13 8.977 5.13M4.061 15h8.977"
        />
      </g>
    </Icon>
  );
});
