// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type LightbulbIconProps = IconProps;

export const LightbulbIcon = forwardRef<SVGSVGElement, LightbulbIconProps>(
  function LightbulbIcon(props: LightbulbIconProps, ref) {
    return (
      <Icon
        data-testid="LightbulbIcon"
        aria-label="lightbulb"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M7.309 11.455H4.693v-1H7.31zM6 3.705a.5.5 0 0 1 0 1 .75.75 0 0 0-.75.75.5.5 0 0 1-1 0c0-.966.784-1.75 1.75-1.75" />
        <path
          fillRule="evenodd"
          d="M6.257 2.216a3.126 3.126 0 0 1 2.719 4.068l-.09.242c-.217.526-.542 1.059-.776 1.502-.249.472-.429.898-.473 1.335l-.015.143-.045.45H4.423l-.045-.45-.015-.143C4.32 8.926 4.14 8.5 3.89 8.028c-.176-.332-.403-.715-.597-1.108l-.18-.394A3.126 3.126 0 0 1 6 2.206zm-.432.996a2.127 2.127 0 0 0-1.788 2.932l.158.345c.17.342.37.677.58 1.073.22.417.432.88.535 1.393h1.38c.103-.512.315-.976.536-1.393.278-.528.542-.948.737-1.418l.06-.165A2.126 2.126 0 0 0 6 3.205z"
          clipRule="evenodd"
        />
        <path d="M2.3 5.75H.8v-1h1.5zm8.9 0H9.7v-1h1.5zm-7.493-3.5L3 2.957l-1.06-1.06.706-.708zm6.353-.354L9 2.957l-.707-.707 1.06-1.06zM6.5 1.55h-1V.05h1z" />
      </Icon>
    );
  },
);
