// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MaintenanceIconProps = IconProps;

export const MaintenanceIcon = forwardRef<SVGSVGElement, MaintenanceIconProps>(
  function MaintenanceIcon(props: MaintenanceIconProps, ref) {
    return (
      <Icon
        data-testid="MaintenanceIcon"
        aria-label="maintenance"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M5.938 2.402a2.484 2.484 0 0 0-1.72-.729l1.583 1.583-2.545 2.545L1.673 4.22a2.497 2.497 0 0 0 3.572 2.205l.32-.152 3.909 3.909a.5.5 0 0 0 .707-.707l-3.91-3.91.152-.319a2.497 2.497 0 0 0-.485-2.843Zm.707-.707a3.493 3.493 0 0 1 .818 3.646l3.425 3.425a1.5 1.5 0 0 1-2.122 2.122L5.341 7.463A3.493 3.493 0 0 1 .87 3.014l.263-.751 2.124 2.124 1.131-1.131-2.124-2.124.751-.262a3.497 3.497 0 0 1 3.631.825Z" />
      </Icon>
    );
  },
);
