// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ManWomanIconProps = IconProps;

export const ManWomanIcon = forwardRef<SVGSVGElement, ManWomanIconProps>(
  function ManWomanIcon(props: ManWomanIconProps, ref) {
    return (
      <Icon
        data-testid="ManWomanIcon"
        aria-label="man woman"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.833 3a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0Zm-1 3.5h5v4h-.5v4h-4v-4h-.5Zm2.5 4v4M10.167 3a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0Zm.5 3.5h2l1.666 5h-.666v3h-4v-3H9Zm1 5v3"
          />
        </g>
      </Icon>
    );
  },
);
