// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MessageSolidIconProps = IconProps;

export const MessageSolidIcon = forwardRef<
  SVGSVGElement,
  MessageSolidIconProps
>(function MessageSolidIcon(props: MessageSolidIconProps, ref) {
  return (
    <Icon
      data-testid="MessageSolidIcon"
      aria-label="message solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <g>
          <path
            fillRule="evenodd"
            d="M.25 1.66h15.5v12.68H.25Zm1.823 1.863L8 7.833l5.927-4.31.828 1.14L8 9.576 1.245 4.663Zm9.243 5.388 3.523 3.523-.996.996-3.523-3.523ZM1.161 12.434 4.684 8.91l.996.996-3.523 3.523Z"
          />
          <path d="M13.585 3.772a.423.423 0 0 1 .59.093l-.249-.342Zm.922.548a.423.423 0 0 1-.094.591l.342-.248ZM8.276 9.375a.47.47 0 0 1-.552 0l.276.2ZM1.587 4.911a.423.423 0 0 1-.094-.59l-.248.342Zm.238-1.046a.423.423 0 0 1 .59-.093l-.341-.249Zm12.715 8.27a.423.423 0 0 1 0 .598l.3-.3Zm-.398.996a.423.423 0 0 1-.598 0l.299.3Zm-3.523-2.925a.423.423 0 0 1 0-.598l-.3.3Zm.398-.996a.423.423 0 0 1 .598 0l-.299-.3Zm-6.632 0a.423.423 0 0 1 .598 0l-.3-.3Zm.996.398a.423.423 0 0 1 0 .598l.3-.299Zm-2.925 3.523a.423.423 0 0 1-.598 0l.3.3Zm-.996-.398a.423.423 0 0 1 0-.598l-.3.299Z" />
        </g>
      </g>
    </Icon>
  );
});
