// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MessageReplyIconProps = IconProps;

export const MessageReplyIcon = forwardRef<
  SVGSVGElement,
  MessageReplyIconProps
>(function MessageReplyIcon(props: MessageReplyIconProps, ref) {
  return (
    <Icon
      data-testid="MessageReplyIcon"
      aria-label="message reply"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M11 11h-1V9a4 4 0 0 0-.233-1.348l-.072-.182a4 4 0 0 0-.731-1.156l-.136-.142a4 4 0 0 0-1.117-.788l-.18-.08A4 4 0 0 0 6 5H2.914l1.621 1.621-.707.707L1 4.5l2.828-2.828.707.707L2.915 4H6a5 5 0 0 1 5 5z" />
    </Icon>
  );
});
