// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MessageForwardIconProps = IconProps;

export const MessageForwardIcon = forwardRef<
  SVGSVGElement,
  MessageForwardIconProps
>(function MessageForwardIcon(props: MessageForwardIconProps, ref) {
  return (
    <Icon
      data-testid="MessageForwardIcon"
      aria-label="message forward"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M2 11H1V9a5 5 0 0 1 5-5h3.086L7.465 2.379l.707-.707L11 4.5 8.172 7.328l-.707-.707L9.085 5H6a4 4 0 0 0-1.53.305l-.18.079a4 4 0 0 0-1.118.788l-.136.142c-.308.34-.555.731-.731 1.156l-.072.182A4 4 0 0 0 2 9z" />
    </Icon>
  );
});
