// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MessageForwardIconProps = IconProps;

export const MessageForwardIcon = forwardRef<
  SVGSVGElement,
  MessageForwardIconProps
>(function MessageForwardIcon(props: MessageForwardIconProps, ref) {
  return (
    <Icon
      data-testid="MessageForwardIcon"
      aria-label="message forward"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.05 15.75v-4.766a6.13 6.13 0 0 1 6.128-6.129h7.49M10.583.77l4.085 4.085-4.085 4.086"
        />
      </g>
    </Icon>
  );
});
