// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MicrophoneSolidIconProps = IconProps;

export const MicrophoneSolidIcon = forwardRef<
  SVGSVGElement,
  MicrophoneSolidIconProps
>(function MicrophoneSolidIcon(props: MicrophoneSolidIconProps, ref) {
  return (
    <Icon
      data-testid="MicrophoneSolidIcon"
      aria-label="microphone solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M8 1q2.692 0 2.692 2.692V8q0 2.692-2.692 2.692T5.308 8V3.692Q5.308 1 8 1"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M8 1q2.692 0 2.692 2.692V8q0 2.692-2.692 2.692T5.308 8V3.692Q5.308 1 8 1Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M3.154 6.923V8a4.846 4.846 0 0 0 9.692 0V6.923M8 12.846V15m-2.692 0h5.384"
        />
      </g>
    </Icon>
  );
});
