// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MicrophoneDisabledIconProps = IconProps;

export const MicrophoneDisabledIcon = forwardRef<
  SVGSVGElement,
  MicrophoneDisabledIconProps
>(function MicrophoneDisabledIcon(props: MicrophoneDisabledIconProps, ref) {
  return (
    <Icon
      data-testid="MicrophoneDisabledIcon"
      aria-label="microphone disabled"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M3.503 5.625a2.5 2.5 0 0 0 2.378 2.372z" />
      <path d="M6.795 8.91A3.5 3.5 0 0 1 2.5 5.5h-1a4.5 4.5 0 0 0 4 4.473V11H3v1h6v-.891L8.891 11H6.5V9.973q.575-.066 1.096-.264zm3.102-1.158-.74-.738c.22-.458.343-.972.343-1.514h1c0 .82-.22 1.59-.603 2.252m-1.51-1.506L7.5 5.36V2.5a1.5 1.5 0 0 0-2.995-.128l-.82-.819A2.5 2.5 0 0 1 8.5 2.5v3q-.002.391-.113.746M10.307 11 1 1.716 1.716 1 11 10.267z" />
    </Icon>
  );
});
