// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MicrophoneDisabledIconProps = IconProps;

export const MicrophoneDisabledIcon = forwardRef<
  SVGSVGElement,
  MicrophoneDisabledIconProps
>(function MicrophoneDisabledIcon(props: MicrophoneDisabledIconProps, ref) {
  return (
    <Icon
      data-testid="MicrophoneDisabledIcon"
      aria-label="microphone disabled"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <g
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
        >
          <path d="M8 1q2.692 0 2.692 2.692V7.56m-3.227 3.104Q5.56 10.44 5.337 8.535m.13-5.994Q5.963 1 8 1" />
          <path d="M3.154 6.923V8A4.846 4.846 0 0 0 8 12.846a4.8 4.8 0 0 0 1.657-.29m2.899-2.9A4.8 4.8 0 0 0 12.846 8V6.923M8 12.846V15m-2.692 0h5.384M1.538 1.538l12.924 12.924" />
        </g>
      </g>
    </Icon>
  );
});
