// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MoveHorizontalIconProps = IconProps;

export const MoveHorizontalIcon = forwardRef<
  SVGSVGElement,
  MoveHorizontalIconProps
>(function MoveHorizontalIcon(props: MoveHorizontalIconProps, ref) {
  return (
    <Icon
      data-testid="MoveHorizontalIcon"
      aria-label="move horizontal"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M4.992 6.496H1.904l1.795 1.798-.707.708L0 6.004 2.998 3l.706.708-1.81 1.814h3.098v.974Zm2.016-.99h3.088L8.301 3.708 9.008 3 12 5.998 9.002 9.002l-.706-.708 1.81-1.814H7.008v-.974Z" />
    </Icon>
  );
});
