// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type MusicDisabledSolidIconProps = IconProps;

export const MusicDisabledSolidIcon = forwardRef<
  SVGSVGElement,
  MusicDisabledSolidIconProps
>(function MusicDisabledSolidIcon(props: MusicDisabledSolidIconProps, ref) {
  return (
    <Icon
      data-testid="MusicDisabledSolidIcon"
      aria-label="music disabled solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M6.5 11v-.672m0-5.656V3.5l7-2V10M7.922 6.094 13.5 4.5"
        />
        <path
          fillRule="evenodd"
          d="m6.5 3.5 7-2v3L7.097 6.33 6.5 5.731Zm0 7.5c0 1.1-1.133 2-2.5 2s-2-.7-2-1.5 1.133-2 2.5-2 2 .7 2 1.5m7-1c0 .68-.433 1.284-1.087 1.645l-2.55-2.55c.44-.346 1.015-.595 1.637-.595 1.367 0 2 .7 2 1.5"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.5 2.5 14 15"
        />
      </g>
    </Icon>
  );
});
