// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type NoteSolidIconProps = IconProps;

export const NoteSolidIcon = forwardRef<SVGSVGElement, NoteSolidIconProps>(
  function NoteSolidIcon(props: NoteSolidIconProps, ref) {
    return (
      <Icon
        data-testid="NoteSolidIcon"
        aria-label="note solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <g>
            <path
              fillRule="evenodd"
              d="M.25.25h15.5v9.864l-5.636 5.636H.25Zm2.114 3.523h11.272v1.409H2.364Zm0 2.818h7.045V8H2.364Zm7.75 7.75 4.227-4.227h-4.227Z"
            />
            <path d="M13.214 3.773a.423.423 0 0 1 .422.422v-.422Zm.422.987a.423.423 0 0 1-.422.422h.422Zm-10.85.422a.423.423 0 0 1-.422-.423v.423Zm-.422-.987a.423.423 0 0 1 .422-.422h-.422ZM8.986 6.59a.423.423 0 0 1 .423.424V6.59Zm.424.987A.423.423 0 0 1 8.985 8h.423ZM2.786 8a.423.423 0 0 1-.422-.423V8Zm-.422-.986a.423.423 0 0 1 .422-.423h-.422Zm11.176 3.901a.47.47 0 0 0-.333-.801h1.134Zm-2.957-.801a.47.47 0 0 0-.47.47v-.47Zm-.469 3.093a.47.47 0 0 0 .801.332l-.801.802Z" />
          </g>
        </g>
      </Icon>
    );
  },
);
