// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type OverflowMenuIconProps = IconProps;

export const OverflowMenuIcon = forwardRef<
  SVGSVGElement,
  OverflowMenuIconProps
>(function OverflowMenuIcon(props: OverflowMenuIconProps, ref) {
  return (
    <Icon
      data-testid="OverflowMenuIcon"
      aria-label="overflow menu"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M.25 6.893h2.214v2.214H.25Zm6.643 0h2.214v2.214H6.893Zm6.643 0h2.214v2.214h-2.214Z"
        />
      </g>
    </Icon>
  );
});
