// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PanelCloseRightIconProps = IconProps;

export const PanelCloseRightIcon = forwardRef<
  SVGSVGElement,
  PanelCloseRightIconProps
>(function PanelCloseRightIcon(props: PanelCloseRightIconProps, ref) {
  return (
    <Icon
      data-testid="PanelCloseRightIcon"
      aria-label="panel close right"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <g
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
        >
          <path d="M14.988 14.988H1.012V1.012h13.976Z" />
          <path d="M14.437 14.988H1.563q-.551 0-.551-.551V1.563q0-.551.551-.551h12.874q.551 0 .551.551v12.874q0 .551-.551.551Z" />
          <path d="M11.31 14.988V1.012m.552 13.976q-.552 0-.552-.551m-.551.551q.551 0 .551-.551m.552-13.425q-.552 0-.552.551m-.551-.551q.551 0 .551.551M3.218 8h5.15m-2.575 2.575L8.368 8 5.793 5.425" />
        </g>
      </g>
    </Icon>
  );
});
