// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PanelOpenTopIconProps = IconProps;

export const PanelOpenTopIcon = forwardRef<
  SVGSVGElement,
  PanelOpenTopIconProps
>(function PanelOpenTopIcon(props: PanelOpenTopIconProps, ref) {
  return (
    <Icon
      data-testid="PanelOpenTopIcon"
      aria-label="panel open top"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M6 10.004 3.172 7.176l.707-.707L5.5 8.089V5.005h1V8.09l1.621-1.621.707.707z" />
      <path
        fillRule="evenodd"
        d="M0 12V0h12v12zM1 1v2h10V1zm0 3v7h10V4z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
