// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PanelCloseBottomIconProps = IconProps;

export const PanelCloseBottomIcon = forwardRef<
  SVGSVGElement,
  PanelCloseBottomIconProps
>(function PanelCloseBottomIcon(props: PanelCloseBottomIconProps, ref) {
  return (
    <Icon
      data-testid="PanelCloseBottomIcon"
      aria-label="panel close bottom"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M6 7 3.172 4.172l.707-.707L5.5 5.085V2h1v3.086l1.621-1.621.707.707z" />
      <path
        fillRule="evenodd"
        d="M0 12V0h12v12zM1 1v7h10V1zm0 8v2h10V9z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
