// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PanelOpenBottomSolidIconProps = IconProps;

export const PanelOpenBottomSolidIcon = forwardRef<
  SVGSVGElement,
  PanelOpenBottomSolidIconProps
>(function PanelOpenBottomSolidIcon(props: PanelOpenBottomSolidIconProps, ref) {
  return (
    <Icon
      data-testid="PanelOpenBottomSolidIcon"
      aria-label="panel open bottom solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path fillRule="evenodd" d="M1.667 14.333V11h12.666v3.333Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.667 14.333V1.667h12.666v12.666Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.667 13.833V2.167q0-.5.5-.5h11.666q.5 0 .5.5v11.666q0 .5-.5.5H2.167q-.5 0-.5-.5Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.667 11h12.666m-12.666.5q0-.5.5-.5m-.5-.5q0 .5.5.5m12.166.5q0-.5-.5-.5m.5-.5q0 .5-.5.5M8 9V4.333m-2.333 2L8 4l2.333 2.333"
        />
      </g>
    </Icon>
  );
});
