// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PanelCloseRightSolidIconProps = IconProps;

export const PanelCloseRightSolidIcon = forwardRef<
  SVGSVGElement,
  PanelCloseRightSolidIconProps
>(function PanelCloseRightSolidIcon(props: PanelCloseRightSolidIconProps, ref) {
  return (
    <Icon
      data-testid="PanelCloseRightSolidIcon"
      aria-label="panel close right solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path fillRule="evenodd" d="M14.333 14.333H11V1.667h3.333Z" />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M14.333 14.333H1.667V1.667h12.666Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M13.833 14.333H2.167q-.5 0-.5-.5V2.167q0-.5.5-.5h11.666q.5 0 .5.5v11.666q0 .5-.5.5Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M11 14.333V1.667m.5 12.666q-.5 0-.5-.5m-.5.5q.5 0 .5-.5m.5-12.166q-.5 0-.5.5m-.5-.5q.5 0 .5.5M3.667 8h4.666M6 10.333 8.333 8 6 5.667"
        />
      </g>
    </Icon>
  );
});
