// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PasteIconProps = IconProps;

export const PasteIcon = forwardRef<SVGSVGElement, PasteIconProps>(
  function PasteIcon(props: PasteIconProps, ref) {
    return (
      <Icon
        data-testid="PasteIcon"
        aria-label="paste"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="M5 2.5H2.5v12h11v-12H11" />
            <path d="M5 1.5h6v3H5Zm0 6h6m-6 3h6" />
          </g>
        </g>
      </Icon>
    );
  },
);
