// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PiIconProps = IconProps;

export const PiIcon = forwardRef<SVGSVGElement, PiIconProps>(function PiIcon(
  props: PiIconProps,
  ref,
) {
  return (
    <Icon
      data-testid="PiIcon"
      aria-label="pi"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M2 3.5h12m-8.5 0V11q0 2.5-2.5 2.5m7.5-10V12q0 1.5 1.5 1.5h2"
        />
      </g>
    </Icon>
  );
});
