// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PinIconProps = IconProps;

export const PinIcon = forwardRef<SVGSVGElement, PinIconProps>(function PinIcon(
  props: PinIconProps,
  ref,
) {
  return (
    <Icon
      data-testid="PinIcon"
      aria-label="pin"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="m10.374 1.307 4.32 4.319-1.728 1.727-.864-.863-3.887 3.887v3.455l-.864.863L1.305 8.65l.863-.864h3.455l3.888-3.887-.864-.864ZM4.328 11.672l-3.023 3.023"
        />
      </g>
    </Icon>
  );
});
