// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PivotIconProps = IconProps;

export const PivotIcon = forwardRef<SVGSVGElement, PivotIconProps>(
  function PivotIcon(props: PivotIconProps, ref) {
    return (
      <Icon
        data-testid="PivotIcon"
        aria-label="pivot"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="M1 1h14v14H1Z" />
            <path d="M4.23 10.333h5.744V4.41M7.82 6.564 9.974 4.41l2.154 2.154M6.385 8.18 4.23 10.333l2.154 2.154" />
          </g>
        </g>
      </Icon>
    );
  },
);
