// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PlaceInIconProps = IconProps;

export const PlaceInIcon = forwardRef<SVGSVGElement, PlaceInIconProps>(
  function PlaceInIcon(props: PlaceInIconProps, ref) {
    return (
      <Icon
        data-testid="PlaceInIcon"
        aria-label="place in"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M0 12h12V6h-1v5H1V1h5V0H0z" />
        <path d="M6 6V2h1v2.293L11.293 0 12 .707 7.707 5H10v1z" />
      </Icon>
    );
  },
);
