// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type PotFoodIconProps = IconProps;

export const PotFoodIcon = forwardRef<SVGSVGElement, PotFoodIconProps>(
  function PotFoodIcon(props: PotFoodIconProps, ref) {
    return (
      <Icon
        data-testid="PotFoodIcon"
        aria-label="pot food"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.038 6.808h11.924v1.788c0 3.29-2.671 5.366-5.962 5.366s-5.962-2.075-5.962-5.366Z"
          />
          <path
            fillRule="evenodd"
            d="M3.827 6.808c.596-1.789 3.577-1.789 4.173 0Z"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M.25 8h1.788m11.924 0h1.788M11.577.25c0 1.59-1.192 2.583-1.192 4.173M14.558.25c0 1.59-1.193 2.583-1.193 4.173"
          />
          <path fillRule="evenodd" d="M5.02 13.962h5.96v1.788H5.02Z" />
        </g>
      </Icon>
    );
  },
);
