// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ProgressClosedIconProps = IconProps;

export const ProgressClosedIcon = forwardRef<
  SVGSVGElement,
  ProgressClosedIconProps
>(function ProgressClosedIcon(props: ProgressClosedIconProps, ref) {
  return (
    <Icon
      data-testid="ProgressClosedIcon"
      aria-label="progress closed"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M4 4h4v4H4z" />
      <path
        fillRule="evenodd"
        d="M6 12A6 6 0 1 0 6 0a6 6 0 0 0 0 12M3 9V3h6v6z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
