// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ProtectionSolidIconProps = IconProps;

export const ProtectionSolidIcon = forwardRef<
  SVGSVGElement,
  ProtectionSolidIconProps
>(function ProtectionSolidIcon(props: ProtectionSolidIconProps, ref) {
  return (
    <Icon
      data-testid="ProtectionSolidIcon"
      aria-label="protection solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M8 1.5c-2.167 1.333-3.8 1.7-5.5 2 0 4.833 1.167 8.967 5.5 11 4.333-2.033 5.5-6.167 5.5-11-1.7-.3-3.333-.667-5.5-2Z"
        />
        <path
          fillRule="evenodd"
          d="M8 1.5c2.167 1.333 3.8 1.7 5.5 2 0 4.833-1.167 8.967-5.5 11Z"
        />
      </g>
    </Icon>
  );
});
