// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ReceiptSolidIconProps = IconProps;

export const ReceiptSolidIcon = forwardRef<
  SVGSVGElement,
  ReceiptSolidIconProps
>(function ReceiptSolidIcon(props: ReceiptSolidIconProps, ref) {
  return (
    <Icon
      data-testid="ReceiptSolidIcon"
      aria-label="receipt solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="m3.586 1.624 1.471.98 1.472-.98L8 2.604l1.471-.98 1.472.98 1.471-.98v12.752l-1.471-.98-1.472.98L8 13.396l-1.471.98-1.472-.98-1.471.98Zm1.962 3.433h4.904v.981H5.548Zm0 2.453h4.904v.98H5.548Zm0 2.452H8.49v.98H5.548Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="m3.586 1.624 1.471.98 1.472-.98L8 2.604l1.471-.98 1.472.98 1.471-.98v12.752l-1.471-.98-1.472.98L8 13.396l-1.471.98-1.472-.98-1.471.98Z"
        />
      </g>
    </Icon>
  );
});
