// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ReceiptSolidIconProps = IconProps;

export const ReceiptSolidIcon = forwardRef<
  SVGSVGElement,
  ReceiptSolidIconProps
>(function ReceiptSolidIcon(props: ReceiptSolidIconProps, ref) {
  return (
    <Icon
      data-testid="ReceiptSolidIcon"
      aria-label="receipt solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="m3.5 1.5 1.5 1 1.5-1 1.5 1 1.5-1 1.5 1 1.5-1v13l-1.5-1-1.5 1-1.5-1-1.5 1-1.5-1-1.5 1Zm2 3.5h5v1h-5Zm0 2.5h5v1h-5Zm0 2.5h3v1h-3Z"
        />
      </g>
    </Icon>
  );
});
