// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ReceiptIconProps = IconProps;

export const ReceiptIcon = forwardRef<SVGSVGElement, ReceiptIconProps>(
  function ReceiptIcon(props: ReceiptIconProps, ref) {
    return (
      <Icon
        data-testid="ReceiptIcon"
        aria-label="receipt"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="m3.5 1.5 1.5 1 1.5-1 1.5 1 1.5-1 1.5 1 1.5-1v13l-1.5-1-1.5 1-1.5-1-1.5 1-1.5-1-1.5 1Zm2 4h5M5.5 8h5m-5 2.5h3"
          />
        </g>
      </Icon>
    );
  },
);
