// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, IconProps } from "../icon";

export type RedoIconProps = IconProps;

export const RedoIcon = forwardRef<SVGSVGElement, RedoIconProps>(
  function RedoIcon(props: RedoIconProps, ref) {
    return (
      <Icon
        data-testid="RedoIcon"
        aria-label="redo"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M4.706 10.83A5 5 0 1 1 10.33 3.5H8v1h4v-4h-1v2.183A6.034 6.034 0 0 0 9.744 1.31a6 6 0 1 0-5.296 10.486l.258-.965Z" />
      </Icon>
    );
  }
);
