// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type Replay15IconProps = IconProps;

export const Replay15Icon = forwardRef<SVGSVGElement, Replay15IconProps>(
  function Replay15Icon(props: Replay15IconProps, ref) {
    return (
      <Icon
        data-testid="Replay15Icon"
        aria-label="replay 15"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.314 3.917C3.231 3 4.17 1.999 5.371 1.512A7 7 0 1 1 1 8m1.314-7v2.917h2.917"
          />
          <path d="M2.314 1.828a.894.894 0 0 0 1.47.684c-.517.436-.996.931-1.47 1.405z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M2.314 1.828a.894.894 0 0 0 1.47.684"
          />
          <path d="M4.575 3.917a.894.894 0 0 1-.552-1.599c-.61.479-1.164 1.054-1.709 1.599z" />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M4.575 3.917a.894.894 0 0 1-.552-1.599"
          />
          <path
            fillRule="evenodd"
            d="M6.378 5.503v4.927h-.623V6.28L4.5 6.738v-.562l1.78-.673Z"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.18)"
            d="M6.378 5.503v4.927h-.623V6.28L4.5 6.738v-.562l1.78-.673Z"
          />
          <path
            fillRule="evenodd"
            d="m9.094 8.098-.498-.128.245-2.44h2.514v.575H9.37l-.148 1.333q.134-.077.341-.145t.476-.067q.34 0 .61.116t.459.332.291.518.101.676q0 .354-.096.65t-.288.516-.483.342-.684.121q-.297 0-.56-.082-.265-.083-.472-.253t-.336-.424-.164-.597h.593q.04.276.161.464.121.189.318.285t.46.096q.222 0 .393-.078.172-.077.29-.222t.18-.35.062-.461q0-.232-.064-.43t-.19-.347-.308-.231-.417-.082q-.313 0-.473.084t-.328.229"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.18)"
            d="m9.094 8.098-.498-.128.245-2.44h2.514v.575H9.37l-.148 1.333q.134-.077.341-.145t.476-.067q.34 0 .61.116t.459.332.291.518.101.676q0 .354-.096.65t-.288.516-.483.342-.684.121q-.297 0-.56-.082-.265-.083-.472-.253t-.336-.424-.164-.597h.593q.04.276.161.464.121.189.318.285t.46.096q.222 0 .393-.078.172-.077.29-.222t.18-.35.062-.461q0-.232-.064-.43t-.19-.347-.308-.231-.417-.082q-.313 0-.473.084t-.328.229Z"
          />
        </g>
      </Icon>
    );
  },
);
