// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type RestoreIconProps = IconProps;

export const RestoreIcon = forwardRef<SVGSVGElement, RestoreIconProps>(
  function RestoreIcon(props: RestoreIconProps, ref) {
    return (
      <Icon
        data-testid="RestoreIcon"
        aria-label="restore"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M12 0H0v6h1V3h10v8H6v1h6V0Z" />
        <path d="m4.45 6.5 1.06 1.06-2.974 2.976L4 12H0V8l1.475 1.475L4.45 6.5Z" />
      </Icon>
    );
  },
);
