// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SaltShakerIconProps = IconProps;

export const SaltShakerIcon = forwardRef<SVGSVGElement, SaltShakerIconProps>(
  function SaltShakerIcon(props: SaltShakerIconProps, ref) {
    return (
      <Icon
        data-testid="SaltShakerIcon"
        aria-label="salt shaker"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M5.346 5.248 6.957 6.86 9.26 5.25H5.346Z" />
        <path
          fillRule="evenodd"
          d="M2.512 5.243 5.966.386A1 1 0 0 1 7.462.293L11.71 4.54a1 1 0 0 1-.093 1.496L6.761 9.49a3.002 3.002 0 0 1-4.243 0 3.008 3.008 0 0 1-.006-4.247Zm1.332-.083 3 3 3.67-2.57a.5.5 0 0 0 .068-.763L7.177 1.42a.5.5 0 0 0-.764.067L3.843 5.16Zm-.634.78a2.023 2.023 0 0 0 2.859 2.859l-2.86-2.86Z"
          clipRule="evenodd"
        />
        <path d="M1 8H0v1h1V8Zm-1 2h1v1H0v-1Zm3 1H2v1h1v-1Z" />
      </Icon>
    );
  },
);
