// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SaveIconProps = IconProps;

export const SaveIcon = forwardRef<SVGSVGElement, SaveIconProps>(
  function SaveIcon(props: SaveIconProps, ref) {
    return (
      <Icon
        data-testid="SaveIcon"
        aria-label="save"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path
          fillRule="evenodd"
          d="M10 6H2v4h8V6ZM9 7H3v2h6V7Z"
          clipRule="evenodd"
        />
        <path
          fillRule="evenodd"
          d="M0 0v12h12V3.293L8.707 0H0Zm3 1H1v10h10V3.707L8.293 1H8v3H3V1Zm4 0H4v2h3V1Z"
          clipRule="evenodd"
        />
      </Icon>
    );
  },
);
