// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SchoolSolidIconProps = IconProps;

export const SchoolSolidIcon = forwardRef<SVGSVGElement, SchoolSolidIconProps>(
  function SchoolSolidIcon(props: SchoolSolidIconProps, ref) {
    return (
      <Icon
        data-testid="SchoolSolidIcon"
        aria-label="school solid"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M2.656 6.934 6.003 8.84l4.117-2.31v2.134l-.25.145-.346.199a211.5 211.5 0 0 1-1.254.723 98.91 98.91 0 0 1-2.026 1.134L5.993 11l-.248-.143-.004-.003-.017-.009-.063-.036-.236-.136-.83-.478c-.68-.39-1.57-.903-2.406-1.385l-.252-.145V6.519l.72.415Z" />
        <path d="m6.053 1.013 5.899 3.399c.04.023.054.067.045.107v2.485h-1.016v-1.85C9.673 5.926 7.5 7.2 6.051 7.981a.095.095 0 0 1-.095 0C5.448 7.69.926 5.09.048 4.581a.098.098 0 0 1 .003-.17c2.22-1.277 5.46-3.144 5.9-3.398a.102.102 0 0 1 .102 0Z" />
      </Icon>
    );
  },
);
