// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SchoolSolidIconProps = IconProps;

export const SchoolSolidIcon = forwardRef<SVGSVGElement, SchoolSolidIconProps>(
  function SchoolSolidIcon(props: SchoolSolidIconProps, ref) {
    return (
      <Icon
        data-testid="SchoolSolidIcon"
        aria-label="school solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fillRule="evenodd"
            d="m8 2.167 6.167 3.666L8 9.5 1.833 5.833Zm-4.5 5.89L8 10.734l4.5-2.675v2.775l-4.5 2.5-4.5-2.5Z"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M14.167 5.833v4"
          />
        </g>
      </Icon>
    );
  },
);
