// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SemanticSatisfiedSolidIconProps = IconProps;

export const SemanticSatisfiedSolidIcon = forwardRef<
  SVGSVGElement,
  SemanticSatisfiedSolidIconProps
>(function SemanticSatisfiedSolidIcon(
  props: SemanticSatisfiedSolidIconProps,
  ref,
) {
  return (
    <Icon
      data-testid="SemanticSatisfiedSolidIcon"
      aria-label="semantic satisfied solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M.25 8a7.75 7.75 0 1 0 15.5 0A7.75 7.75 0 1 0 .25 8m4-1.75a1 1 0 1 0 2 0 1 1 0 1 0-2 0m5.5 0a1 1 0 1 0 2 0 1 1 0 1 0-2 0m1.962 4.962a5.25 5.25 0 0 1-7.424 0l1.06-1.06a3.75 3.75 0 0 0 5.304 0Z"
        />
      </g>
    </Icon>
  );
});
