// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SemanticDissatisfiedSolidIconProps = IconProps;

export const SemanticDissatisfiedSolidIcon = forwardRef<
  SVGSVGElement,
  SemanticDissatisfiedSolidIconProps
>(function SemanticDissatisfiedSolidIcon(
  props: SemanticDissatisfiedSolidIconProps,
  ref,
) {
  return (
    <Icon
      data-testid="SemanticDissatisfiedSolidIcon"
      aria-label="semantic dissatisfied solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M.25 8a7.75 7.75 0 1 0 15.5 0A7.75 7.75 0 1 0 .25 8m4-1.75a1 1 0 1 0 2 0 1 1 0 1 0-2 0m5.5 0a1 1 0 1 0 2 0 1 1 0 1 0-2 0m-5.462 4.538a5.25 5.25 0 0 1 7.424 0l-1.06 1.06a3.75 3.75 0 0 0-5.304 0Z"
        />
      </g>
    </Icon>
  );
});
