// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, IconProps } from "../icon";

export type SemanticSatisfiedIconProps = IconProps;

export const SemanticSatisfiedIcon = forwardRef<
  SVGSVGElement,
  SemanticSatisfiedIconProps
>(function SemanticSatisfiedIcon(props: SemanticSatisfiedIconProps, ref) {
  return (
    <Icon
      data-testid="SemanticSatisfiedIcon"
      aria-label="semantic satisfied"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path d="M5.874 9c.982 0 1.853-.471 2.4-1.2.27.202.512.438.723.7A3.993 3.993 0 0 1 5.874 10a3.993 3.993 0 0 1-3.123-1.5c.21-.262.454-.498.723-.7a2.995 2.995 0 0 0 2.4 1.2ZM5 5a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2Z" />
      <path
        fillRule="evenodd"
        d="M12 6A6 6 0 1 1 0 6a6 6 0 0 1 12 0Zm-1 0A5 5 0 1 1 1 6a5 5 0 0 1 10 0Z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
