// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SendIconProps = IconProps;

export const SendIcon = forwardRef<SVGSVGElement, SendIconProps>(
  function SendIcon(props: SendIconProps, ref) {
    return (
      <Icon
        data-testid="SendIcon"
        aria-label="send"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M1.5 2.5 13.833 8 1.5 13.5l2-5.5Zm2 5.5h10.333"
          />
        </g>
      </Icon>
    );
  },
);
