// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SignatureIconProps = IconProps;

export const SignatureIcon = forwardRef<SVGSVGElement, SignatureIconProps>(
  function SignatureIcon(props: SignatureIconProps, ref) {
    return (
      <Icon
        data-testid="SignatureIcon"
        aria-label="signature"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            strokeWidth=".469"
            d="m1.25 8.75 2.5 2.5m0-2.5-2.5 2.5"
          />
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M5 11.5c2-1.5 5.333-7.167 4.333-8.667-1-1.666-3.166 3.5-3.166 7 0 2.5 1.833 2.5 2.833.5L10 8.5c-.5 2.5.5 2.833 1.5 1.5l.833-1c-.5 2.333.5 2.333 2.167 1"
          />
          <path
            fillRule="evenodd"
            d="M2.25 13.25h1.5v1.5h-1.5Zm2.5 0h1.5v1.5h-1.5Zm2.5 0h1.5v1.5h-1.5Zm2.5 0h1.5v1.5h-1.5Zm2.5 0h1.5v1.5h-1.5Z"
          />
        </g>
      </Icon>
    );
  },
);
