// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SignalIconProps = IconProps;

export const SignalIcon = forwardRef<SVGSVGElement, SignalIconProps>(
  function SignalIcon(props: SignalIconProps, ref) {
    return (
      <Icon
        data-testid="SignalIcon"
        aria-label="signal"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M3.586 2.483a7.172 7.172 0 0 0 0 11.034m8.828-11.034a7.172 7.172 0 0 1 0 11.034M5.24 4.69a4.414 4.414 0 0 0 0 6.62m5.518-6.62a4.414 4.414 0 0 1 0 6.62"
          />
          <path
            fillRule="evenodd"
            d="M6.897 8a1.103 1.103 0 1 0 2.206 0 1.103 1.103 0 1 0-2.206 0"
          />
        </g>
      </Icon>
    );
  },
);
