// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SortAscendIconProps = IconProps;

export const SortAscendIcon = forwardRef<SVGSVGElement, SortAscendIconProps>(
  function SortAscendIcon(props: SortAscendIconProps, ref) {
    return (
      <Icon
        data-testid="SortAscendIcon"
        aria-label="sort ascend"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M12 13.5v-11M9.5 5 12 2.5 14.5 5m-13-1.5h2M1.5 8h4m-4 4.5h6"
          />
        </g>
      </Icon>
    );
  },
);
