// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SortNumAscendIconProps = IconProps;

export const SortNumAscendIcon = forwardRef<
  SVGSVGElement,
  SortNumAscendIconProps
>(function SortNumAscendIcon(props: SortNumAscendIconProps, ref) {
  return (
    <Icon
      data-testid="SortNumAscendIcon"
      aria-label="sort num ascend"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="M4.458 6.333h-.48v-3.07q0-.175.002-.301t.006-.231.013-.215q-.092.095-.172.161l-.199.165-.495.397-.258-.335L4.05 2h.409Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth=".124419"
          d="M4.458 6.333h-.48v-3.07q0-.175.002-.301t.006-.231.013-.215q-.092.095-.172.161l-.199.165-.495.397-.258-.335L4.05 2h.409Z"
        />
        <path
          fillRule="evenodd"
          d="M5.086 11.513q0 .394-.054.768t-.187.696-.357.566-.565.382-.81.137q-.128 0-.291-.016T2.555 14v-.427q.11.039.258.061t.29.022q.555 0 .872-.238.317-.239.456-.65t.157-.923h-.035q-.089.142-.233.262t-.348.193-.477.073q-.377 0-.657-.154t-.435-.448-.156-.708q0-.448.17-.775.17-.328.48-.506.307-.177.725-.177.32 0 .587.121t.464.363.305.597.109.827m-1.465-1.49q-.394 0-.638.257-.245.258-.245.777 0 .43.21.679t.65.249q.302 0 .523-.122t.34-.308.12-.382-.057-.398-.176-.372-.3-.275q-.18-.106-.427-.106"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth=".124419"
          d="M5.086 11.513q0 .394-.054.768t-.187.696-.357.566-.565.382-.81.137q-.128 0-.291-.016T2.555 14v-.427q.11.039.258.061t.29.022q.555 0 .872-.238.317-.239.456-.65t.157-.923h-.035q-.089.142-.233.262t-.348.193-.477.073q-.377 0-.657-.154t-.435-.448-.156-.708q0-.448.17-.775.17-.328.48-.506.307-.177.725-.177.32 0 .587.121t.464.363.305.597.109.827Zm-1.464-1.49q-.394 0-.638.257-.245.258-.245.777 0 .43.21.678t.65.25q.302 0 .523-.122t.34-.308.12-.383-.057-.397-.177-.372-.299-.276-.427-.105Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M12 2.5v11M9.5 11l2.5 2.5 2.5-2.5"
        />
      </g>
    </Icon>
  );
});
