// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SparkleSolidIconProps = IconProps;

export const SparkleSolidIcon = forwardRef<
  SVGSVGElement,
  SparkleSolidIconProps
>(function SparkleSolidIcon(props: SparkleSolidIconProps, ref) {
  return (
    <Icon
      data-testid="SparkleSolidIcon"
      aria-label="sparkle solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M6.421 2.336c1.092 4.524 1.716 5.148 6.24 6.24-4.524 1.091-5.148 1.715-6.24 6.238C5.33 10.291 4.706 9.667.182 8.575 4.706 7.484 5.33 6.86 6.422 2.336m7.018-1.169.624 1.715 1.716.624-1.716.624-.624 1.716-.624-1.716-1.716-.624 1.716-.624Z"
        />
      </g>
    </Icon>
  );
});
