// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SparkleRefreshIconProps = IconProps;

export const SparkleRefreshIcon = forwardRef<
  SVGSVGElement,
  SparkleRefreshIconProps
>(function SparkleRefreshIcon(props: SparkleRefreshIconProps, ref) {
  return (
    <Icon
      data-testid="SparkleRefreshIcon"
      aria-label="sparkle refresh"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <g
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
        >
          <path d="M12.908 3.15a6.941 6.941 0 1 0 2.033 4.909M10.016 3.15h2.892V.259" />
          <path
            strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.62)"
            d="M8 4.233c.67 2.774 1.052 3.156 3.825 3.826C9.052 8.729 8.67 9.11 8 11.884 7.33 9.111 6.948 8.728 4.175 8.06 6.948 7.389 7.33 7.007 8 4.233Z"
          />
        </g>
      </g>
    </Icon>
  );
});
