// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type StethoscopeSolidIconProps = IconProps;

export const StethoscopeSolidIcon = forwardRef<
  SVGSVGElement,
  StethoscopeSolidIconProps
>(function StethoscopeSolidIcon(props: StethoscopeSolidIconProps, ref) {
  return (
    <Icon
      data-testid="StethoscopeSolidIcon"
      aria-label="stethoscope solid"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M3.484.5h-1V1H1v3.5a3.5 3.5 0 0 0 3 3.465v1.05A2.99 2.99 0 0 0 7.004 12 2.983 2.983 0 0 0 10 9.016V7.415a1.5 1.5 0 1 0-1 0v1.6A1.983 1.983 0 0 1 7.004 11 1.99 1.99 0 0 1 5 9.016V7.965A3.5 3.5 0 0 0 8 4.5V1H6.5V.5h-1v2h1V2H7v2.5a2.5 2.5 0 0 1-5 0V2h.484v.5h1v-2Z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
