// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type StorageIconProps = IconProps;

export const StorageIcon = forwardRef<SVGSVGElement, StorageIconProps>(
  function StorageIcon(props: StorageIconProps, ref) {
    return (
      <Icon
        data-testid="StorageIcon"
        aria-label="storage"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M1 2.077h14v3.23H1Zm1.077 3.231h11.846v8.615H2.077Zm3.231 3.23h5.384"
          />
        </g>
      </Icon>
    );
  },
);
