// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SuccessTickIconProps = IconProps;

/** @deprecated since 1.13.0. Use `CheckmarkIcon` instead. */
export const SuccessTickIcon = forwardRef<SVGSVGElement, SuccessTickIconProps>(
  function SuccessTickIcon(props: SuccessTickIconProps, ref) {
    return (
      <Icon
        data-testid="SuccessTickIcon"
        aria-label="success tick"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M2.793 8.457 6.5 12.164l6.707-6.707-1.414-1.414L6.5 9.336 4.207 7.043Z"
          />
        </g>
      </Icon>
    );
  },
);
