// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SuccessCircleSolidIconProps = IconProps;

export const SuccessCircleSolidIcon = forwardRef<
  SVGSVGElement,
  SuccessCircleSolidIconProps
>(function SuccessCircleSolidIcon(props: SuccessCircleSolidIconProps, ref) {
  return (
    <Icon
      data-testid="SuccessCircleSolidIcon"
      aria-label="success circle solid"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M6 12A6 6 0 1 0 6 0a6 6 0 0 0 0 12Zm3.75-7.984L4.952 9.332 2 6.582l1.027-1.098L4.875 7.2l3.772-4.208L9.75 4.016Z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
