// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SumSolidIconProps = IconProps;

export const SumSolidIcon = forwardRef<SVGSVGElement, SumSolidIconProps>(
  function SumSolidIcon(props: SumSolidIconProps, ref) {
    return (
      <Icon
        data-testid="SumSolidIcon"
        aria-label="sum solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fillRule="evenodd"
            d="M2.5 2h11v3H12V3.5H5L9 8l-4 4.5h7V11h1.5v3h-11v-1.5l4-4.5-4-4.5Z"
          />
        </g>
      </Icon>
    );
  },
);
