// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type SyncIconProps = IconProps;

export const SyncIcon = forwardRef<SVGSVGElement, SyncIconProps>(
  function SyncIcon(props: SyncIconProps, ref) {
    return (
      <Icon
        data-testid="SyncIcon"
        aria-label="sync"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M7.296 1.17A5 5 0 0 0 1 6H0a6 6 0 0 1 11.002-3.317V.5h1v4h-4v-1h2.33A5 5 0 0 0 9.12 2.09a5 5 0 0 0-1.825-.92m-2.589 9.66A5 5 0 0 0 11 6h1A6 6 0 0 1 1 9.317V11.5H0v-4h4v1H1.67a5 5 0 0 0 1.21 1.41 5 5 0 0 0 1.826.92" />
      </Icon>
    );
  },
);
