// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TailsSolidIconProps = IconProps;

export const TailsSolidIcon = forwardRef<SVGSVGElement, TailsSolidIconProps>(
  function TailsSolidIcon(props: TailsSolidIconProps, ref) {
    return (
      <Icon
        data-testid="TailsSolidIcon"
        aria-label="tails solid"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="m.56.25 4.96 1.86h4.96L15.44.25l-2.48 5.58 2.48 6.2L8 15.75.56 12.03l2.48-6.2Zm4.175 6.407a.992.992 0 1 0 1.984 0 .992.992 0 1 0-1.984 0m4.546 0a.992.992 0 1 0 1.984 0 .992.992 0 1 0-1.984 0M7.067 9.243l.933.933.933-.933.614.614-1.24 1.24q-.03.03-.066.054-.035.024-.075.04t-.081.025-.085.008-.085-.008-.081-.025-.075-.04-.066-.054l-1.24-1.24Zm-5.338 1.119Q5.472 9.738 8 14.206q2.528-4.468 6.271-3.844l-.142.856q-3.404-.567-5.74 4.106-.065.13-.195.194-.038.02-.08.03-.04.012-.083.015t-.085-.002q-.043-.006-.083-.02-.04-.013-.078-.034t-.07-.05-.058-.06-.045-.073q-2.337-4.673-5.74-4.106Z"
          />
        </g>
      </Icon>
    );
  },
);
