// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TextBoldIconProps = IconProps;

export const TextBoldIcon = forwardRef<SVGSVGElement, TextBoldIconProps>(
  function TextBoldIcon(props: TextBoldIconProps, ref) {
    return (
      <Icon
        data-testid="TextBoldIcon"
        aria-label="text bold"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth="var(--icon-strokeWidth, 1)">
          <path
            fillRule="evenodd"
            d="M8.165 15.75h-5.93V.25h5.409q1.351 0 2.421.255 1.07.256 1.815.778t1.14 1.314.393 1.88q0 .957-.43 1.766t-1.347 1.32q-.203.107-.426.192.5.128.883.362.873.511 1.272 1.33t.4 1.757q0 1.49-.65 2.507t-1.9 1.528-3.05.511m.139-6.803H5.429v4.312h2.736q.841 0 1.373-.272.533-.271.788-.74.256-.468.256-1.075 0-.68-.23-1.181-.228-.5-.729-.772-.5-.272-1.32-.272M5.43 6.755h2.215q.883 0 1.447-.23.565-.228.847-.67t.282-1.08q0-.725-.272-1.172-.271-.447-.84-.649-.57-.202-1.465-.202H5.43Z"
          />
        </g>
      </Icon>
    );
  },
);
