// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TextAlignRightIconProps = IconProps;

export const TextAlignRightIcon = forwardRef<
  SVGSVGElement,
  TextAlignRightIconProps
>(function TextAlignRightIcon(props: TextAlignRightIconProps, ref) {
  return (
    <Icon
      data-testid="TextAlignRightIcon"
      aria-label="text align right"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M.25 2.188h15.5M4.125 8H15.75M2.188 13.813H15.75"
        />
      </g>
    </Icon>
  );
});
