// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TextAlignRightIconProps = IconProps;

export const TextAlignRightIcon = forwardRef<
  SVGSVGElement,
  TextAlignRightIconProps
>(function TextAlignRightIcon(props: TextAlignRightIconProps, ref) {
  return (
    <Icon
      data-testid="TextAlignRightIcon"
      aria-label="text align right"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M2 3.5h12M5 8h9M3.5 12.5H14"
        />
      </g>
    </Icon>
  );
});
