// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TextUnderlineIconProps = IconProps;

export const TextUnderlineIcon = forwardRef<
  SVGSVGElement,
  TextUnderlineIconProps
>(function TextUnderlineIcon(props: TextUnderlineIconProps, ref) {
  return (
    <Icon
      data-testid="TextUnderlineIcon"
      aria-label="text underline"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fillRule="evenodd"
          d="M12.38.569V7.96q0 1.211-.489 2.157-.488.946-1.472 1.489t-2.47.543q-2.118 0-3.223-1.149Q3.62 9.852 3.62 7.93V.569h1.336v7.4q0 1.454.77 2.243T8.027 11q1.048 0 1.716-.379t.992-1.063q.324-.683.324-1.582V.569Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          strokeWidth="calc(var(--icon-strokeWidth, 1) * 0.4071)"
          d="M12.38.569V7.96q0 1.211-.489 2.157-.488.946-1.472 1.489t-2.47.543q-2.118 0-3.223-1.149Q3.62 9.852 3.62 7.93V.569h1.336v7.4q0 1.454.77 2.243T8.027 11q1.048 0 1.716-.379t.992-1.063q.324-.683.324-1.582V.569Z"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.386 15h13.228"
        />
      </g>
    </Icon>
  );
});
