// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TextAlignLeftIconProps = IconProps;

export const TextAlignLeftIcon = forwardRef<
  SVGSVGElement,
  TextAlignLeftIconProps
>(function TextAlignLeftIcon(props: TextAlignLeftIconProps, ref) {
  return (
    <Icon
      data-testid="TextAlignLeftIcon"
      aria-label="text align left"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M.25 2.188h15.5M.25 8h11.625M.25 13.813h13.563"
        />
      </g>
    </Icon>
  );
});
