// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TextItalicsIconProps = IconProps;

export const TextItalicsIcon = forwardRef<SVGSVGElement, TextItalicsIconProps>(
  function TextItalicsIcon(props: TextItalicsIconProps, ref) {
    return (
      <Icon
        data-testid="TextItalicsIcon"
        aria-label="text italics"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="m2.829 11 .142-.6.629-.029c.5-.014.929-.314 1.043-.785l1.614-7a1.6 1.6 0 0 0 .043-.343c0-.414-.271-.586-.843-.614L4.871 1.6 5 1h4.171l-.142.6-.629.029c-.586.028-.929.314-1.029.785L5.7 9.571c-.014.086-.029.172-.029.243 0 .372.272.543.686.557l.786.029L7 11z" />
      </Icon>
    );
  },
);
