// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ThumbsDownSolidIconProps = IconProps;

export const ThumbsDownSolidIcon = forwardRef<
  SVGSVGElement,
  ThumbsDownSolidIconProps
>(function ThumbsDownSolidIcon(props: ThumbsDownSolidIconProps, ref) {
  return (
    <Icon
      data-testid="ThumbsDownSolidIcon"
      aria-label="thumbs down solid"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fillRule="evenodd"
          d="M14.5 9.5h-2v-7h2Zm-4-7v7L8 14H6.5v-4H3q-1.5 0-1.5-1.5l1.5-6Z"
        />
      </g>
    </Icon>
  );
});
