// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TriangleDownIconProps = IconProps;

export const TriangleDownIcon = forwardRef<
  SVGSVGElement,
  TriangleDownIconProps
>(function TriangleDownIcon(props: TriangleDownIconProps, ref) {
  return (
    <Icon
      data-testid="TriangleDownIcon"
      aria-label="triangle down"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path fillRule="evenodd" d="M.25 3.374h15.5L8 12.674Z" />
      </g>
    </Icon>
  );
});
