// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type TriangleRightDownIconProps = IconProps;

export const TriangleRightDownIcon = forwardRef<
  SVGSVGElement,
  TriangleRightDownIconProps
>(function TriangleRightDownIcon(props: TriangleRightDownIconProps, ref) {
  return (
    <Icon
      data-testid="TriangleRightDownIcon"
      aria-label="triangle right down"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path fillRule="evenodd" d="M3.333 12.667h9.334V3.333Z" />
      </g>
    </Icon>
  );
});
