// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, IconProps } from "../icon";

export type TypeIconProps = IconProps;

export const TypeIcon = forwardRef<SVGSVGElement, TypeIconProps>(
  function TypeIcon(props: TypeIconProps, ref) {
    return (
      <Icon
        data-testid="TypeIcon"
        aria-label="type"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path d="M3 3v2h2v4h2V5h2V3H3Z" />
        <path
          fillRule="evenodd"
          d="M0 0h3v1h6V0h3v3h-1v6h1v3H9v-1H3v1H0V9h1V3H0V0Zm3 10h6V9h1V3H9V2H3v1H2v6h1v1ZM1 1h1v1H1V1Zm0 9h1v1H1v-1Zm10-9h-1v1h1V1Zm-1 9h1v1h-1v-1Z"
          clipRule="evenodd"
        />
      </Icon>
    );
  }
);
