// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type UniversalAccessIconProps = IconProps;

export const UniversalAccessIcon = forwardRef<
  SVGSVGElement,
  UniversalAccessIconProps
>(function UniversalAccessIcon(props: UniversalAccessIconProps, ref) {
  return (
    <Icon
      data-testid="UniversalAccessIcon"
      aria-label="universal access"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth=".67">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.5 8a6.5 6.5 0 1 0 13 0 6.5 6.5 0 1 0-13 0Z"
        />
        <path
          fillRule="evenodd"
          d="M7.1 4.5a.9.9 0 1 0 1.8 0 .9.9 0 1 0-1.8 0M7 7l-3-.5-.2.9L7 8l-1 4h1l1-2.5L9 12h1L9 8l3.2-.6-.2-.9L9 7Z"
        />
      </g>
    </Icon>
  );
});
