// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type UnlockedIconProps = IconProps;

export const UnlockedIcon = forwardRef<SVGSVGElement, UnlockedIconProps>(
  function UnlockedIcon(props: UnlockedIconProps, ref) {
    return (
      <Icon
        data-testid="UnlockedIcon"
        aria-label="unlocked"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M4.5 7V5a3.5 3.5 0 0 1 6.733-1.333M2.9 7h10.2q.4 0 .4.4v6.2q0 .4-.4.4H2.9q-.4 0-.4-.4V7.4q0-.4.4-.4Z"
          />
          <path fillRule="evenodd" d="M7.5 10.7a1 1 0 1 1 1 0v1.8h-1Z" />
        </g>
      </Icon>
    );
  },
);
