// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type UrgencyOntimeIconProps = IconProps;

export const UrgencyOntimeIcon = forwardRef<
  SVGSVGElement,
  UrgencyOntimeIconProps
>(function UrgencyOntimeIcon(props: UrgencyOntimeIconProps, ref) {
  return (
    <Icon
      data-testid="UrgencyOntimeIcon"
      aria-label="urgency ontime"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.531 8 8 3.522 14.469 8 8 12.478Z"
        />
      </g>
    </Icon>
  );
});
