// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type UserSearchIconProps = IconProps;

export const UserSearchIcon = forwardRef<SVGSVGElement, UserSearchIconProps>(
  function UserSearchIcon(props: UserSearchIconProps, ref) {
    return (
      <Icon
        data-testid="UserSearchIcon"
        aria-label="user search"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M3.8 4.8a2.2 2.2 0 1 0 4.4 0 2.2 2.2 0 1 0-4.4 0ZM1.5 14v-2q0-3 4.5-3 .667 0 1.235.066M8.672 14H1.5M9 10.5a2.5 2.5 0 1 0 5 0 2.5 2.5 0 1 0-5 0Zm4.333 1.833 2 2"
          />
        </g>
      </Icon>
    );
  },
);
