// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type VisibleIconProps = IconProps;

export const VisibleIcon = forwardRef<SVGSVGElement, VisibleIconProps>(
  function VisibleIcon(props: VisibleIconProps, ref) {
    return (
      <Icon
        data-testid="VisibleIcon"
        aria-label="visible"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <g
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          >
            <path d="M1.5 8Q8-2.5 14.5 8 8 18.5 1.5 8Z" />
            <path d="M6 8a2 2 0 1 0 4 0 2 2 0 1 0-4 0Z" />
          </g>
        </g>
      </Icon>
    );
  },
);
