// WARNING: This file was generated by a script. Do not modify it manually
import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type WeightSolidIconProps = IconProps;

export const WeightSolidIcon = forwardRef<SVGSVGElement, WeightSolidIconProps>(
  function WeightSolidIcon(props: WeightSolidIconProps, ref) {
    return (
      <Icon
        data-testid="WeightSolidIcon"
        aria-label="weight solid"
        viewBox="0 0 12 12"
        ref={ref}
        {...props}
      >
        <path
          fillRule="evenodd"
          d="M8 4a2.5 2.5 0 1 0-4 0H2l-2 8h12l-2-8H8Zm-.5-1.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z"
          clipRule="evenodd"
        />
      </Icon>
    );
  },
);
