// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type WifiDisabledIconProps = IconProps;

export const WifiDisabledIcon = forwardRef<
  SVGSVGElement,
  WifiDisabledIconProps
>(function WifiDisabledIcon(props: WifiDisabledIconProps, ref) {
  return (
    <Icon
      data-testid="WifiDisabledIcon"
      aria-label="wifi disabled"
      viewBox="0 0 16 16"
      ref={ref}
      {...props}
    >
      <g strokeWidth="var(--icon-strokeWidth, 1)">
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M.754 4.767q.291-.27.583-.517m3.628-2.241q5.14-1.987 10.281 2.758M2.983 7.554q.43-.43.861-.787m4.45-1.713q2.361.138 4.723 2.5M5.213 10.34q.578-.579 1.157-.917"
        />
        <path
          fillRule="evenodd"
          d="M6.997 13.685a1.003 1.003 0 1 0 2.006 0 1.003 1.003 0 1 0-2.006 0"
        />
        <path
          fill="none"
          stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
          d="M1.311 1.422 14.689 14.8"
        />
      </g>
    </Icon>
  );
});
