// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type WoodlandIconProps = IconProps;

export const WoodlandIcon = forwardRef<SVGSVGElement, WoodlandIconProps>(
  function WoodlandIcon(props: WoodlandIconProps, ref) {
    return (
      <Icon
        data-testid="WoodlandIcon"
        aria-label="woodland"
        viewBox="0 0 16 16"
        ref={ref}
        {...props}
      >
        <g strokeWidth=".67">
          <path
            fill="none"
            stroke="var(--saltIcon-color, var(--icon-color, currentColor))"
            d="M4.5 12.5a3.5 3.5 0 0 1-1-6.833 4.5 4.5 0 0 1 9 0 3.5 3.5 0 0 1-1 6.833Zm3.5-8V15m0-6.5 3-2M8 11 6 9"
          />
        </g>
      </Icon>
    );
  },
);
