// WARNING: This file was generated by a script. Do not modify it manually

import { forwardRef } from "react";

import { Icon, type IconProps } from "../icon";

export type ZipIconProps = IconProps;

export const ZipIcon = forwardRef<SVGSVGElement, ZipIconProps>(function ZipIcon(
  props: ZipIconProps,
  ref,
) {
  return (
    <Icon
      data-testid="ZipIcon"
      aria-label="zip"
      viewBox="0 0 12 12"
      ref={ref}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M1 0v6h1V1h5v3h3v2h1V2L9 0zm9 3v-.586L8.586 1H8v2z"
        clipRule="evenodd"
      />
      <path d="M4.842 11.997H1.25v-.564l2.543-3.736H1.329V7h3.445v.56L2.23 11.3h2.611zM5.75 7v4.997h.82V7z" />
      <path
        fillRule="evenodd"
        d="M10.364 7.396Q9.92 7 8.953 7H7.5v4.997h.82v-1.873h.534q.546 0 .919-.13.375-.13.605-.352.23-.225.328-.516.102-.294.103-.619 0-.714-.445-1.11M8.32 7.68h.578q.554 0 .813.212.264.212.264.646 0 .325-.14.523a.8.8 0 0 1-.41.29q-.27.09-.657.09H8.32z"
        clipRule="evenodd"
      />
    </Icon>
  );
});
