import { Button, FlowLayout, StackLayout } from "@salt-ds/core";
import type { ReactElement } from "react";

export const FocusableWhenDisabled = (): ReactElement => (
  <StackLayout gap={3}>
    <FlowLayout>
      <Button
        appearance="solid"
        sentiment="accented"
        disabled
        focusableWhenDisabled
      >
        Solid
      </Button>
      <Button
        appearance="bordered"
        sentiment="accented"
        disabled
        focusableWhenDisabled
      >
        Bordered
      </Button>
      <Button
        appearance="transparent"
        sentiment="accented"
        disabled
        focusableWhenDisabled
      >
        Transparent
      </Button>
    </FlowLayout>
    <FlowLayout>
      <Button
        appearance="solid"
        sentiment="neutral"
        disabled
        focusableWhenDisabled
      >
        Solid
      </Button>
      <Button
        appearance="bordered"
        sentiment="neutral"
        disabled
        focusableWhenDisabled
      >
        Bordered
      </Button>
      <Button
        appearance="transparent"
        sentiment="neutral"
        disabled
        focusableWhenDisabled
      >
        Transparent
      </Button>
    </FlowLayout>
    <FlowLayout>
      <Button
        appearance="solid"
        sentiment="positive"
        disabled
        focusableWhenDisabled
      >
        Solid
      </Button>
      <Button
        appearance="bordered"
        sentiment="positive"
        disabled
        focusableWhenDisabled
      >
        Bordered
      </Button>
      <Button
        appearance="transparent"
        sentiment="positive"
        disabled
        focusableWhenDisabled
      >
        Transparent
      </Button>
    </FlowLayout>
    <FlowLayout>
      <Button
        appearance="solid"
        sentiment="negative"
        disabled
        focusableWhenDisabled
      >
        Solid
      </Button>
      <Button
        appearance="bordered"
        sentiment="negative"
        disabled
        focusableWhenDisabled
      >
        Bordered
      </Button>
      <Button
        appearance="transparent"
        sentiment="negative"
        disabled
        focusableWhenDisabled
      >
        Transparent
      </Button>
    </FlowLayout>
    <FlowLayout>
      <Button
        appearance="solid"
        sentiment="caution"
        disabled
        focusableWhenDisabled
      >
        Solid
      </Button>
      <Button
        appearance="bordered"
        sentiment="caution"
        disabled
        focusableWhenDisabled
      >
        Bordered
      </Button>
      <Button
        appearance="transparent"
        sentiment="caution"
        disabled
        focusableWhenDisabled
      >
        Transparent
      </Button>
    </FlowLayout>
  </StackLayout>
);
