import { Button, FlowLayout, StackLayout } from "@salt-ds/core";
import type { ReactElement } from "react";

export const FocusableWhenDisabled = (): ReactElement => (
  <StackLayout gap={3}>
    <FlowLayout>
      <Button
        appearance="filled"
        chrome="accent"
        disabled
        focusableWhenDisabled
      >
        Filled
      </Button>
      <Button
        appearance="outlined"
        chrome="accent"
        disabled
        focusableWhenDisabled
      >
        Outlined
      </Button>
      <Button
        appearance="minimal"
        chrome="accent"
        disabled
        focusableWhenDisabled
      >
        Minimal
      </Button>
    </FlowLayout>
    <FlowLayout>
      <Button
        appearance="filled"
        chrome="neutral"
        disabled
        focusableWhenDisabled
      >
        Filled
      </Button>
      <Button
        appearance="outlined"
        chrome="neutral"
        disabled
        focusableWhenDisabled
      >
        Outlined
      </Button>
      <Button
        appearance="minimal"
        chrome="neutral"
        disabled
        focusableWhenDisabled
      >
        Minimal
      </Button>
    </FlowLayout>
  </StackLayout>
);
