// Writes the pattern example manifest and the site's source loaders from each
// pattern example's import graph. Run with `--check` to verify they are current.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const examplesRoot = path.join(repositoryRoot, "site", "src", "examples");
const patternsRoot = path.join(examplesRoot, "patterns");
const manifestPath = path.join(patternsRoot, "manifest.json");
const sourceLoadersPath = path.join(
  repositoryRoot,
  "site",
  "src",
  "components",
  "components",
  "patternSourceLoaders.ts",
);
const textFile = /\.(?:css|js|jsx|ts|tsx)$/;
const importPattern =
  /(?:import|export)\s+(?:type\s+)?(?:[^"']*?\s+from\s+)?["']([^"']+)["']/g;

function toPosix(value) {
  return value.split(path.sep).join("/");
}

function packageName(specifier) {
  const parts = specifier.split("/");
  return specifier.startsWith("@") ? parts.slice(0, 2).join("/") : parts[0];
}

async function isFile(candidate) {
  try {
    return (await stat(candidate)).isFile();
  } catch {
    return false;
  }
}

async function resolveRelativeImport(importer, specifier) {
  const base = path.resolve(path.dirname(importer), specifier);
  const candidates = path.extname(specifier)
    ? [base]
    : [
        ...["", ".ts", ".tsx", ".js", ".jsx"].map((ext) => `${base}${ext}`),
        ...[".ts", ".tsx", ".js", ".jsx"].map((ext) =>
          path.join(base, `index${ext}`),
        ),
      ];
  const matches = [];
  for (const candidate of candidates) {
    if (await isFile(candidate)) matches.push(path.normalize(candidate));
  }
  const importerPath = toPosix(path.relative(repositoryRoot, importer));
  assert.equal(
    matches.length,
    1,
    `${importerPath}: ${specifier} must resolve to exactly one file; found ${matches.length}`,
  );
  assert.ok(
    matches[0].startsWith(`${examplesRoot}${path.sep}`),
    `${importerPath}: ${specifier} is outside site/src/examples`,
  );
  return matches[0];
}

/** Follows relative imports from the entry and records packages it uses. */
async function discover(entry) {
  const pending = [path.join(examplesRoot, entry)];
  const files = new Set();
  const externalDependencies = new Set();
  const saltPackages = new Set();

  while (pending.length > 0) {
    const current = pending.pop();
    if (files.has(current)) continue;
    assert.ok(await isFile(current), `${entry}: missing ${current}`);
    files.add(current);
    if (!textFile.test(current)) continue;

    const source = await readFile(current, "utf8");
    if (current.endsWith(".tsx")) externalDependencies.add("react");
    for (const [, specifier] of source.matchAll(importPattern)) {
      if (specifier.startsWith(".")) {
        pending.push(await resolveRelativeImport(current, specifier));
      } else {
        const dependency = packageName(specifier);
        (dependency.startsWith("@salt-ds/")
          ? saltPackages
          : externalDependencies
        ).add(dependency);
      }
    }
  }

  return {
    files: [...files]
      .map((file) => toPosix(path.relative(examplesRoot, file)))
      .sort(),
    saltPackages: [...saltPackages].sort(),
    externalDependencies: [...externalDependencies].sort(),
  };
}

async function patternIds() {
  const ids = [];
  for (const entry of await readdir(patternsRoot, { withFileTypes: true })) {
    if (
      entry.isDirectory() &&
      (await isFile(path.join(patternsRoot, entry.name, "index.tsx")))
    ) {
      ids.push(entry.name);
    }
  }
  return ids.sort();
}

function format(filePath, source) {
  const result = spawnSync(
    process.execPath,
    [
      require.resolve("@biomejs/biome/bin/biome"),
      "format",
      `--stdin-file-path=${filePath}`,
    ],
    { cwd: repositoryRoot, input: source, encoding: "utf8" },
  );
  if (result.status !== 0) {
    throw new Error(`Biome could not format ${filePath}:\n${result.stderr}`);
  }
  return result.stdout;
}

const examples = [];
for (const id of await patternIds()) {
  const entry = `patterns/${id}/index.tsx`;
  examples.push({ id, entry, ...(await discover(entry)) });
}

const manifest = format(
  manifestPath,
  `${JSON.stringify({ examples }, null, 2)}\n`,
);
const sourceFiles = [
  ...new Set(
    examples.flatMap(({ files }) =>
      files.filter((file) => textFile.test(file)),
    ),
  ),
].sort();
const sourceLoaders = format(
  sourceLoadersPath,
  [
    "// Generated by scripts/generatePatternExamples.mjs. Do not edit by hand.",
    "export const patternExampleLoaders = {",
    ...examples.map(
      ({ id }) =>
        `  ${JSON.stringify(id)}: () => import(${JSON.stringify(`../../examples/patterns/${id}`)}),`,
    ),
    "} as const;",
    "",
    "export const patternSourceLoaders = {",
    ...sourceFiles.map(
      (file) =>
        `  ${JSON.stringify(file)}: () => import(${JSON.stringify(`../../examples/${file}?raw`)}),`,
    ),
    "} as const;",
    "",
  ].join("\n"),
);

const outputs = [
  [manifestPath, manifest],
  [sourceLoadersPath, sourceLoaders],
];

if (process.argv.includes("--check")) {
  const stale = [];
  for (const [filePath, expected] of outputs) {
    const actual = await readFile(filePath, "utf8").catch(() => "");
    if (actual !== expected)
      stale.push(toPosix(path.relative(repositoryRoot, filePath)));
  }
  if (stale.length > 0) {
    console.error(
      `Pattern example files are out of date: ${stale.join(", ")}. Run yarn gen:pattern-examples.`,
    );
    process.exit(1);
  }
  console.log(`Checked ${examples.length} pattern examples.`);
} else {
  for (const [filePath, content] of outputs) {
    await writeFile(filePath, content);
  }
  console.log(`Wrote ${examples.length} pattern examples.`);
}
