name: "Build Storybook"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "24"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build Storybook
        run: yarn build-storybook
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
      - name: Upload Storybook Static
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: storybook-build
          path: ./storybook-static
          retention-days: 1
