name: "Performance"
on: push
jobs:
  lighthouse:
    if: ${{ false }} # Temporarily skip job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: "https://ui-toolkit.pages.dev/"
          uploadArtifacts: true # save results as an action artifacts
