import type { Options } from "highcharts";

export const heatmapOptions: Options = {
  chart: {
    type: "heatmap",
    styledMode: true,
  },
  title: {
    text: "Sample heatmap",
  },
  xAxis: {
    type: "category",
    startOnTick: false,
    endOnTick: false,
    categories: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
  },
  yAxis: {
    type: "category",
    startOnTick: false,
    endOnTick: false,
    reversed: true,
    categories: [
      "Consumer",
      "Financials",
      "Healthcare",
      "Real Estate",
      "Technology",
    ],
    title: {
      text: null,
    },
  },
  tooltip: {
    enabled: false,
  },
  plotOptions: {
    heatmap: {
      colsize: 1,
      rowsize: 1,
      borderWidth: 1,
      pointPadding: 0,
      dataLabels: {
        enabled: true,
        inside: true,
        align: "center",
        verticalAlign: "middle",
        style: {
          textOutline: "none",
        },
        formatter: function () {
          return typeof this.point.value === "number"
            ? String(this.point.value)
            : "";
        },
      },
    },
  },
  legend: {
    layout: "horizontal",
    align: "right",
    symbolWidth: 200,
    symbolHeight: 12,
  },
  colorAxis: {
    showInLegend: true,
    min: -50,
    max: 50,
  },
  series: [
    {
      name: "Performance",
      type: "heatmap",
      data: [
        [0, 0, -42],
        [0, 1, 4],
        [0, 2, 38],
        [0, 3, -3],
        [0, 4, 50],
        [1, 0, 2],
        [1, 1, -28],
        [1, 2, 5],
        [1, 3, 45],
        [1, 4, 0],
        [2, 0, 6],
        [2, 1, 3],
        [2, 2, -4],
        [2, 3, 11],
        [2, 4, -50],
        [3, 0, -35],
        [3, 1, 10],
        [3, 2, 1],
        [3, 3, 7],
        [3, 4, -5],
        [4, 0, 5],
        [4, 1, -1],
        [4, 2, 48],
        [4, 3, 2],
        [4, 4, 33],
        [5, 0, 10],
        [5, 1, 42],
        [5, 2, -6],
        [5, 3, 4],
        [5, 4, 8],
        [6, 0, -2],
        [6, 1, 3],
        [6, 2, 11],
        [6, 3, -46],
        [6, 4, 1],
        [7, 0, 4],
        [7, 1, -18],
        [7, 2, 6],
        [7, 3, 50],
        [7, 4, 3],
        [8, 0, 36],
        [8, 1, 2],
        [8, 2, -10],
        [8, 3, 5],
        [8, 4, -30],
        [9, 0, -3],
        [9, 1, 9],
        [9, 2, 4],
        [9, 3, -7],
        [9, 4, 11],
        [10, 0, 7],
        [10, 1, -50],
        [10, 2, 50],
        [10, 3, 0],
        [10, 4, -1],
        [11, 0, 1],
        [11, 1, 25],
        [11, 2, -40],
        [11, 3, 8],
        [11, 4, 4],
      ],
    },
  ],
};
