import type { Options } from "highcharts";

export const singleColorHeatmapOptions: Options = {
  chart: {
    type: "heatmap",
    styledMode: true,
  },
  title: {
    text: "Sales volume by region",
  },
  xAxis: {
    type: "category",
    startOnTick: false,
    endOnTick: false,
    categories: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
  },
  yAxis: {
    type: "category",
    startOnTick: false,
    endOnTick: false,
    reversed: true,
    categories: ["EMEA", "APAC", "AMER", "LATAM"],
    title: {
      text: null,
    },
  },
  tooltip: {
    enabled: false,
  },
  plotOptions: {
    heatmap: {
      colsize: 1,
      rowsize: 1,
      borderWidth: 1,
      pointPadding: 0,
      dataLabels: {
        enabled: true,
        inside: true,
        align: "center",
        verticalAlign: "middle",
        style: {
          textOutline: "none",
        },
        formatter: function () {
          return typeof this.point.value === "number"
            ? String(this.point.value)
            : "";
        },
      },
    },
  },
  legend: {
    layout: "horizontal",
    align: "right",
    symbolWidth: 200,
    symbolHeight: 12,
  },
  colorAxis: {
    showInLegend: true,
    min: 0,
    max: 100,
  },
  series: [
    {
      name: "Volume",
      type: "heatmap",
      data: [
        [0, 0, 72],
        [0, 1, 45],
        [0, 2, 88],
        [0, 3, 30],
        [1, 0, 65],
        [1, 1, 52],
        [1, 2, 74],
        [1, 3, 18],
        [2, 0, 80],
        [2, 1, 60],
        [2, 2, 92],
        [2, 3, 40],
        [3, 0, 55],
        [3, 1, 70],
        [3, 2, 63],
        [3, 3, 25],
        [4, 0, 90],
        [4, 1, 48],
        [4, 2, 100],
        [4, 3, 35],
        [5, 0, 78],
        [5, 1, 85],
        [5, 2, 67],
        [5, 3, 50],
        [6, 0, 42],
        [6, 1, 95],
        [6, 2, 58],
        [6, 3, 22],
        [7, 0, 68],
        [7, 1, 75],
        [7, 2, 82],
        [7, 3, 15],
        [8, 0, 83],
        [8, 1, 38],
        [8, 2, 96],
        [8, 3, 55],
        [9, 0, 50],
        [9, 1, 62],
        [9, 2, 71],
        [9, 3, 44],
        [10, 0, 76],
        [10, 1, 88],
        [10, 2, 54],
        [10, 3, 10],
        [11, 0, 60],
        [11, 1, 33],
        [11, 2, 79],
        [11, 3, 28],
      ],
    },
  ],
};
